### ISSUE TITLE
What's happening here?

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Waterfall#1]
Yeah, simple question.

**Comment by punkeel** [comment]
+1

**Comment by minecrafter** [comment]
Changing over to a patch-based system

**Comment by Techcable** [comment]
a Waterfall has an uneesicarily large diff with bungeecord.
I asked Tux if I could try and minimize the diff, and if we could switch to a patch-based system like spigot.
He said yes, and so from now on we won't be making unnecessary formatting changes, and will use patch files for our changes.
Updating bungeecord will be a simple `git submodule update` and rebuilding patches (like with paper).

I'm working on converting our changes as we speak.
