### ISSUE TITLE
web/jenkins offline

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#100]
cludflare report that jenkins and web are offline

**Comment by HeroCC** [comment]
Same here, please fix soon!

**Comment by jamierocks** [comment]
https://twitter.com/AquiferMc/status/799662545061613568

**Comment by HeroCC** [comment]
Any idea how long it will take? It's been a few days since the outage. Now the site is displaying a Database Error

**Comment by jamierocks** [comment]
https://forum.jamierocks.uk/d/11-temporary-waterfall-downloads

**Comment by Techcable** [comment]
It's fixed :wink:
