### ISSUE TITLE
Please fix your website.

### ISSUE THREAD

**Issue by pavog** [PaperMC/Waterfall#103]
On the website https://aquifermc.org/ most of the links in the waterfall dropdown point to the wrong locations where you can not download it.

Also on the about page it says "1.10, 1.9.x, and 1.8.x support". You should add 1.11 there too.

**Comment by jamierocks** [comment]
While we use the Aquifer resources, we are not the Aquifer team. I'll look into getting this resolved however.

**Comment by mibby** [comment]
@jamierocks Any update on the jenkins server being down? Or will all Waterfall builds stay on the PaperSpigot jenkins from now on?
