### ISSUE TITLE
[Proxy] Lost Connection problem.

### ISSUE THREAD

**Issue by craftrise** [PaperMC/Waterfall#105]
Random kicks players : [Proxy] Lost connection why?

This problem occurred when Waterfall was updated.

And 2.bug  : 

12:11:51 [WARNING] [/46.1.32.197:54413|AhmetR3D] -> UpstreamBridge - read timed out
12:11:51 [INFO] [AhmetR3D] disconnected with: ReadTimeoutException : null

Random kick players: Timed out.
Why?

 @jamierocks, @fuzzybot

**Comment by jamierocks** [comment]
We're going to need to know which commit it was you started seeing this and the full log.

**Comment by craftrise** [comment]
Plugins %100 Custom, There is no console error.  @jamierocks

It happened after WaterFall version changed.

**Comment by Janmm14** [comment]
@craftrise
Which version did you had before (woring fine) and which version do you have now (errouneous version)?
That was his question basically.
