### ISSUE TITLE
Where to download the latest dev build?

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PaperMC/Waterfall#107]
Okay, okay, this isn't a issue with Waterfall, but I think it should be reported here.

I couldn't find a working download for the latest dev build, the link in the project's README isn't working (https://aquifermc.org/job/Waterfall/ -> Route job/Waterfall/ could not be found.) and none of the links in AquiferMC works. (https://ci.getwaterfall.xyz/repository/download/Waterfall_Build/lastSuccessful/waterfall.jar -> Requested module (build configuration) does not exist: Waterfall_Build), (https://aquifermc.org/job/Waterfall/ -> same error as before), (https://github.com/WaterfallMC/Waterfall/releases -> not really broken, but there isn't any releases for Waterfall yet ;) )

Yes, I know how to compile Waterfall myself, but I thought I should report this issue.

**Comment by MrPowerGamerBR** [comment]
Okay, I found one dev build after looking for a little bit: https://ci.destroystokyo.com/job/Waterfall/

**Comment by jamierocks** [comment]
I'll update the readme, using Z750's ci was supposed to be temporary.
