### ISSUE TITLE
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents   

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Waterfall#112]
We had this error on initialHandler on latest WaterFall, looking for more clarification than a fix because the error seems to of gone but I kinda wanna know what caused it. It was caused by a guy who has the same IP but different port,

http://pastebin.com/Tq7Nhjfn

We run ViaVersion on the Proxy.
Lobby Version 1.10

I believe at the time mojang services were up and down, cannot really confirm but if this error can be a result of that then its probably the cause.

**Comment by kamcio96** [comment]
Client sends invalid packet;

**Comment by Cobwebster** [comment]
Is it harmless or could it be used maliciously?

**Comment by kamcio96** [comment]
quite harmless 😉
