### ISSUE TITLE
'NullPointerException: group' on connection to Waterfall.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#122]
Waterfall dev 101
Paper dev 1060 (Spigot 1.11.2)

I tried connecting to my server through Waterfall and got kicked with a NPE for 'group'. Tried connecting again and it connected me. I asked around and apparently a few other players and staff also experience this rarely. 

Client log of me connecting.
```
[00:58:51] [Client thread/INFO]: Connecting to <ip-censored>, 25565
[00:59:14] [Server Connector #1/ERROR]: Couldn't connect to server
java.lang.NullPointerException: group
	at io.netty.bootstrap.AbstractBootstrap.group(AbstractBootstrap.java:80) ~[netty-all-4.0.23.Final.jar:?]
	at er.a(SourceFile:275) ~[1.11.2.jar:?]
	at bgv$1.run(SourceFile:59) [1.11.2.jar:?]
```

Bungeecord log of me connecting.
```
00:59:12 [WARNING] [/IP:PORT|PLAYER] -> UpstreamBridge - NativeIoException: syscall:read(...)() failed: Connection reset by peer
00:59:12 [INFO] [player] disconnected with: §fNativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
```

![link](http://i.imgur.com/UdzptWR.png)

For what it's worth, both I and the person who initially reported the issue to me are grouped as an Admin. Could the scoreboard packet be too large?

**Comment by electronicboy** [comment]
Quick google search pulls up this, https://bugs.mojang.com/browse/MC-68381
In general, this is a clientside issue and only occurs when the client is unable to connect to the server for some reason, e.g. antivirus software blocking the connection.
