### ISSUE TITLE
5-7 second login times

### ISSUE THREAD

**Issue by EmotionalLove** [PaperMC/Waterfall#123]
I have Waterfall, my queue server, and my main server all hosted on the same machine. The queue server and the main server are hosted on 0.0.0.0 and Waterfall is open on the public IP address.

Upon connecting to the Waterfall server, it takes about 5-7 seconds to actually log onto the server, and it just hangs on "Logging in..."

I've tested Waterfall without any plugins, but the problem persists.

Please let me know if you need my configuration file.

**Comment by kamcio96** [comment]
Try disable plugins on spigot server. Logging screen depends on server response.

**Comment by EmotionalLove** [comment]
Tried that and still no-go, I should also mention if I run a normal MC server in online mode and connect to it without Waterfall, it only takes about half a second to log on.

**Comment by kamcio96** [comment]
plugins? both proxy and server

**Comment by EmotionalLove** [comment]
Yes, if I remove all plugins from the server and proxy, it still takes forever to log in :P

**Comment by kamcio96** [comment]
same machine? pls try on localhost

**Comment by EmotionalLove** [comment]
Yep, I've moved the backends to 127.0.0.1 on the dedicated and the problem still persists

Edit: http://i.imgur.com/uLwhOnt.gifv

Edit: with vanilla client: http://i.imgur.com/Yu0XSBD.gifv

Version: http://i.imgur.com/3IOsmU8.png

**Comment by Janmm14** [comment]
When you join the spigot server directly, is it an instant join?

**Comment by EmotionalLove** [comment]
Yes

**Comment by DominicDV** [comment]
referenced in https://github.com/PaperMC/Paper/issues/674

**Comment by sebastianbinder** [comment]
Same problem here. Logging in via Waterfall to PaperSpigot sometimes takes 10 seconds whereas using Bungeecord login is almost instant.
Also tried removing all my plugins from Waterfall: this does not change anything.

**Comment by MarkTwoFive** [comment]
@sebastianbinder in my case it's the exact opposite. Using Sponge servers and IP forwarding Waterfall performs 4 to 5 times faster logins than BungeCoord. 
@gtavbeastaya Maybe play around with the options a little to see if you come up with something.
Also try several different server modifications on the serving end to see if that makes a difference.

**Comment by MarkTwoFive** [comment]
@DominicDV in your referenced issue @aikar has an interesting explanation for why this may happen.

**Comment by sebastianbinder** [comment]
Did some further testing. For me this happens only on builds 103 upwards. Build 102 is fine. There has been a netty update between those two builds: https://github.com/SpigotMC/BungeeCord/commit/53cc3242e1d2786c34b2e138d233c4eeca8e3b1d
Can anyone tell me, if build 102 (https://ci.destroystokyo.com/job/Waterfall/102/) works for him and starting with build 103 (https://ci.destroystokyo.com/job/Waterfall/103/) these problems occur?

**Comment by sebastianbinder** [comment]
Guys, do you have any similar results like in my test above?

**Comment by Rushmead** [comment]
Yep can agree, i see a similar pattern @sebastianbinder

**Comment by sebastianbinder** [comment]
@WaterfallMC guys, do you have an idea why that new netty version works with Bungee but not with Waterfall?

**Comment by jamierocks** [comment]
I'll see about doing some profiling at some point - this should be priority for us

**Comment by sebastianbinder** [comment]
@jamierocks great! Hope there will be a solutions for us :)

**Comment by Techcable** [comment]
Implementing some sort of basic timings system may also help, and it's been on my TODO list for a while.

**Comment by sebastianbinder** [comment]
@Techcable good idea - that'll be nice for profiling. Unfortunately I need to switch back to BungeeCord as soon as 1.12 gets released as I cannot use any newer Waterfall version after that build I mentioned before.

**Comment by jamierocks** [comment]
I have a patch that *may* help things, I'll make a commit when I get back ;)

/edit: has anyone tested with sponge?/

**Comment by sebastianbinder** [comment]
Great - I can test the build as soon as it is available.

I'm not using sponge :/

**Comment by Black-Hole** [comment]
Will you be able to log DNS requests made by the server? I encountered this delay with misconfigured DNS servers.

**Comment by sebastianbinder** [comment]
Why should there be a difference between Bungeecord and Waterfall if this was a DNS problem?

**Comment by jamierocks** [comment]
We do use the async DNS resolver, but I can't see how that would be causing any issues.

**Comment by sebastianbinder** [comment]
@jamierocks what about your patch that "may help"?

**Comment by sebastianbinder** [comment]
Guys, any update on this issue?

**Comment by jamierocks** [comment]
ah crap, i completely forgot to get around to this after my business exam. im away at the moment, but i imagine a quickfix would be downgrade netty

**Comment by kamcio96** [comment]
Any update on this?

**Comment by sebastianbinder** [comment]
With https://github.com/SpigotMC/BungeeCord/commit/73a81ff2439864187f0b40a7273e375540cc6bdc / https://github.com/WaterfallMC/Waterfall/commit/3b5e511743de70f4e60215e9ad4b37366d98bc47 the issue seems to be fixed for me...

**Comment by jamierocks** [comment]
Yeah, I thought it may have been - another netty update. Could someone else confirm this fix, and I'll get this issue closed.

**Comment by Postremus** [comment]
Updated to master yesterday, have not noticed this problem yet.

2017-06-27 12:04 GMT+02:00 Jamie Mansfield <notifications@github.com>:

**Comment by jamierocks** [comment]
Good enough for me. Closing.

**Comment by Stualyttle** [comment]
I still have this problem, and i tried witout plugins.. on every server..
