### ISSUE TITLE
Upstream merge request

### ISSUE THREAD

**Issue by Rushmead** [PaperMC/Waterfall#125]
Recent changes updated the version of Netty meaning that some warnings users were experiencing are now gone.

Thanks
Rushmead

**Comment by jamierocks** [comment]
On it.

**Comment by jamierocks** [comment]
https://github.com/WaterfallMC/Waterfall/commit/8ff8de0fbdbf14d0b3e842780738f6d0b204d07a

**Comment by Rushmead** [comment]
Thanks!
