### ISSUE TITLE
error on join

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#126]
logs
https://gist.github.com/mat41997/50027e22b4d36a8ff288a14803b99571

I'm using windows 10 pro (64bit)
and java 8 121 (64bit)

start cmd
```
@ECHO OFF
color 02
java -Xmx1G -jar Waterfall-103.jar
```

config.yml
https://gist.github.com/mat41997/de9c4e55f57ae8bb09e4480945d23ea3

plugins list
![2017-03-14 14_06_40-plugins](https://cloud.githubusercontent.com/assets/5884000/23901958/9d8baeae-08bf-11e7-8b6e-30cdeaed9f77.png)

some others old topics
https://github.com/WaterfallMC/Travertine/issues/12
and
https://github.com/WaterfallMC/Waterfall/issues/83

**Comment by Janmm14** [comment]
This is a "notification error", everything works as usual.
Try updating waterfall/travertine if you're not using the latest version.
Report if the error is gone or not (and simply wait for a fix).

**Comment by ghost** [comment]
i have the Waterfall-103 
https://ci.destroystokyo.com/job/Waterfall/

it's the lates build

**Comment by jamierocks** [comment]
*That's not a bug*, rather a change we made to print an exception when a bytebuf other than a DirectByteBuf is being used. BungeeCord had a **far** less noticeable message, this justs ensures that the network administrator is aware.

**Comment by JavituRec** [comment]
I have same problem... Really What does that mean? Is it something that is misconfigured? Or something that is bad?

**Comment by jamierocks** [comment]
The change is introduced by [0027-Print-stack-trace-when-the-ByteBuf-is-not-direct.patch](https://github.com/WaterfallMC/Waterfall/blob/8ff8de0fbdbf14d0b3e842780738f6d0b204d07a/BungeeCord-Patches/0027-Print-stack-trace-when-the-ByteBuf-is-not-direct.patch).
The description of said patch is `The issue with ByteBufs not being direct should be fixed as of netty 4.1, and stacktraces provide valuable information.`

BungeeCord did a similar thing to us, in that they would provide the user with a message, however as previously mentioned it was far less noticeable than ours. `Netty is not using direct IO buffers.`

So, like I said -  **That's not a bug** In that Waterfall, will continue to run.
