### ISSUE TITLE
Could not connect to a default or fallback server

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#131]
Whenever I try doing /server MIN-1, I get a " Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!" error in my bungee log but I don't get connected to the server and in-game I get a "Could not connected to a default or fallback server." I've searched this up and I saw that other people just get this error but they get connected to the server they're trying to join. Any reason why this happens? Thanks

NOTE: I'm using Windows 10 for  this and build 106

**Comment by jamierocks** [comment]
The `Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!` "issue" is *not actually an issue*, rather a change in procedure from how BungeeCord previously handled things. (see #126)

The real issue here is probably down to the configuration of waterfall, or your servers.

**Comment by Techcable** [comment]
[Gist](gist.github.com) your full logs please
