### ISSUE TITLE
Users can't connect in this morning

### ISSUE THREAD

**Issue by JavituRec** [PaperMC/Waterfall#133]
Hello,

Since this morning all users join and automatic disconnect of my network, yesterday this did not happen. I have last update of waterfall,

thanks.

**Comment by MarkTwoFive** [comment]
1. General information (Versions, Builds, Mods [Server and client])
2. Logs? 
3. You may use gist.github.com for that
4. Did you update any of your software?

We need this information in order to help you in any way since we otherwise can't know whats causing your problem.
