### ISSUE TITLE
1.12 Waterfall not work

### ISSUE THREAD

**Issue by andris155** [PaperMC/Waterfall#137]
```
[01:51:24] [User Authenticator #1/INFO]: UUID of player andris155 is fc4c9617-452b-345d-b1fe-21544ad9c4d4
[01:51:24] [Server thread/INFO]: andris155[/xxxxxxxx:35757] logged in with entity id 3 at ([world]842.3382210360061, 8.0, -150.05212098390766)
[01:51:24] [Server thread/INFO]: andris155 lost connection: Internal Exception: java.io.IOException: Error while write(...): A kapcsolatot bontotta a távoli fél
[01:51:34] [User Authenticator #1/INFO]: UUID of player andris155 is fc4c9617-452b-345d-b1fe-21544ad9c4d4
[01:51:34] [Server thread/INFO]: andris155[/xxxxxxxx:35619] logged in with entity id 4 at ([world]842.3382210360061, 8.0, -150.05212098390766)
[01:51:34] [Server thread/INFO]: andris155 lost connection: Internal Exception: java.io.IOException: Error while write(...): Törött adatcsatorna
```

**Comment by ghost** [comment]
same issue, when replace with BC, works fine

**Comment by ghost** [comment]
<pre>
18:19:43 [INFO] [/62.182.234.189:59534] <-> InitialHandler has connected
18:19:45 [INFO] [HunterzCZ|/162.82.24.189:59534] <-> ServerConnector [minecraft2] has connected
18:19:46 [WARNING] Event ServerSwitchEvent(player=HunterzCZ) took 302,386,242ns to process!
18:19:47 [WARNING] [/162.82.24.189:59534|HunterzCZ] <-> DownstreamBridge <-> [minecraft2] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 77 Protocol GAME Direction
 net.md_5.bungee.protocol.Protocol$DirectionData@675ccd44
18:19:47 [INFO] [HunterzCZ] disconnected with: §cThe server you were previously on went down, you have been connected to a fallback server
18:19:47 [SEVERE] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
18:19:47 [SEVERE]       at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:54)
18:19:47 [SEVERE]       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
18:19:47 [SEVERE]       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18:19:47 [SEVERE]       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18:19:47 [SEVERE]       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
18:19:47 [SEVERE]       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
18:19:47 [SEVERE]       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
18:19:47 [SEVERE]       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
18:19:47 [SEVERE]       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
18:19:47 [SEVERE]       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
18:19:47 [SEVERE]       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
18:19:47 [SEVERE]       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
18:19:47 [SEVERE]       at java.lang.Thread.run(Thread.java:745)
18:19:47 [INFO] [/162.82.24.189:59534|HunterzCZ] <-> DownstreamBridge <-> [minecraft2] has disconnected
18:19:47 [INFO] [/162.82.24.189:59534|HunterzCZ] -> UpstreamBridge has disconnected

</pre>

**Comment by jamierocks** [comment]
I got a report about this the other day, including the fix by @Black-Hole, unfortunately I have (and remain) to be rather busy this week, having an exam tomorrow. I would be rather pleased if @Black-Hole could contribute a pr much like the previous update, else I will most-likely get to it tomorrow. Sorry for any inconvenience this causes ;)

**Comment by Black-Hole** [comment]
I've created https://github.com/WaterfallMC/Waterfall/pull/138 but I'm not sure if that fixes the issue with dropped connections.

**Comment by ghost** [comment]
Looks like it works now. Btw when run Waterfall, modules not updated, must dowload/copy by hand.

**Comment by jamierocks** [comment]
That's interesting... (I have fixed that all too many times :|) However, the modules haven't changed so there really is no need to update them by hand ;) I'll take a look at fixing it tomorrow. *adds to ever-growing list of things-for-tomorrow*.

**Comment by andris155** [comment]
Fixed. Thanks!
