### ISSUE TITLE
Vulnerability on packet flood

### ISSUE THREAD

**Issue by Sitmobedaf** [PaperMC/Waterfall#14]
http://mc.kanet.ru/proxy.log

**Comment by Janmm14** [comment]
Duplicate of #12

**Comment by Sitmobedaf** [comment]
This is not a duplicate. I do not want to draw your vnimatnie only error. The problem is that when a large packet BungeeCord the flood ceases responding to ping and new connections. Players who are already connected to a server problem is not felt. In this case also there is no load on the CPU.

Make a limiter on the number of packets per one IP. Exceeding this limit proxy server must ignore the following compound for a certain time.

I use Windows Server on my dedicated server, and I find it difficult implement protections for packet flood.

**Comment by Techcable** [comment]
as @Janmm14 said, this is a duplicate of #12
