### ISSUE TITLE
MC 1.12 Pre 6

### ISSUE THREAD

**Issue by Lmmb74** [PaperMC/Waterfall#141]
BungeeCord was upgraded some hours ago.

**Comment by jamierocks** [comment]
Yep I saw, on holiday so I haven't been at a machine yet to perform the update. Should be coming in the next couple hours.

**Comment by kamesuki** [comment]
Mind if i ask were you found the update? .w.

**Comment by Lmmb74** [comment]
https://github.com/SpigotMC/BungeeCord/commit/e26b93728c11bbeb73ae27e3184a7b8070f29247
That commit literally says Update to Minecraft 1.12-pre6 xD

**Comment by Lmmb74** [comment]
Neither Waterfall nor Travertine are building correctly since the commit before it.

**Comment by kamesuki** [comment]
Sorry I though you were talking about an update for waterfall ;~;

**Comment by Lmmb74** [comment]
Oh no, I opened this issue in order to get Waterfall updated :P

**Comment by Leymooo** [comment]
How about update to pre7?

**Comment by jamierocks** [comment]
Bungee haven't made the update. I'll be home in like 6-7 hours so I'll get it done then, regardless of whether bungee get it done or not.
