### ISSUE TITLE
Why was this method removed in 1.12? net.md_5.bungee.connection.LoginResult

### ISSUE THREAD

**Issue by DardBrinza** [PaperMC/Waterfall#144]
Latest build waterfall 1.12
I used this method and now I started to get this error:
java.lang.NoSuchMethodError: net.md_5.bungee.connection.LoginResult.<init>(Ljava/lang/String;[Lnet/md_5/bungee/connection/LoginResult$Property;)V

**Comment by Rushmead** [comment]
Could you tell me the exact version number? I've just downloaded the latest and it appears to be there.

**Comment by DardBrinza** [comment]
@Rushmead build 124 
https://ci.destroystokyo.com/job/Waterfall/

**Comment by Black-Hole** [comment]
You just have to add a parameter for the players name:
https://github.com/SpigotMC/BungeeCord/commit/5bc189fbb7e8ca19984544af78a083024404fb2a
