### ISSUE TITLE
elytra bug

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Waterfall#146]
when you switch servers while flying with an elytra, you are still stuck flying on the new server

**Comment by punkeel** [comment]
This bug is also present in vanilla bungeecord :)

**Comment by Janmm14** [comment]
@PunKeel According to md_5 its not reproducible.

**Comment by Foorack** [comment]
@Janmm14 This is definitely reproducible. Multiple people on the server I help is able to do this. As of the latest version of Spigot/Bungeecord this is still not fixed.

**Comment by Foorack** [comment]
Latest bungee, latest spigot, I have now learned how to do it as well.

This is how I am able to do it:
1. I go into the creative server and equip an elytra. **Make sure to disable creative flying** with either /fly or changing gamemode.
2. At a hight I start flying.
3. I switch server to another server (which is in adventure for everyone) with a command.
4. I can continue to fly until I press shift (which is when the server realizes I do not have an elytra).

Setting player.isGliding(false) at PlayerJoinEvent and PlayerSpawnEvent does not fix it. :frowning:

**Comment by Foorack** [comment]
After a lot of testing with creative modes and inventories this is the only way so far that I have been able to prevent it:

```
    @EventHandler
    public void onPlayerSpawnLocation(PlayerSpawnLocationEvent e) {
        // Fix elytra hack
        for(int i = 1; i <= 8; i++) {
            plugin.getServer().getScheduler().scheduleSyncDelayedTask(plugin, () -> e.getPlayer().setGliding(true), i * 5L);
            plugin.getServer().getScheduler().scheduleSyncDelayedTask(plugin, () -> e.getPlayer().setGliding(false), i * 5L + 1);
        }
    }
```

**Comment by MarkTwoFive** [comment]
@Foorack Hearing this
> I can continue to fly until I press shift (which is when the server realizes I do not have an elytra).

I'd suggest that's nothing Waterfall/BungeeCord should be preventing but the MC server shouldn't allow players who just connected to fly a nonexistent Elytra. If I would know how I'd try to force my client to connect to a vanilla server as "flying Elytra" and file a bug report to Mojang if that actually works.

**Comment by electronicboy** [comment]
They're not flying a nonexistent elytra, the issue here is that as they connect, more than likely the client apparently doesn't assume that they've stopped flying an elytra, Bungee should be ensuring that this information is handled properly and that the client is told that it's no longer flying.

**Comment by MarkTwoFive** [comment]
I'm still thinking this wouldn't be the only action necessary.

**Comment by Foorack** [comment]
I apologize for the bad audio in the beginning. This video shows proof that it is definitely reproducible on latest BungeeCord and latest Spigot with latest Minecraft. After a few tries I get it at **1:00**.

[https://www.youtube.com/watch?v=TraswOeSOqg](https://www.youtube.com/watch?v=TraswOeSOqg)

The trick is to holding W+SPACE **BEFORE** you get sent to the other server. It is difficult to time this right (as you can see from my attempts in the video). Other more skilled people on the server can replicate it with a much higher success rate. This is an especially big problem as this is possible to do in the minigame servers as well.

**Comment by PhanaticD** [comment]
should probably make a new issue with proof on bungee as it would be their fault not the waterfall fork

**Comment by Foorack** [comment]
@PhanaticD Good idea. In the video I was using BungeeCord, not Waterfall. I will report it on there instead.

**Comment by Foorack** [comment]
@PhanaticD This has now been fixed in the latest CraftBukkit release. I suggest closing this issue.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/1dced6a2c58fa1113fb2c123c8f066991fd73d8b

**Comment by PhanaticD** [comment]
okay dokay
