### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by friishon** [PaperMC/Waterfall#147]
Can i link 2 or more waterfall?
BungeeCord/waterfall 
  /              |              \
Survi       hub          waterfall
                                /       |           \
                           Sw   arena1  arena2
                           Hub

I made this in my mobile, this is possible?
[
![screenshot_20170627-232245](https://user-images.githubusercontent.com/19889173/27610712-ca2bfb58-5b8f-11e7-920d-24b5f9e0c550.png)

**Comment by jamierocks** [comment]
No.

**Comment by MarkTwoFive** [comment]
Why would you want to do that? Simply put everything behind one proxy.

**Comment by friishon** [comment]
big networks usging more than one bungeecord, and i need it.
frist, when you are making a minigamer on bungee mode, need 1 bungeecord, but one for this minigame, because, if you are going to put one arena, you need to stop en bungee and config, then start, if you do this on the principal bungee, your close all the network, so this is too bad, for prevent this things, i need more than 1 bungeecord
do you understand me?

**Comment by EmanYm** [comment]
You also asked this on Bungeecord and were told the same thing.
https://github.com/SpigotMC/BungeeCord/issues/2181

**Comment by MarkTwoFive** [comment]
@friishon Write your own/Install a BC plugin to do load balancing on sub servers.

**Comment by friishon** [comment]
i found redis, i will try to make a redis server for link bungeecord servers

**Comment by Black-Hole** [comment]
With RedisBungee you could run several BungeeCord servers in parallel, so you'll need some kind of load balancing at the network level (or DNS round robin).
Daisy-chaining BungeeCord still won't work with RedisBungee. You have to rethink what you're trying to accomplish and design your network properly.
But if you don't expect more than about 800 players in parallel a single BungeeCord server is your best option.

**Comment by jamierocks** [comment]
This functionality was explicitly prevented by Bungee in https://github.com/SpigotMC/BungeeCord/commit/504d3c0529e2014d5a1c469206db3bfd440829a7 and Waterfall in https://github.com/WaterfallMC/Waterfall/commit/12baa16bbf4d0d1e4ee9b863a9145e78ae8dd264. It was discussed in length in https://github.com/WaterfallMC/Waterfall/issues/76. It was also discussed in length on Bungee's issue tracker https://github.com/SpigotMC/BungeeCord/issues/1939.

**Comment by friishon** [comment]
I found this 
https://www.spigotmc.org/resources/redisbungee.13494/
And this
https://www.spigotmc.org/resources/redsync.22752/

**Comment by Black-Hole** [comment]
And the developers of those plugins will be happy about your negative review or refund request since they don't support daisy-chaining either. ;)

**Comment by friishon** [comment]
why? i have all server at home, i don't pay vps

**Comment by EmanYm** [comment]
It doesn't matter if they are hosted in your basement or on the moon.  If the programming in the mod does not allow you to do something, it will not allow something.
Like Jamie said, that behavior was prevented because it causes more problems than it's worth.

Why not just make a second world on your main hub and use that as the second hub.

**Comment by friishon** [comment]
this isn't for seccond hub, this is for makin all minigames on bungee mode, i need one bungeecord for each minigames, the reason:
i put all in one bungeecord server, when i making a new arena for skywars i have to close the bungeecord and then put the config, this can cause, all the network close
if i have multiple bungeecord server, i only close one, but the rest are online and player can play without problem, like big networks

**Comment by jamierocks** [comment]
@friishon 
> like big networks

You've said this twice now - do you actually have a source that 'big networks' daisy-chain Bungeecord servers, or is it just an assumption?

> i have to close the bungeecord and then put the config

To my shame, I don't have a great deal of knowledge of using the Bungeecord plugin API. However, I'm almost certain that such functionality exists as to allow for this to go about happening, in code that is.

---

Waterfall totally 100% agrees with Bungee on this one - Bungeecord/Waterfall servers should *not* be daisy-chained. We will not be reversing such change ourselves - it is a recipe for disaster, and we want to provide as safe a piece of software as we can.

---

With that, I am going to lock this conversation. There is nothing productive that can come of this being continued - I will end by quoting a previous comment made by myself.

---

#### *Repost of https://github.com/WaterfallMC/Waterfall/issues/147#issuecomment-311654592*
This functionality was explicitly prevented by Bungee in SpigotMC/BungeeCord@504d3c0 and Waterfall in 12baa16. It was discussed in length in #76. It was also discussed in length on Bungee's issue tracker SpigotMC/BungeeCord#1939.
