### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by sebastianbinder** [PaperMC/Waterfall#149]
Deployment to `repo.ellune.net` according to https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0001-POM-Changes.patch#L578 does not work anymore, as `repo.ellune.net` seems to be down. Is there any other repository that developers can use?

**Comment by jamierocks** [comment]
Iirc at some point I mentioned this to z750, but I cannot recall the outcome of such mention - I'll give it another ask tonight ;)

**Comment by sebastianbinder** [comment]
Any update on this?

**Comment by jamierocks** [comment]
Finally got around to getting it sorted. Probably only took about a year or so since it entered my todo list. Onto the next year long task :P 
https://github.com/WaterfallMC/Waterfall/commit/4c8715286f704a31a495e794b52a9c5af2834d00
