### ISSUE TITLE
Providing access to LoginResult on player login

### ISSUE THREAD

**Issue by phenomax** [PaperMC/Waterfall#154]
Hey!
Today I got a feature request/idea:
Currently BungeeCord does not grant access to the [LoginResult](https://github.com/SpigotMC/BungeeCord/blob/5bc189fbb7e8ca19984544af78a083024404fb2a/proxy/src/main/java/net/md_5/bungee/connection/LoginResult.java) containing the player's texture data on [LoginEvent](https://github.com/SpigotMC/BungeeCord/blob/ea6680281f3b20f4f1dcab44c51b4640c27f357c/api/src/main/java/net/md_5/bungee/api/event/LoginEvent.java).
But it would be very useful, if this data were accessible; for example to save the skull texture in the database.
Implementing this would be quite easy, because the InitialHandler provides direct access to [this object ](https://github.com/SpigotMC/BungeeCord/blob/daac8d85e20baed2ee0107ee637d0e82af8b2cd1/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L419) before calling the LoginEvent (see [here](https://github.com/SpigotMC/BungeeCord/blob/daac8d85e20baed2ee0107ee637d0e82af8b2cd1/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L532) and [here ](https://github.com/SpigotMC/BungeeCord/blob/daac8d85e20baed2ee0107ee637d0e82af8b2cd1/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L101)).
I'm looking forward to the implementation!
his object

**Comment by phenomax** [comment]
ping @jamierocks @fuzzybot @Techcable

**Comment by jamierocks** [comment]
Make a pr?

**Comment by jamierocks** [comment]
Resolved with https://github.com/WaterfallMC/Waterfall/commit/9f73d70f1507a27b0317837c8033880d61a42c9c.
