### ISSUE TITLE
Stuck in logging in when crashing in a sponge plugin created world

### ISSUE THREAD

**Issue by Sir-Will** [PaperMC/Waterfall#155]
If I crash my client in a world created by a sponge plugin I get stuck in logging it and the client throws the error that it can't find the dimension (error in sponge issue).
It is not possible to reproduce this bug without waterfall.

Apparently this is a waterfall bug and not sponge.
Sponge issue: https://github.com/SpongePowered/SpongeForge/issues/1507

**Comment by m31317015** [comment]
Several questions:
Did you try connecting directly to the server **when waterfall is active**?
Did you notice anything in the log on the Sponge side?
Did the player log recorded anything strange besides the "Dimension not found" error?

**Comment by Sir-Will** [comment]
You can't directly connect to the server using waterfall if you setup it correctly, so no.
The only errors are in the linked issue above as I said above.

**Comment by dualspiral** [comment]
I'll PR a fix in, the problem is that some FORGE packets are getting dropped when the handshake has completed.
