### ISSUE TITLE
1.12.1 waterfall server instant disconnect

### ISSUE THREAD

**Issue by mechoriet** [PaperMC/Waterfall#164]
got this message when joining a spigot 1.12.1 server thru waterfall
![image](https://user-images.githubusercontent.com/4313219/28984986-c020c384-7960-11e7-8a2c-dc83e4bf5beb.png)

bungeecord console:
![image](https://user-images.githubusercontent.com/4313219/28985014-e2bd5ea2-7960-11e7-98fc-4db4320a8be9.png)

spigot log:
![image](https://user-images.githubusercontent.com/4313219/28985032-fb121164-7960-11e7-82d2-54030a6aee4f.png)

**Comment by MarkTwoFive** [comment]
I guess your last joined server is also set up as the default server?

**Comment by mechoriet** [comment]
yes its the default server
test situation(waterfall + 1x spigot 1.12.1)

**Comment by MarkTwoFive** [comment]
Then is the default server correctly set up? I guess Bungee simply can't reach it

**Comment by mechoriet** [comment]
tried the same setup, the same config with plain bungeecord and it works fine
I can connect normally

**Comment by jordanwilliams1** [comment]
So.. Waterfall doesn't work with 1.12.1 spigot/paper servers right now?

**Comment by MarkTwoFive** [comment]
Just to be sure: This does also happen with BungeeCord?

**Comment by mechoriet** [comment]
Normal bungeecord is fine
waterfall is not, dunno why it does it

**Comment by jordanwilliams1** [comment]
So? Is this getting fixed or what

**Comment by Postremus** [comment]
Tested this with a paper server and Waterfall `git:Waterfall-Bootstrap:1.12-SNAPSHOT:c59f45f:136`. Works fine for me locally. 

What plugins are you using?
Can you reproduce this error without any plugins on paper and waterfall?
Any additional errors in the logs?

**Comment by jamierocks** [comment]
Perhaps if you got some full logs from people getting these errors, we might be able to assist.

**Comment by jordanwilliams1** [comment]
tbh. I haven't even checked if this is happening for me. I Just saw this open on GitHub and just won't update till someone confirms if this is a bug or not, lol

**Comment by krusic22** [comment]
What hosting are you using for Spigot/Paper? Some hosting providers prevent Bungee connections to their servers...

**Comment by mechoriet** [comment]
Own dedicateds

Op 12 aug. 2017 3:26 p.m. schreef "Kristjan Krušič" <
notifications@github.com>:

What hosting are you using for Spigot/Paper? Some hosting providers prevent
Bungee connections to their servers...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/WaterfallMC/Waterfall/issues/164#issuecomment-321980956>,
or mute the thread

**Comment by RaynLegends** [comment]
Are you using AAC? I think that's what causes this issue, but I'm not sure. I've the latest build of WaterFall with 1.8.8 spigot servers (using ViaVersion).

**Comment by Foorack** [comment]
I have been unable in replicating this. Any steps of procedure to replicate? Or can this be closed?
