### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Behoston** [PaperMC/Waterfall#165]
https://paste.ofcode.org/hXkHb5nr4JGhqLKdV7cGsG
no more info... 
I have this server from one month and this is first crash.

**Comment by jamierocks** [comment]
We're not Paper ;)

**Comment by Behoston** [comment]
oh, sorry

**Comment by jamierocks** [comment]
No problem at all -> https://github.com/PaperMC/Paper/issues/new is what you're after.
