### ISSUE TITLE
MultiLobby breaks on Waterfall

### ISSUE THREAD

**Issue by Cobwebster** [PaperMC/Waterfall#168]
Plugin : https://www.spigotmc.org/resources/multilobby.2446/

Issue : Basically when using MultiLobby on waterfall I guess waterfall handles disconnects differently than bungee because when you close minecraft on a 1.12 gamemode it'll spam bungee with about 50-100k lines of the player joining/leaving, basically only happens when you fully disconnect on a 1.12 server, obviously the fix should be from the multilobby dev but he said he has no interest in adding waterfall support.

I wonder if its intentional to handle disconnects differently on 1.12 on waterfall and not bungee? If its a performance improvement thats fine but i thought i'd report.

Just to make it clear,
obviously ideally the plugin dev would fix it but he isn't gonna, us not having multiple lobbies isn't a solution so we don't wanna go back on bungee instead of waterfall. I can provide a network setup and you can test yourself.

No problem if you have no interest in addressing it, its obviously down to the plugin dev but wanted to clarify first that it wasn't a bug/oversight on waterfall that disconnects handle differently. Kinda a wild card to see if its a easy fix on your end.

Thanks, I can provide more info on the bug if need be.

**Comment by jamierocks** [comment]
Yeah, this sounds like it is an issue on our end. Unfortunately MultiLobby is a paid resource, so I won't be able to take a look into its source to try and establish what it is doing to break Waterfall. Did you get any stacktraces I could look at perhaps?

**Comment by Cobwebster** [comment]
There are 0 errors, it'll literally just spam join/leave in bungee about 100k times, fills all logs within seconds. I can probably arrange a mediafire link of my localhost network which has the setup, I'm sure the dev wouldn't mind me sending it if it helped waterfall fix the issue and it was sent over private pm.

If you want I can ask him and see what he says, it'll be very hard to fix without it.

**Comment by jamierocks** [comment]
I'll give the author a pm, see where that leads. I'll also take a look over our patches, try and see if anything sticks out.

**Comment by Cobwebster** [comment]
He said I can send you my network setup with multilobby, could you pm me on spigot?#

https://www.spigotmc.org/members/cobwebster.64009/

I can send you the bungee network setup

**Comment by Cobwebster** [comment]
Were you able to replicate it?

**Comment by jamierocks** [comment]
No, I'm afraid I wasn't. I'll give it another go, later on today. I've been really busy sorry :(

**Comment by Cobwebster** [comment]
Bump :)

**Comment by jamierocks** [comment]
@kashike if I send you the files, could you give this a test?

**Comment by Cobwebster** [comment]
Bump :)

**Comment by Fluxty** [comment]
Similar to https://github.com/WaterfallMC/Waterfall/issues/69 - Please reference the responses. We're having a similar issue with hubmagic.
