### ISSUE TITLE
ComponentBuilder not working correctly

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#173]
When the Componentbuilder gets another Componentbuilder to use it for example a prefix that i need everytime that happens:

in older builds: Prefix | You got muted!
now: Prefix | You Prefix | got Prefix | muted! Prefix |

I only updated my bungee server so it is not my code because it was working before

**Comment by jamierocks** [comment]
Hmm, perhaps I did a dodgy merge of https://github.com/SpigotMC/BungeeCord/commit/fd675022c0dd2d8597c2f32a89d81545d99cfa9d
