### ISSUE TITLE
1.12.2 not supported

### ISSUE THREAD

**Issue by SanderGielisse** [PaperMC/Waterfall#179]
1.12.2 shows "Outdated server" on connect and does not show the version in the server list.

**Comment by jamierocks** [comment]
My guess'd be that the server doesn't accept 1.12.2 clients.

**Comment by SanderGielisse** [comment]
@jamierocks The ping in the server list also shows a red cross, which should be fully handled by Waterfall itself.

**Comment by MarkTwoFive** [comment]
This is handled by BungeeCord not Waterfall though

**Comment by jamierocks** [comment]
If the server doesn't accept 1.12.2 clients, bungee nor waterfall is going to help you.
Unless you can provide some more info, I'm closing this.
