### ISSUE TITLE
1.7.x

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Waterfall#18]
Where missing support this version?

**Comment by FunnyCraft** [comment]
missing*

**Comment by kamcio96** [comment]
http://minecraft.gamepedia.com/1.7.2

Because first 1.7 version was released on `October 25, 2013` and its just outdated.

**Comment by FunnyCraft** [comment]
I have a lot of players playing with a 1.7. *, Return the support please.

**Comment by kamcio96** [comment]
So just update server, they will update client.

**Comment by minecrafter** [comment]
We have made a decision to maintain 1.7 support in a separate fork.

**Comment by FunnyCraft** [comment]
When can download a version with support?

**Comment by FunnyCraft** [comment]
Give link for download, when you back support 1.7?

I really looking forward.

**Comment by Janmm14** [comment]
Go with an old version. Currwntly there is no 1.7 version available.

**Comment by FunnyCraft** [comment]
229 build was supporting 1.7 version, and everything was fine. When we fixed the bug, the support was gone.

**Comment by FunnyCraft** [comment]
where can i download  separate fork?

**Comment by Janmm14** [comment]
@FunnyCraft As I already mentioned:

> Currently there is no 1.7 version available.

Except if you want to use old versions.

**Comment by FunnyCraft** [comment]
there are 3 file class you pick up and ready.

**Comment by kamcio96** [comment]
Yeaaa
There are [1.10](http://mojang.com/2016/06/minecraft-110-an-update-of-fire-and-ice/). Just update and ready

**Comment by FunnyCraft** [comment]
why not support and 1.7 version?

**Comment by kamcio96** [comment]
I told you "Because first 1.7 version was released on October 25, 2013 and its just outdated."

**Comment by kamcio96** [comment]
If you really want 1.7: http://ci.md-5.net/job/BungeeCord/1119/

**Comment by FunnyCraft** [comment]
I want support 1.7 - 1.8 - 1.9 version.

**Comment by kamcio96** [comment]
And 1.10?

**Comment by FunnyCraft** [comment]
yes, it would be a mega cool.
