### ISSUE TITLE
Forced host chat not working

### ISSUE THREAD

**Issue by kaal-1** [PaperMC/Waterfall#180]
I have the following setup:
Vanilla hub server
1.10.2 SpongeForge server
Waterfall

I have the 1.10 server set as a forced host, but whenever I try to connect to it directly, the chat simply doesn't work.. Commands don't work, chat messages don't work.
If I enter the hub server and then /server sponge, it does.

Any idea of what could be the issue?

**Comment by kamcio96** [comment]
You can't join directly to server. Never.

**Comment by MarkTwoFive** [comment]
@kamcio96 as he mentioned forced hosts I guess he doesn't actually mean connecting directly but connecting directly over bungee ignoring the last location.

@kaal-1 make sure you've fully enabled the BungeCoord module in Sponge.

**Comment by kaal-1** [comment]
I did. I enabled the module and ip forwarding

**Comment by MarkTwoFive** [comment]
And I assume you also have ipf enabled in the Waterfall config.  

Could you quickly list the plugins installed on your Waterfall and your Sponge server?
