### ISSUE TITLE
Error dispatching even for ForceResourcePacks plugin

### ISSUE THREAD

**Issue by smmmadden** [PaperMC/Waterfall#184]
Using the latest Waterfall (v152), Spigot 1.12.2 (built today) and ForceResourcePacks plugin on the Waterfall/bungeecord server plugins folder, the plugin loads fine.  However, teleporting to different servers in the network results in exceptions with the event.
https://pastebin.com/gDa6Hfs6

This works fine under BungeeCord Server build 1273.

**Comment by Black-Hole** [comment]
That is an internal exception of that plugin. So you have to ask the author of that plugin to fix it.
Changes in Waterfall might cause some expectations of that plugin to fail. But changing that expectations should be easy for the plugin author.

**Comment by smmmadden** [comment]
sounds great, thanks for the quick reply :-)

**Comment by smmmadden** [comment]
reported to the plugin owner and he's fixed it in the latest build.  Thanks!
