### ISSUE TITLE
Console output has issues with new lines/spam

### ISSUE THREAD

**Issue by mikroskeem** [PaperMC/Waterfall#188]
This is only happening when plugin spits out 3-4 lines in a row. At first, line ends up being inserted after input prompt and if that happens frequently enough, Log4j2 spits out an error.

Log snippet & stack trace: https://paste.wut.ee/ezerajafor.md

Waterfall version: `This server is running Waterfall version git:Waterfall-Bootstrap:1.12-SNAPSHOT:261741a:155 by md_5`

**Comment by mikroskeem** [comment]
If that helps, I am using SLF4J logger (as plugin is multiplatform and uses SLF4J widely) and getting it using `LoggerFactory.getLogger(...)`

**Comment by jamierocks** [comment]
Ref @Minecrell

**Comment by stephan-gh** [comment]
I can't reproduce this. It's likely some kind of race condition that only happens if a message is logged while the console reader is changing its state (e.g. it's done reading or it starts reading again).

Do you have a reliable way to reproduce this?

**Comment by k-jiang** [comment]
Same issue here. To reproduce it, you just need to spam command in the console frequently then you will see the exception.
In my case I have [RedisBungee](https://github.com/phenomax/RedisBungee) installed with Waterfall [build 160](https://ci.destroystokyo.com/job/Waterfall/160/). The command I have tested is RedisBungee's modified `glist`.
I'm guessing it doesn't have to be the commands from RedisBungee, any plugins will do so, even the basic commands from BungeeCord.
If you need any help on testing please let me know. I'm here to help. @Minecrell

**Comment by Black-Hole** [comment]
Seems like https://github.com/jline/jline3/issues/183
