### ISSUE TITLE
which site is accurate for this project?

### ISSUE THREAD

**Issue by smmmadden** [PaperMC/Waterfall#195]
For the last few months I've been using this url to get the latest waterfall build and for the last few days it has been down with no way to notify anyone.  So I did a search and found this project and see it appears to be the same thing but different build #'s.  https://ci.aquifermc.org/job/Waterfall/

Which is current and correct to use?
Is the other site no longer going to be available?

Thanks,
Steve

**Comment by mikroskeem** [comment]
https://ci.destroystokyo.com/job/Waterfall/
