### ISSUE TITLE
Ultimate friends errror

### ISSUE THREAD

**Issue by Malachiel87** [PaperMC/Waterfall#204]
Waterfall build: 168
I i want report Ultimate friends plugin that sometimes on /friends load it trow the error on waterfall ad cause database friends not to be loaded. (link https://www.spigotmc.org/resources/ultimate-friends.3964/)
The author of plugin @M1nef4n say that is waterfall fault
https://hastebin.com/miregenapi.pl

**Comment by electronicboy** [comment]
an NPE inside of the plugin itself is generally a sign that they're not handling null safety properly. But, even if the issue is on this side, there isn't much we can do when we don't even know what the plugin is doing to cause that).

**Comment by holubv** [comment]
Basically `player.getServer()` returns `null` even if the player is connected. I have never had this issue with BungeeCord.

https://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/connection/ProxiedPlayer.html#getServer--

`null` value is not mentioned in javadocs

**Comment by Black-Hole** [comment]
It seems it's called by a delayed task. At that point in time the player could be disconnected already, so getServer() will return null. Waterfall might disconnect the player a little faster, without up to 500 ms delay.

JavaDoc in BungeeCord rarely makes statements about null values.

**Comment by electronicboy** [comment]
That getter can return null in some cases, while the javadocs might not state that it, in fact, can, there are certain states, e.g. during connection, as well as various places where I can see the potential for this field to be null.

As above, bungees javadocs suck at noting methods which might return null, especially as they're using lombok which relies on the javadocs for the field itself, as opposed to being specifically commented getters/setters.
