### ISSUE TITLE
Waterfall Memory Leak

### ISSUE THREAD

**Issue by Fluxty** [PaperMC/Waterfall#207]
Waterfall does not always completely let go of player objects, memory fills up and the server begins to lag. Our servers cannot remain stable with their current traffic on Waterfall with any kind of hub balancing plugin, we're using hubmagic by Tux/theminecoder right now (and RedisBungee, but this issue was here without RedisBungee). Running /find or /glist shows the players as connected to a lobby when they are not online.

This is not an issue in Bungeecord, but we need Waterfall for tons of other reasons.

Please re-reference https://github.com/WaterfallMC/Waterfall/issues/69 - it should have more than enough information. Please help us solve this problem. It's been plaguing us for over a year now. We're looking into forking but our workload is very high.

**Comment by MarkTwoFive** [comment]
Does this also happen with no balancing plugins installed?

**Comment by Fluxty** [comment]
@MarkL4YG I don't think so, but we can't really comprehensively test because we need the balancing for both incoming players and for fallbacks during our daily gamemode reboots. Also worth nothing that reconnecting players are often met with a "you are already connected to this network!" error that lasts a couple minutes after disconnecting.

**Comment by MarkTwoFive** [comment]
In that case you should really take a look into what the plugins are doing that may cause this.
There're tools to find such causes.

**Comment by Fluxty** [comment]
Considering Tux contributes/has contributed to both HubMagic and Waterfall, I thought the interaction might be important to both. There's also a similar report of this with multilobby here: https://github.com/WaterfallMC/Waterfall/issues/168 and a few other open issues regarding "ghost players" in waterfall only.

I can confirm the issue is not present when using Bungeecord instead of Waterfall

**Comment by jamierocks** [comment]
The fault does seem to be with Waterfall here - I just can't imagine where :S

**Comment by Fluxty** [comment]
I cannot see either. When the player disconnects, hubmagic for some reason is still trying to assign them to a lobby and Waterfall believes they're in said lobby instead of being offline? This doesn't affect player count though.

**Comment by Fluxty** [comment]
Small update, when a player is kicked from the network they are disconnected normally. This is perhaps because the kick doesn't pass through hubmagic.

Update 2: We have fixed the issue. When a player disconnects from the network, Waterfall fires PlayerKickEvent, resulting in hubmagic assigning a player to a lobby even after they are offline, and Waterfall retains the object. Adding "Lost connection to server" to the hubmagic kick reason blacklist allows hubmagic to ignore the disconnect event and bandaid's the resulting memory leak!
