### ISSUE TITLE
Allow advancement functions to be ran with elevated permissions

### ISSUE THREAD

**Issue by ShelLuser** [PaperMC/Waterfall#208]
This is a feature suggestion based on my question on the Aquifer forum as seen [here](https://aquifermc.org/threads/does-paper-allow-for-advancements-to-use-functions.5247/).

In the current situation any functions which get triggered from an advancement are ran from the users context, on a regular server this means it runs without op status. I'm wondering if it is possible to somehow allow for this behavior to be overridden.

Basically for 2 main reasons. First and foremost: this behavior would be equal to that of the vanilla server, and in my opinion also makes more sense. After all: the server triggers the advancement so why would it need to be run from within the users context (I'm aware of security concerns)? Another thing which irks me a little bit about the current behavior is that whenever a user triggers a commandblock then whatever gets executed will be run within the server context (elevated). So why would an advancement be any different?

Second: this would open up a lot of options for server owners (and map designers I guess) to provide users with a more customized experience. Think about rewarding them with customized items, but also about performing certain tasks which would otherwise be impossible (which could be interesting for map makers).

Thanks in advance for your attention.

**Comment by mikroskeem** [comment]
That's wrong issue tracker, I think you are looking for [Paper's](https://github.com/PaperMC/Paper/issues)

**Comment by electronicboy** [comment]
As above, wrong issue tracker
