### ISSUE TITLE
[SUGGESTION] Extract the messages.properties to edit it outside the jar

### ISSUE THREAD

**Issue by Alexre** [PaperMC/Waterfall#209]
Hi! If you extract the messages.properties making it configurable outside the jar it would save many people a lot of time. Thanks :)

**Comment by LuminousLoreBloom** [comment]
Pretty sure it already lets you do that. You might just have to extract the file into base directory yourself though.

**Comment by MarkTwoFive** [comment]
Yes it does.
I believe there's even a section on it in the BungeeCord wikis.
