### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by camdenorrb** [PaperMC/Waterfall#21]
Ello I can't seem to figure out how to build Waterfall. Since I am using centos in order utilize Openssl on Centos I have to build it on my centos system.

**Comment by kamcio96** [comment]
First you have to install git and maven 
git: `apt-get install git` or something similar 
maven: download from site, unpack

``` bash
git clone http://github.com/WaterfallMC/Waterfall.git
cd Waterfall 
git submodule update --init 
./applyPatches.sh
cd Waterfall-Proxy 
path/to/maven/mvn.sh install 
```

And you have jar in Waterfall/Waterfall-Proxy/target :wink:

**Comment by camdenorrb** [comment]
This should be added to the read me <3
