### ISSUE TITLE
How can I use Waterfall with Cauldron?

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#210]
I want to set up a network with both spigot and cauldron servers, how can i do that?

**Comment by electronicboy** [comment]
You probably want Travertine, as opposed to waterfall, in order to support a 1.7.10 server; beyond that, it's configured the exact same as a spigot server is, albeit, if you're not using the spigot fork, you won't have proper bungee support (IP and UUID forwarding).

**Comment by ghost** [comment]
My spigot servers are all 1.8 and cauldron is 1.7.10 (as all the mods i need in my server) when using bungeecord, i get this error: [m>[2K11:54:16 [WARNING] [FlyrkyGameplays] <-> ServerConnector [dbw] - overflow in packet detected! Cannot receive byte array longer than 169 (got 6178 bytes)

I was asking if i use waterfall, is possible or not to use spigot 1.8 linked with 1.7.10 cauldron

**Comment by jamierocks** [comment]
Waterfall does not support 1.7.10. You'll want to use Travertine, for Waterfall with 1.7 support.

**Comment by ghost** [comment]
Does Travertine support 1.8 as well?

**Comment by jamierocks** [comment]
Travertine supports all the versions as Waterfall does, with additional support for 1.7.10.

**Comment by ghost** [comment]
Ok, thank you so much!

**Comment by ghost** [comment]
One question, how do I configure Travertine? Is it the same configuration process as Waterfall?

**Comment by electronicboy** [comment]
exact same as waterfall, exact same as bungee

**Comment by ghost** [comment]
Ok, now I don't get that error, instead, when I jump in the portal to the Dragon Block server (cauldron) I just get disconnected, it just says "Dissconnected from server" on my screen, no errors on console. Only in the cauldron console, it appears this: >[12:50:48 INFO]: FlyrkyGameplays lost connection: Internal Exception: java.io.IOException: Broken pipe

**Comment by jamierocks** [comment]
Okay, if you think that is due to a fault with Travertine - could you please move this over to the appropriate issue tracker.

**Comment by ghost** [comment]
https://github.com/WaterfallMC/Travertine/issues/63
