### ISSUE TITLE
Netty DNS Resolver causes long (6-10 second) logging in / connection screen times.

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#211]
```use_netty_dns_resolver: true```

With the netty dns resolver enabled, login to the server through Waterfall causes extremely long logging in connection screen times. Averaging about 6-10 seconds in length - 1.12.2 client connecting to a 1.12.2 server. Turning the setting false, logging in connection screen only takes about 1-2 seconds. Not necessarily instant logins, but better than with the setting enabled.

Tested with no BungeeCord plugins, as well as with BungeeCord instead of Waterfall.

**Comment by khlfkk** [comment]
same here

**Comment by electronicboy** [comment]
Routine "going through a few issues when I have the time", ultimately, stuff like this is entirely down to your environment, while in most setups, that option is going to help with performance, there are cases where it might not, shamefully, your environment appears to be one where it doesn't help and should be disabled.

**Comment by mibby** [comment]
@electronicboy Is there any way to actually benchmark between using and not using the setting or figure out as to why it slows down connection logins with my environment?
