### ISSUE TITLE
Railcraft crash

### ISSUE THREAD

**Issue by LasmGratel** [PaperMC/Waterfall#216]
Waterfall doesn't support custom meta entity which is defined in modding server.

For example, railcraft used custom entity meta id '15' and it would make Waterfall server crash.

![7dfb421e6dc922f1](https://user-images.githubusercontent.com/6669365/37344562-a6a8a022-2705-11e8-8e37-7a7603fe0a44.png)

This issue is duplicated in https://github.com/HellFirePvP/AstralSorcery/issues/547
https://github.com/SpigotMC/BungeeCord/issues/2349

But they are not getting solved by the authors.

I am looking forward to the official supporting of Waterfall.

**Comment by n0099** [comment]
more info: This issue could reproduce when a player placing railcraft locomotive or some type of railcraft carts (like forestry beecart), and all players within that locomotive's visual range chunks will be kicked to the fallback server or just kick out of the server by proxy, then these players are unable to rejoin the server (players get kicked again and again) until the locomotive be killed by commands.

Several mods using custom entity meta type 15 for some particular purpose too.

**Comment by Black-Hole** [comment]
You might want to fork this project and implement those metadata for the mods you're using. Entity meta types above 14 could be anything.

**Comment by MarkTwoFive** [comment]
Why would forge allow breaking the protocol though... 🤔 seems useless if that breaks compatibility with proxies. Are you sure there's no easy way to allow this in BungeeCord/Waterfall?  
I don't know the protocols internals but this really sounds like not being that big of a deal...

**Comment by Black-Hole** [comment]
Entity meta data don't have a length field. The length is determined by the type. So where does type 15 stops:
http://wiki.vg/Entity_metadata#Entity_Metadata_Format

**Comment by electronicboy** [comment]
Basically, bungeecord is required to do some modification to entity data sent to the client in order to support teleporting across servers properly, they need to rewrite some information which is sent to the client; Now, in order to do this (because of the usage of varints), they need to rewrite all of the metadata on the entity, which we can't do for an unknown metadata type, because we have no idea how to process this.

If this type is defined by forge, we could probably support it, but for stuff added directly by mods, you're out of luck.

**Comment by MarkTwoFive** [comment]
@Black-Hole Ah okay now I see what the issue with that is.... Thanks.  
But I still feel like such a thing should not happen ... not saying there's someone at fault here but not being allowed to use any of the remaining possible IDs sounds just wrong.

**Comment by electronicboy** [comment]
It's not the usage of IDs that's the issue, it's a, how do you expect a
system to manipulate data which it doesn't know the format of. This
mechanism is a core part of what allows cross server teleportation to occur
without having invalid/corrupt entities due to transporting across servers,
and due to how the protocol works, requires the full packet contents to be
rewritten, which we cannot do properly if we don't know the format of the
data we're working with.

**Comment by MarkTwoFive** [comment]
@electronicboy Yeah I get that. But this still sounds like being unfriendly to modifications. I personally consider the need to know all entity meta types a protocol flaw. Anyways - as I said I don't want to blame or anything. I'm just giving my opinion on this issue.

**Comment by LasmGratel** [comment]
@electronicboy Thus I have to fork Railcraft and get this entity normalized and being friendly with Waterfall? Instead, I also have no idea with CovertJaguar's thoughts...

**Comment by MarkTwoFive** [comment]
Nah I think they ment you'd need to fork Waterfall/Bungee and add this entity-meta-type to the mappings.

**Comment by jamierocks** [comment]
Indeed that is what @electronicboy meant. Bungeecord has to process entity meta data to ensure that players can teleport across servers without buggering up data. To process the meta data, Bungeecord (and intrinsically Waterfall) needs to know how to read it. Sadly this means that any meta data introduced by mods will not be compatible with Bungeecord/Waterfall - without modifications.

**Comment by LuminousLoreBloom** [comment]
Pending BungeeCord issue 2361 has speculation about it if entity rewriting can be removed (see md-5 referenced commit)

**Comment by LasmGratel** [comment]
I just comment the `throw new IllegalArgumentException( "Unknown meta type " + type );` code part in EntityMap and `0x3C` case in `rewriteClientbound` of EntityMap_1_12(_1)

Compiled binaries available below:

[entitymap.zip](https://github.com/WaterfallMC/Waterfall/files/1970727/entitymap.zip)

Repack them into `net.md_5.bungee.entitymap` package in BungeeCord or Waterfall.

**Comment by LasmGratel** [comment]
This issue still relevant.

**Comment by electronicboy** [comment]
The fix here is ultimately going to be to disable entity remapping entirely and rely upon the clients logic of disposing of entities in the world upon switching world, which would require a fair chunk of testing on... If somebody wants to put in the work for this and put it behind a configurable option, I'd be more than happy to review it, but given 1.13s release and forge reworking all of their tooling, I personally cannot personally justify the work to put into this with proper testing.

**Comment by electronicboy** [comment]
Closing in favor of #136
