### ISSUE TITLE
Item frame rotation is broken

### ISSUE THREAD

**Issue by mikroskeem** [PaperMC/Waterfall#217]
On Paper server without Waterfall or BungeeCord (how item rotations should be!):
![](https://0x0.st/sacH.png)

On Paper server with Waterfall:
![](https://0x0.st/sac-.png)

On Paper server with BungeeCord:
![](https://0x0.st/sac8.png)

No plugins are used on proxy or server

**Comment by mikroskeem** [comment]
Everything was running & tested on latest version on the day the issue was submitted
- Paper `#1349`
- Waterfall `#170`
- BungeeCord `#1303`

**Comment by jamierocks** [comment]
Well that is interesting :s

**Comment by mikroskeem** [comment]
Extra information: this is not reproducible 100%, this seems to happen only on 8 out of 10 connections. Some players have correct rotation, but on reconnection item frames are broken again etc.

**Comment by mikroskeem** [comment]
(putting this here as well in case someone does not read IRC)

https://paste.wut.ee/umilefakiy.diff I used this patch to get this information and I rotated item on item frame

![](https://0x0.st/sMum.png)

>Some players have correct rotation, but on reconnection item frames are broken again etc.

^ that happens because Entity ID's last number (or whatever is the logic behind vanilla client's rendering) seems to be between 0-7, thus item frames work by pure luck for them.

In the picture, last rotation value should be 0 (but ends with 7 so item is rotated to North-West)

**Comment by mikroskeem** [comment]
This seems to be caused by a first server (in priority list or w.e what makes player connect first to given server) not sending chunks and that causes internal issues with BungeeCord.

No idea if it is worth looking into this issue more deeply or not however.
