### ISSUE TITLE
Is an issue about Netty 4.1.23.Final?

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Waterfall#221]
Is an issue about Netty? Endless loop which will cause the issue to be not able to cleanup in Netty 4.1.23.Final?
Thanks for support.

https://paste.md-5.net/nuxokabixu.avrasm

**Comment by Janmm14** [comment]
This looks more like the mysterious empty packet problem.

**Comment by khlfkk** [comment]
confirmed, if you are using waterfall #174 and using RedisBungee then the player count will be cleared randomly. Right now i should switch to use Bungeecord build since they have good support to Waterfall
.

**Comment by electronicboy** [comment]
Closing, not a netty issue, something is sending bad data to the proxy.
