### ISSUE TITLE
Strange BungeeCord issues

### ISSUE THREAD

**Issue by Xayanix** [PaperMC/Waterfall#223]
Hi, 

i got problem since updated from 1.12.1 -> 1.12.2. My BungeeCord seems to very randomly stop receiving/sending packets (looks like netty crash or something). It happens ONLY after server switch event (on proxy join too). Console is error free.

Video how it looks like:
https://www.youtube.com/watch?v=edBZYxxFLcQ

Plugins on BungeeCord:
- BungeeTablistPlus
- RedisBungee

Does anyone have idea how to debug it?

**Comment by MarkTwoFive** [comment]
Looks like a classic dropped connection to me to be honest. 
What do the server and client logs tell? There has to be a mention of at least a disconnect.

**Comment by Xayanix** [comment]
Just timed out on bungeecord and spigot. It happe s after server switch events, never while playing.

**Comment by Xayanix** [comment]
It was issue on my firewall.
