### ISSUE TITLE
Pendig server? PreLoginEvent?

### ISSUE THREAD

**Issue by download042** [PaperMC/Waterfall#225]
Hi!

I'm not sure that is with Waterfall, but i got this message many times, in the console:

[Server] WARN No client connected for pending server!

[Server] WARN Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[(The player's IP) .dynamic.isp.telekom.rs/(The player's IP again with port):24830|(The player's name)] <-> InitialHandler) took 329,555,236ns to process!

**Comment by mikroskeem** [comment]
Plugins?

**Comment by download042** [comment]
![image](https://user-images.githubusercontent.com/13710574/39676039-c5cce066-5163-11e8-97c8-4b5336565ea3.png)

**Comment by mikroskeem** [comment]
http://belle.spi.gt/iris/?channels=#waterfall

**Comment by electronicboy** [comment]
The time for the event is 100% down to a plugin taking too long, the "No client connected for pending server" also means that the users connection is no longer active, they lost connection/improperly disconnected?
