### ISSUE TITLE
Error with 1.7 Clients.

### ISSUE THREAD

**Issue by BrettPlays** [PaperMC/Waterfall#227]
I am 99% sure this is because of 1.7 clients.  It happens when someone (not whitelisted (have not tested with being whitelisted)) joins the server: https://hastebin.com/vuqidexaci.lua
Version: git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175

**Comment by electronicboy** [comment]
potentially #178, but waterfall doesn't support 1.7.x in any capacity

**Comment by Janmm14** [comment]
https://github.com/WaterfallMC/Travertine
