### ISSUE TITLE
Error whilst handling query packet from null (netty errors)

### ISSUE THREAD

**Issue by tootoll** [PaperMC/Waterfall#228]
I am getting this error on every 10-20 seconds (or less depending on number of players)
(im using https://ci.destroystokyo.com/job/Waterfall/175/)
> `[10:53:09] [Netty Worker IO Thread #0/WARN]: Error whilst handling query packet from null
> java.lang.IllegalStateException: Invalid data request packet
> 	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:154) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:26) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:478) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> `

and this one every now and then

> `java.lang.IllegalArgumentException: Chat message is empty
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:139) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Waterfall%23175.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:b0199cf:175]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> `

Any help is appreciated.

**Comment by mikroskeem** [comment]
1) Someone is sending invalid Query packets?
2) Someone is sending invalid chat packets from client

**Comment by tootoll** [comment]
Shouldn't then there be a error check that will handle problem instead throwing errors in console and logging them?

**Comment by electronicboy** [comment]
That's where that exception is coming from, the error check. You don't encounter an error and do nothing about it, that would be bad.

**Comment by tootoll** [comment]
What i meant is, shouldn't there be isEmpty() check on handling messages with inline msg about the problem instead trowing multiline log error when it occurs?

**Comment by electronicboy** [comment]
No, because that would;
1) not alert the caller that something wrong happened (e.g. they sent an illegal argument)
2) would not allow anybody to trace where the issue comes from.

**Comment by tootoll** [comment]
But as it is now cos of trowing error can (for example) some plugin still use ChatEvent even when Waterfall is trowing error so that he can check if msg is empty and dcc that user who is sending strange things?

**Comment by electronicboy** [comment]
From what I can see, waterfall is probably going to kick the user anyways for sending an invalid packet, invalid data really shouldn't ever be passed around a system which expects clean data to be passed to it.
