### ISSUE TITLE
Error pinging remote server

### ISSUE THREAD

**Issue by Neeonn** [PaperMC/Waterfall#232]
After using Waterfall for over a week now, I found one strange thing in the console..
Whenever someone is attacking my server with bots using the Ping method, bungee (waterfall) seems to lose the connection to the lobby server for a short period of time thus kicking players from the server and crashing itself.

Error from the console:
`[10:00:36 WARN]: Error pinging remote server
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:46896bd:177]`

It also says when kicking players: "Error; Lost connection to the servers"

**Comment by MarkTwoFive** [comment]
Do you have ping-passthrough enabled?

**Comment by Neeonn** [comment]
Yes, I do.

**Comment by MarkTwoFive** [comment]
Any log messages in the (actual) server log regarding that issue?

**Comment by Neeonn** [comment]
I have logs for ABD from the bungee server and just a image when players are kicked from the lobby server.
Please tell me which ones do you need so I can send them.

By the way, I'm using the latest version of Waterfall.

**Comment by MarkTwoFive** [comment]
@Neeonn I'm just gonna say "all of them".  
Please put both your proxy logs and the server log of the game server in question into a Gist and provide the link.

**Comment by electronicboy** [comment]
Closing due to lack of response and information.
