### ISSUE TITLE
[Question/Issue]

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#24]
So in the Waterfall configuration file, the follow 2 options don't seem to generate, and when a server goes down for its scheduled restart, players get kicked out of the server altogether instead of getting moved to the Lobby/HUB server.

```
  default_server: Lobby
  fallback_server: Lobby
```

Am I doing something wrong that is causing these options not to show up? Any help at all would be greatly appreciated.

**Comment by minecrafter** [comment]
BungeeCord replaced those options with a "server priority" configuration instead
