### ISSUE TITLE
Console issue with Multicraft

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#241]
Hello!

I'm not entirely sure if this is the place to go, but the aquifermc.org site is down, so went here instead.

After installing Waterfall I noticed this issue in the Multicraft console of the Proxy (Waterfall) instance.
It basically spams the console with "Command not found" messages every time the console is supposed to run the /list command. I tried changing the list command manually on Multicraft to /glist, but doesn't seem to have any effect.

Showcase: https://gyazo.com/b30d0814a2dd7a62ab06c3605f610ecb

Is there any way that you could add better compatibility to Multicraft and/or does another fix to this issue exist? Thank you either way.

**Comment by jamierocks** [comment]
This is certainly the place for bug reports, I don't think any of us actively scan the forums for issues - they should be here.

To clarify, Waterfall when used with Multicraft does this for all command or just the ones listed?

**Comment by ghost** [comment]
Just the automatic execution of the /list command. Multicraft knows how to convert the one from BungeeCord to a /glist, but not the one from Waterfall. Not really sure if anything can be done to bypass or fix this.

**Comment by mikroskeem** [comment]
This is a Multicraft configuration issue.

**Comment by electronicboy** [comment]
From my understanding, this can be disabled inside of the service definition for the software, if you can use the bungeecord profile instead of the waterfall one, that would work fine too (Nothing really changes between us and bungee that would cause any issues with that unless multicraft is doing weird things)
