### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GameModeOnX** [PaperMC/Waterfall#243]
https://hasteb.in/zekuzogi.lua
how to fix it?

**Comment by jamierocks** [comment]
This is a duplicate of #178. There isn't a proper fix, though you could look into applying #187 to your build. @electronicboy has looked into the issue far more than myself ;)

**Comment by Black-Hole** [comment]
And the issue was already reported at https://github.com/SpigotMC/BungeeCord/issues/2446 with some hints.
