### ISSUE TITLE
firewall problem

### ISSUE THREAD

**Issue by GameModeOnX** [PaperMC/Waterfall#245]
i using firewall. Its causing error during updating modules. Modules can't checking updates. How to fix it?

**Comment by electronicboy** [comment]
Fix your firewall, or upload the modules manually to the modules folder.

**Comment by GameModeOnX** [comment]
Which IP addresses does Waterfall get updates from?

**Comment by electronicboy** [comment]
currently `ci.destroystokyo.com` which redirects to `destroystokyo.com`

**Comment by kamcio96** [comment]
@GameModeOnX I suggest to allow all outbound traffic
