### ISSUE TITLE
[modserver][clientcrash]Our server's player tp to other server,Client will crash

### ISSUE THREAD

**Issue by OldKingisdie** [PaperMC/Waterfall#246]
There is a chance that the client will crash when our server players go to other sub servers
What should I do for this problem？I need some help，thanks

sponge version：spongeforge-1.12.2-2555-7.1.0-BETA-2857
waterfall version：Waterfall-Bootstrap:1.12-SNAPSHOT:4adb1b4:181
crash-report：https://www.lanzous.com/i1eo42f

If you need more info，Please talk me

**Comment by mikroskeem** [comment]
Use gist.github.com next time for crash reports. I believe that nobody wants to download a file to simply read a crash log :smile:

**Comment by OldKingisdie** [comment]
<script src="https://gist.github.com/OldKingisdie/df7d8b0e9a29c69488ff597672f0744f.js"></script>

sorry，I first use github to report my problem.

**Comment by OldKingisdie** [comment]
`<script src="https://gist.github.com/OldKingisdie/df7d8b0e9a29c69488ff597672f0744f.js"></script>`

**Comment by OldKingisdie** [comment]
`<script` src="https://gist.github.com/OldKingisdie/df7d8b0e9a29c69488ff597672f0744f.js"></script>

**Comment by OldKingisdie** [comment]
sorry，I used github for the first time to report my problem.

https://gist.github.com/OldKingisdie/df7d8b0e9a29c69488ff597672f0744f

**Comment by electronicboy** [comment]
Quick glance of the code somewhat makes it look like it's potentially a client bug or a mod not being too pleased about something, did you have a parrot on your solder or some form of entity on there before switching servers?

**Comment by OldKingisdie** [comment]
No parrot，However, when more entities appear in the rendering scope, it is more likely to cause this problem. The reason may be the client, but the crash only happens when going to other servers. I did not see this problem when I used the multi-world plugin to cross the world.

**Comment by OldKingisdie** [comment]
Maybe I have a misunderstanding of the transmission, I just think that it is more like cross-world and cross-server. But I don't know if they work the same way.

**Comment by electronicboy** [comment]
The method on your client which threw an exception is there to play sounds for entities on your shoulder, the only place in which I could see an exception being fired from there is either a client bug or something is setting invalid data onto the players shoulder, this really doesn't look like an issue that waterfall would cause.

**Comment by OldKingisdie** [comment]
According to your statement, is there a possibility that a mod may have some invalid data on the player's shoulder causing the player to crash when going to another server?

**Comment by OldKingisdie** [comment]
I hear a explanation from my server‘s admin friend
He said there is a old bug in Bungeecord，If you are a mod server. this bug will occur
The bug is that player go to other server will consumer a lot of CPU performances to render and change the world,Mod Client have more entity rendering to increase CPU's burden than vanilla.If player's computer is not so good.Client will crash.
So his server use this  proxy to connect other server.Because this proxy not have this bug

https://github.com/LilyPad

I don't know if it's true，I not sure whether this bug comes from Bungeecord. But I hope it can help you.

**Comment by OldKingisdie** [comment]
It's not the reason of Mod，I remove all mod to connect subserver But the mistake still appears.So maybe it's the problem in forge. Could you make some compatibility in this way ?

**Comment by OldKingisdie** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4901
I found this 

"Resetting the mappings while the client knows about a world is NEVER a good idea. But we can't convince BungeeCord to reset the handshake outside of the world. So whatever."

**Comment by electronicboy** [comment]
Welp, that looks like your issue there including a fix, we might be able to make bungeecord handle this a bit more gracefully, but I really don't have the time to look into this with 1.13 out too

**Comment by Aang23** [comment]
This crash was fixed in forge a while ago. Just upgrade you client forge version to 2705 or newer.

**Comment by OldKingisdie** [comment]
@Aang23 Thinks！！！It‘s a Hot wire！
