### ISSUE TITLE
Fake players problem..

### ISSUE THREAD

**Issue by NeximaOzi** [PaperMC/Waterfall#251]
Hello,

Look this video please.
https://vk.com/video246456789_456239018

In server showing too much players.
http://prntscr.com/k7ubnp

and players can't join to server.. They waiting when try join "Logging in..."

**Comment by mikroskeem** [comment]
You are getting botted, get yourself an anti bot plugin.

**Comment by NeximaOzi** [comment]
Would you recommend a good one for this problem?

**Comment by mikroskeem** [comment]
Turn on online mode or search from [Google](https://www.google.ee/search?q=bungeecord+anti+bot+attack)

**Comment by JorisPV** [comment]
@NeximaOzi The best anti bot I know is this one: https://www.spigotmc.org/resources/antibot-bot-sentry-%E2%9C%AF-the-fear-of-all-bot-attacks-bungeecord.55924/ even if it is paying, I recommend it.
