### ISSUE TITLE
1.13 Clients Disconnected

### ISSUE THREAD

**Issue by Fluxty** [PaperMC/Waterfall#255]
In the latest version of Waterfall, I'm able to connect to my 1.8.8 lobby server on 1.13 but I'm disconnected 5-10 seconds later.

> Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

Using an older version of Waterfall with ViaVersion instead resolves this issue. Of course it would be best if I didn't have to run ViaVersion at the Bungee level :) Thanks!

**Comment by jamierocks** [comment]
Ref @electronicboy.

Could you please Gist the whole stacktrace.

**Comment by Leymooo** [comment]
Hi. Waterfall was not fully updated to 1.13. ScoreboardObjective and Teams now have a Json in prefix, suffix, etc.. (Chat component)
http://wiki.vg/Pre-release_protocol#Scoreboard_Objective

**Comment by jamierocks** [comment]
Interesting, nice change - will try get that fixed ASAP.

**Comment by Leymooo** [comment]
I am not test this, but i think that will work. https://github.com/Leymooo/BungeeCord/commit/2ed81ffe09beb6db0ca2e1b33d6624563c0ef00f

**Comment by Leymooo** [comment]
I am not tested this, but i hope that it will work. https://github.com/Leymooo/BungeeCord/commit/3f643c27b93053ad566f53932bc7b3965d62371e

**Comment by electronicboy** [comment]
Should be resolved, bungee did have the logic to pass through the info properly, however API detail was broken due to that one

**Comment by Leymooo** [comment]
Team Display Name is also a Chat in Teams

**Comment by Fluxty** [comment]
@electronicboy Using the latest Waterfall, I'm now unable to join on 1.8.9 and 1.13. Using an older version with ViaVersion still resolves the issue. 

Gist: https://gist.github.com/Fluxty/7ce53ab9e8091ef392279de68a675087

**Comment by electronicboy** [comment]
Please try the latest build, I ended up parsing the wrong field

**Comment by amadeusmz** [comment]
Still can't join the lobby

**Comment by Leymooo** [comment]
@electronicboy wiki.vg does not say, that displayname is Chat component. 
I think that json data was not correctly converted to BaseComponent. Maybe add debug?

**Comment by electronicboy** [comment]
Sorry, I'll sort this out later, feel free to submit a PR; I'm clearly not feeling well enough right now to sort this, build 198 should work at the expense of the bungee API not supporting teams and objectives properly (you will need to disable any proxy side stuff with this)

**Comment by amadeusmz** [comment]
This issue is caused by BungeeTablistPlus and they fixed it.

**Comment by electronicboy** [comment]
Closing, some of my overly tired changes caused some issues, ontop of other plugins; Appears to that all issues here appear to be fixed now

**Comment by Leymooo** [comment]
Okey. I think we need do something with this patch, because some big plugins now send a json string. Like a BungeeTabListPlus. 

![nxyqvmrmhgg](https://user-images.githubusercontent.com/8667294/43206253-ef8b6a5e-902d-11e8-8119-14da98c3297f.jpg)
Author say: _Don't use Waterfall or any other BungeeCord forks. Get BungeeCord from https://ci.md-5.net/job/BungeeCord/ and you won't experience any issues._

I suggest to revert all changes, or check if string is json before convert it to json. (ComponentSerealizer has a field with ~~JsonElement~~ JsonParser. I think you can use it)

**Comment by Leymooo** [comment]
Its my version for fix this(Untested, but i hope that it works). https://github.com/Leymooo/BungeeCord/commit/5f32b40e17c1b0cb459dcfbd210abc31398ac6d0#diff-cde8e0bfd70cda93f1098dd45704f431R48

**Comment by jamierocks** [comment]
Yeah, I think that's the best solution for now.

**Comment by Leymooo** [comment]
Okey. This is dont work correctly. I will go deeper later. 
![rn7qijuhs3s](https://user-images.githubusercontent.com/8667294/43215531-11e149ae-9045-11e8-84dd-e4cd9c037a1e.jpg)

**Comment by electronicboy** [comment]
Providing support for this would be great, but shamefully that can't come at the cost of other plugins, as such, I've pulled these changes for now; We should look into adding this back, however this cannot come at the cost of newer plugins using the API, which is shamefully going to be unlikely due to plugins assuming that they should either be sending or recieving json.

**Comment by Leymooo** [comment]
If i will found what is wrong, i will make a pr when i test it.

**Comment by Leymooo** [comment]
Okey. I found what is wrong.
```
    public static void writeStringAsChatComponent(String s, ByteBuf buf)
    {
        System.out.println( "--Debug Start---" );
        System.out.println( "String is '" + s + "'" );
        try
        {
            JsonElement el = ComponentSerializer.getJSON_PARSER().parse( s );
            System.out.println( "String is json [" + el.toString() + "]" );
            writeString( s, buf );  //Its a json string
        } catch ( JsonSyntaxException ex )
        {
            s = ComponentSerializer.toString( TextComponent.fromLegacyText( s ) );
            System.out.println( "String is NOT json. Writing: '" + s + "'" );
            writeString( s, buf );
        }
        System.out.println( "--Debug End---" );
    }
```
```
16:28:33 [INFO] --Debug Start---
16:28:33 [INFO] String is '§f§f  §7§o Слот #9 '
16:28:33 [INFO] String is NOT json. Writing: '{"extra":[{"color":"white","text":"  "},{"color":"gray","italic":true,"text":" Слот #9 "}],"text":""}'
16:28:33 [INFO] --Debug End---
16:28:33 [INFO] --Debug Start---
16:28:33 [INFO] String is '§f'
16:28:33 [INFO] String is json ["§f"]
16:28:33 [INFO] --Debug End---
```

JsonParser#parse parse §f as JsonPrimitive. Also its like that it is not updated version of BungeeTabListPlus(Screenshots is not mine).
https://github.com/Leymooo/BungeeCord/commit/5170fd174c0f201a59d32a73dd787b36b04774c3

I will make a pr, if no problems were found
