### ISSUE TITLE
Can't Join

### ISSUE THREAD

**Issue by zBoringDrop** [PaperMC/Waterfall#258]
I'm using waterfall, build n 203 and players can't join in: https://pastebin.com/FM9b5iK8

**Comment by amadeusmz** [comment]
same issue

**Comment by electronicboy** [comment]
Try updating, I've just applied a few changes

**Comment by zBoringDrop** [comment]
You fixed the error, but if i can't join in hub, the waterfall kick me for server crashed and on hub i see "kicked for internal error"
why you don't test yourself?

**Comment by zBoringDrop** [comment]
Ehm, if i try to connect in my hub with a non 1.13 version (as 1.12.2) and i try to switch in another server (from hub), it say me this: https://imgur.com/a/NZzZQbz

**Comment by zBoringDrop** [comment]
Up with 2 errors: https://pastebin.com/545dc6Mc
