### ISSUE TITLE
Build on Windows broken

### ISSUE THREAD

**Issue by Black-Hole** [PaperMC/Waterfall#262]
Since commit https://github.com/WaterfallMC/Waterfall/commit/126c0d88ddd55d0e9766d28fd6d81cd3960970ee#diff-911b1ca4b34d45a115afee01b1e4fbb9 build on Windows is broken, because the file system is case insensitive.
So there can't be a folder "Waterfall" and a file "waterfall" in the same folder.

**Comment by jamierocks** [comment]
There isn't a directory called `Waterfall` within the same directory though. Also Windows support is rather difficult - there is no native Git builds. I'm pretty sure this doesn't break usage through Git Bash?

**Comment by Black-Hole** [comment]
The folder "Waterfall" will be created by the script. And since it's a file, the parent directory will be used and reset to BungeeCord.
```
$ ./waterfall p
Rebuilding Forked projects....
fatal: repository 'BungeeCord' does not exist
scripts/applyPatches.sh: line 31: cd: /c/Developing/Waterfall/Waterfall-Proxy: No such file or directory
Resetting Waterfall-Proxy to BungeeCord...
Your branch and 'origin/master' have diverged,
and have 1527 and 203 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
fatal: ambiguous argument 'upstream/upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  Applying patches to Waterfall-Proxy...
fatal: could not open '/c/Developing/Waterfall/BungeeCord-Patches/*.patch' for reading: No such file or directory
  Something did not apply cleanly to Waterfall-Proxy.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh
```

**Comment by jamierocks** [comment]
I'm a little confused tbh, we've had a contributor use Windows and Paper works, right?

I'm going to boot up my surface and give it a go.

**Comment by Black-Hole** [comment]
After another test it's because I didn't run "./waterfall b" first. That created the directory "Waterfall-Proxy" and the build succeded.
Anyway, the script could be improved to stop if the folder doesn't exist and not overwriting the working directory.

**Comment by jamierocks** [comment]
The script should create the directory if it doesn't exist... https://github.com/WaterfallMC/Waterfall/blob/master/scripts/applyPatches.sh#L29

edit: build even uses that script

**Comment by jamierocks** [comment]
I just tested this on my Windows machine, and was able to run the `patch` script just fine, I'm not sure why yours doesn't work :S

**Comment by Black-Hole** [comment]
A freshly cloned Waterfall doesn't have the directory Waterfall-Proxy, so "./waterfall p" will fail. Running "./waterfall b" first creates that directory, so "patch" will work as expected.

**Comment by electronicboy** [comment]
Should be fixed, waterfalls script wasn't pulling in the submodules when you run just patch, and so it would cause anybody who didn't already have that submodule checked out to fail
