### ISSUE TITLE
Can't interact with messages and chat on 1.13

### ISSUE THREAD

**Issue by zBoringDrop** [PaperMC/Waterfall#263]
Hi, i'm using Waterfall 1.13, build 209 (while 218 snapshot of viaversion) and if i join with 1.13 client on 1.13 (and all other versions) servers, i can't write and send messages and commands. (if i send a message, the chat doesn't show it, and also in the console, my message/command doesn't appears. It is as i don't write anything on chat).
Is this a proxy error or viaversion error?

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/43054042-a476dc04-8e27-11e8-835a-d0acdac77b3a.png)
Appears to be working perfectly fine in both directions here, you would need to attempt to replicate without any plugins on the proxy/server itself
