### ISSUE TITLE
Unexpected packet received during server login process

### ISSUE THREAD

**Issue by Alexre** [PaperMC/Waterfall#264]
I'm using the latest snapshot, I'm getting these errors randomly on the console:

https://hastebin.com/onomiserow.bash

**Comment by electronicboy** [comment]
Looks like something on your server is sending invalid messages to bungeecord which is triggering that, try replicating without plugins on either waterfall and a 1.13 server

**Comment by juzhijian** [comment]
me too

**Comment by electronicboy** [comment]
Closing, this isn't an issue caused by waterfall (nor can we do anything about this beyond ignoring bad stuff), something on the server is sending invalid information to the proxy.
