### ISSUE TITLE
Bug: Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#265]
Hello,

A rather recurrent error returns on my console bungeecord since several updates.
I noticed we only had this problem with the hubs.

Error : https://hastebin.com/tixokijomu.bash
Version : git:Waterfall-Bootstrap:1.13-SNAPSHOT:9b49f93:210

Do you need more information? Thank you in advance.

**Comment by stephan-gh** [comment]
Duplicate of https://github.com/WaterfallMC/Waterfall/issues/264
