### ISSUE TITLE
 I don't know if the problem should be submitting requirements or bug

### ISSUE THREAD

**Issue by OldKingisdie** [PaperMC/Waterfall#266]
I want to link a Waterfall's lobby to another Waterfall But it failed

I don't know if this function is supported XD

waterfall：Waterfall-Bootstrap:1.12-SNAPSHOT:4adb1b4:181
forge：forge-1.12.2-14.23.4.2705-universal
sponge：spongeforge-1.12.2-2705-7.1.0-BETA-3328

Cosole ERROR Log：https://gist.github.com/OldKingisdie/4b30c14fbb6e5c9af6cac96ef744e96f
waterfall config a ：https://gist.github.com/OldKingisdie/6a61810676d07d079d74398c52724436
waterfall config b：https://gist.github.com/OldKingisdie/950f53a5d7e7571d1e01eaeb3ff88c72

**Comment by jamierocks** [comment]
Not supported.
