### ISSUE TITLE
Forge/SpongeForge

### ISSUE THREAD

**Issue by awitkowski0** [PaperMC/Waterfall#272]
Spongeforge: 1.10.2-2477-5.2.0-BETA-2793 
Waterfall: Build #216 (Aug 12, 2018 3:00:09 PM)

This issue started occurring once we ip-forwarded the server. After that the server started timing out players every 5-10 minutes due to the "Timed Out", and the server said "io.netty.handler.timeout.readtimeoutexception"

We're currently running the skyfactory 3 pack.

Mod list:
http://skyfactory3.wikia.com/wiki/Mod_List

**Comment by MarkTwoFive** [comment]
Increase the read timeout of your server. I believe it was `-Dfml.readTimeout=`. This should make it work again. 
I have faced similar issues with some players even not behind BC/Waterfall.

**Comment by electronicboy** [comment]
Timing out players in such a manner indicates that the client didn't send any data to the server, or that it was lost for some reason more than likely going to be down to network issues; If you're losing multiple players, I'd double check the proxy logs for any issues, but I believe that your best bet is going to be to monitor to the connection to your proxy, and if the proxy is running on a different box, from there to where your servers are running;

enabling ip forwarding on bungee only makes the server start adding some information to the login request, nothing else which would have the potential to cause this issue from that setting
