### ISSUE TITLE
Client error?

### ISSUE THREAD

**Issue by timr2000** [PaperMC/Waterfall#273]
Got an error when someone is disconnection: https://pastebin.com/9qajJx06

**Comment by Black-Hole** [comment]
Please copy all relevant lines from the server log, not your web console.

**Comment by timr2000** [comment]
@Black-Hole https://pastebin.com/vyLs7pEx
Waterfall version: 216

EDIT: Looks like it happens when someone is joining/leaving

**Comment by Black-Hole** [comment]
0d is the kick packet. So a plugin kicks the player while logging in.

**Comment by Janmm14** [comment]
@Black-Hole it says unexpected packet **recieved**

**Comment by electronicboy** [comment]
Those messages only dump the contents, not what would be the packet id is; something on your server is sending invalid data

**Comment by Black-Hole** [comment]
The first byte is the packet id. There is no kick packet expected during this early login process.

**Comment by timr2000** [comment]
Dont know what plugin can cause this?¿
