### ISSUE TITLE
Unsupported characters sent through plugin messaging channels crash newer clients (1.13).

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#277]
**Proxy Environment**
Waterfall dev 218
ViaVersion dev 224

**Server Environment**
Paper dev 1547 _(Spigot 1.12.2)_
ProtocolSupport dev 242 _(Last Spigot 1.12.2 supported build)_

RE: https://github.com/MylesIsCool/ViaVersion/issues/981#issuecomment-414079292

I ran into an issue of being unable to connect with a 1.13 client through BungeeCord (Waterfall) with a form of protocol remapping support to allow newer clients to connect on an older server version. Upon investigation, it seemed to be caused by a plugin sending an unsupported character through an EmptyCustomPayloadPacket on connect and also has a few places with the character in various CustomPayloadChannelNames - specifically the pipe symbol ```|```.

> The issue is down to BungeeCord rewriting the plugin messages from protocolsupport, because it uses a pipe symbol this isn't compatible with 1.13.
>
> Ideally, BungeeCord should rewrite the pipe symbol as this issue could also happen if a BungeeCord plugin used it for messaging.

I'm not sure if this issue is too trivial to fix upstream within BungeeCord, but if it falls into the scope of Waterfall, a fix would be greatly appreciated -- so unsupported characters get remapped or stripped to prevent crashing newer clients. :)

**Comment by Janmm14** [comment]
Likely relevant code: https://github.com/SpigotMC/BungeeCord/blob/176b75b97edaaea8551123664ebc4c9975e05225/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L235

**Comment by electronicboy** [comment]
Being perfectly honest, I'm really not sure what the best way to deal with this mess is;
No matter what we do to fix this, we're going to make this entire situation even worse, if you have plugins which are using invalid messages, your best and only real fix is going to be to patch the involved plugins to properly support all versions
