### ISSUE TITLE
upstream patches

### ISSUE THREAD

**Issue by MedicOP** [PaperMC/Waterfall#284]
Some waterfall patches were added upstream so are redundant now (unless you keep them for backwards compatibility)
https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0014-Don-t-allow-channel-buffers-to-grow-beyond-a-reasona.patch
https://github.com/SpigotMC/BungeeCord/commit/bd5a7e5b26b698c57e6f99933452bfc0659269f9

https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0022-Optional-server-list-ping-logging.patch
https://github.com/SpigotMC/BungeeCord/commit/ba0739798a0b6f184eca4def52750e8633623487

**Comment by electronicboy** [comment]
The first patch needs looking into, that looks like that could be dropped
The second patch is there to retain our own setting, doesn't look like waterfall or bungee where really designed for dealing with evolving configs

**Comment by Orodato** [comment]
And maybe this patch ?
https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0037-Security-enhancements-for-EncryptionUtil.patch
https://github.com/SpigotMC/BungeeCord/pull/2380

And the lines 7 and 10 can be removed on this patch: https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0017-Micro-optimizations.patch#L6-L10

**Comment by Orodato** [comment]
And what this patch should do ?
https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0028-Don-t-send-KICK-packets-while-in-HANDSHAKE-state.patch

Because this break plugins that disconnect during the PlayerHandshakeEvent (the players don't see the kick message)

When the event is call the client is not in handshake, and bungee set the new state just after calling the event

**Comment by electronicboy** [comment]
The protocol doesn't support sending kick packets until we've left the handshake state, thus the packet lookup would fail on the proxies side, as per issue #12 which is what that patch was intending to solve, only once we're on LOGIN can we actually send a kick packet
