### ISSUE TITLE
Connections issue - bots attacks

### ISSUE THREAD

**Issue by haeiven** [PaperMC/Waterfall#286]
Hi,

Since few months, bots attacks are more and more stronger, I'm a contributor of AntibotDeluxe plugin, and I recently noticed something unusual:

![screenshot_2](https://user-images.githubusercontent.com/11612016/45821086-a61aaa00-bce8-11e8-8ff0-924dd445139a.png)

When the attack start, number of connections are growing more and more, and when the limit is reached (Default 1Million), the dedicated can't reach the network. Is waterfall closing connections correctly?

This attack was only 600-800 bots/s.
Some people can reach 2000/4000 bots/s.

Maybe the main developper of Antibotdeluxe did something wrong?

I noticed this only on Waterfall, this don't happend on Spigot/Paper.

Best regards,

**Comment by MarkTwoFive** [comment]
Did you test this with plain BungeeCord?  
If its the case with it too, it should be fixed upstream.

**Comment by haeiven** [comment]
Going to make tests tomorrow.

**Comment by haeiven** [comment]
Need to be fixed upstream.

https://github.com/SpigotMC/BungeeCord/issues/2532
