### ISSUE TITLE
ActuallyAdditions crates buttons not working

### ISSUE THREAD

**Issue by TeraNovell** [PaperMC/Waterfall#287]
Hello,

I noticed a bug when I tried to switch pages in an Actually Additions Crate nothing happens.

This only occurs when the Server is behind a Bungeecord.

Is there a chance for a fix on your side?

**Comment by MarkTwoFive** [comment]
> This only occurs when the Server is behind a Bungeecord.   

Please report such issues to BungeeCord first then. ^^

**Comment by TeraNovell** [comment]
> 
> 
> > This only occurs when the Server is behind a Bungeecord.
> 
> Please report such issues to BungeeCord first then. ^^

@MarkL4YG  I wrote Bungeecord but to be specific the Server was behind a Waterfall.

**Comment by MarkTwoFive** [comment]
Then please try to reproduce this with BungeeCord first :)  
Any change made in this project further deviates it from upstream. Therefore, when a bug is present upstream too it should be fixed there.

**Comment by electronicboy** [comment]
More than likely down to the underlying system behind #136
Bungee performs some modifications to packets with entity ids, and shamefully this modification breaks mods which rely upon using these IDs, I'm hoping to basically find the time to finish off removing this system, however, filing an issue with the mod author about this is a good idea as they may be able to provide a more universal fix

**Comment by TeraNovell** [comment]
@electronicboy, @MarkL4YG Thanks four your help!
I close this Issue and wait for this change: #136
