### ISSUE TITLE
More CPU usage than origin bungeecord while >600 online

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#29]
Hardware: DELL r730 E5-2699v3 dual
OS: ubuntu-14.04lts
A cluster, upto >5000 online, under 5-10 bungeecord balance with LVS. Waterfall have definite less CPU usage while <600 online, but more CPU usage while >600 online.
How can I help you?:-)

**Comment by Janmm14** [comment]
Whats the cpu usage difference? Are the machines equal?

**Comment by caoli5288** [comment]
@Janmm14 Yes all machines equals.

**Comment by Janmm14** [comment]
....

**Comment by caoli5288** [comment]
![20160618163637](https://cloud.githubusercontent.com/assets/3120587/16169924/f3d676c4-3505-11e6-8097-e562ae02d9a6.png)
Left, Waterfall. Right, origin Bungeecord. ~1000 online each instance.

**Comment by Janmm14** [comment]
try running yourkit (test version) or jvisualvm (free) cpu monitoring. however its possible that these are just normal differences that the players on waterfall do more. Also its possible that some plugins often add and remove listeners which is slower in waterfall (but event execution is faster). Or plugins do other things.

**Comment by caoli5288** [comment]
@Janmm14 There is only three plugins: RedisBungee-0.3.9-SNAPSHOT.jar, MultiLobby.jar and ServerListPlus-3.4.4-Universal.jar
Profiling cannot get more usage info, most CPU time in netty thread.

**Comment by Janmm14** [comment]
> most CPU time in netty thread

How do you know it? Profiling shows the speed of a method btw. (much more exact) and bungee and waterfall also do things in netty threads.

**Comment by caoli5288** [comment]
![20160624200537](https://cloud.githubusercontent.com/assets/3120587/16337376/abca3662-3a47-11e6-89ce-25c085935dca.png)
Left is an waterfall instance, right is bungeecord. ~1200 client per instance. waterfall ate much more CPU time then origin bungeecord.

**Comment by Janmm14** [comment]
These screens do not help. You did not said from where there you know that

> most CPU time in netty thread

 and your statement

> Profiling cannot get more usage info

is wrong, profiling gives a per-method average speed which is more information than comparing cpu percentages.

**Comment by caoli5288** [comment]
@Janmm14 Are you maintainer? I'll take profiling screen snapshot next after

**Comment by Janmm14** [comment]
@caoli5288 No, I'm no maintainer.

**Comment by caoli5288** [comment]
![2016-06-25 11-09-00](https://cloud.githubusercontent.com/assets/3120587/16354396/53e7e65e-3a58-11e6-9382-ec2f2c8708ce.png)
Waterfall's

**Comment by caoli5288** [comment]
![2016-06-25 11-09-07](https://cloud.githubusercontent.com/assets/3120587/16354399/6de28460-3a58-11e6-8858-4f967ebf6cf6.png)
Bungeecord's

**Comment by Techcable** [comment]
Could you order the methods by CPU so we can see whats eating the CPU?
Currently it looks like the program is IO bound.

**Comment by caoli5288** [comment]
@Techcable I'll do it next day.

**Comment by Techcable** [comment]
Yes, thats a good point that registering listeners is slower in waterfall.
Right now waterfall doesn't cache the generated event executors, which could possibly cause these performance issues.

**Comment by caoli5288** [comment]
@Techcable I'll switch to test the newest version. :-)

**Comment by jamierocks** [comment]
Anyone able to confirm if this is still an issue?

**Comment by Malachiel87** [comment]
for me it use like 200-400% with 400 player around. not sure if is normal
