### ISSUE TITLE
Waterfall server disconnect

### ISSUE THREAD

**Issue by zBoringDrop** [PaperMC/Waterfall#291]
Hi, sometimes a random server between factions and vanilla got disconnet from waterfall, so i must do /greload or reload the waterfall.. why? :\

**Comment by electronicboy** [comment]
Sorry for the delay due to illness, however you have failed to provide any useful information to this issue, is there an error? do the servers disappear from /server or can you just not connect to them? Have you tried removing plugins?

**Comment by zBoringDrop** [comment]
No, no errors bug i have this problem: the servers disappear from /server.
I have tried removing a plugin called Bungeeresourcepack since other problem of compatibility but idk if i have solved.. idk why this happen, so i cant reproduce it to test :/

**Comment by electronicboy** [comment]
Servers cannot disappear from /server unless something installed on the server is modifying the server list, this is 100% going to be down to a plugin removing servers from the proxy

**Comment by zBoringDrop** [comment]
Wait, so what kind of plugin i should try to remove from waterfall?

**Comment by MarkTwoFive** [comment]
@zBoringDrop Each one - until you know which one is causing the culprit.

**Comment by zBoringDrop** [comment]
The problem is that i don't know how reproduce this bug.
@electronicboy what do you mean for "this is 100% going to be down to a plugin removing servers from the proxy"?

**Comment by electronicboy** [comment]
The only way that a server can be removed from the proxy at runtime, i.e. removed from `/server` is for something to have modified the ServerInfo list using the API

**Comment by zBoringDrop** [comment]
And what are the plugins that typically edits the "ServerInfo list using the API"?

**Comment by MarkTwoFive** [comment]
@zBoringDrop Go through your plugin list and remove them one at a time until the issue disappears.
And yes, knowing how to reproduce this will help you with this method.
