### ISSUE TITLE
empty packet on 1.13 tab completion

### ISSUE THREAD

**Issue by Nikokku** [PaperMC/Waterfall#292]
My setup is a waterfall server that connects the user to a properly configured 1.13 server (bungee is enabled, online mode is off, etc.). 

Now when a user on that 1.13 server types a command that has to be followed by another argument, for example '/home ...' or '/tp ...' then as soon as he hits spacebar after the main command, he will get kicked with  a message that the server went down and waterfall prints out the following error:
_https://hastebin.com/icuwaxibec.sql_

**Testing this without any plugins resulted in the exact same problem with no changes.**

**Comment by electronicboy** [comment]
A new configuration option has been added to waterfall to allow a setup in which the proxy won't kick for this error and to deal with empty packets like the vanilla client. This issue is down to your server sending invalid traffic via the proxy, I'd suggest looking into what it is first, however.
