### ISSUE TITLE
 <-> InitialHandler - read timed out

### ISSUE THREAD

**Issue by 0xC1A551C** [PaperMC/Waterfall#294]
If I join & leave my server quickly I get this error  <-> InitialHandler - read timed out

it says "connecting to server..." for 30 - 60 seconds then says "timed out".

I can reproduce it easily

**Comment by Janmm14** [comment]
Did you test this also with bungercord?

**Comment by 0xC1A551C** [comment]
> 
> 
> Did you test this also with bungercord?

The issue does not happen with bungeecord

**Comment by mibby** [comment]
Is your netty dns resolver setting enabled?

https://github.com/PaperMC/Waterfall/issues/211

**Comment by electronicboy** [comment]
Logs? How are you joining the server that fast? Screenshot of the actual error message, etc, etc
