### ISSUE TITLE
Option to hide fake connections InitialHandler - read timed out

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Waterfall#297]
Is it possible to hide fake connections being made? For example: [https://hastebin.com/oyojexareq.md](https://hastebin.com/oyojexareq.md) (Note how the mc name is just random letters on each IP). I've basically got an issue where someone is attacking my proxy with bots and it spams the log pretty hard and sometimes causes the proxy to freeze. I've tried using the many options which mention hiding ping related stuff on both bungeecord and waterfall configs but none of them seem to deal give me a way to hide this stuff.

**Comment by electronicboy** [comment]
You can probably use a plugin to filter that information or create a custom log4j config based on the one from the jar which can filter stuff, however; no, I will not provide configuration options which hide feedback from errors, even this is something you should be looking to address with your firewall

**Comment by sgdc3** [comment]
@electronicboy as i pointed out multiple times, log4j filters cause huge performance issues

**Comment by Janmm14** [comment]
Remove logging will not solve bot attack problems.

**Comment by SecretlyJealous** [comment]
@Janmm14 The issue is that the proxy is being spammed these fake connections thousands of times a second and it's causing the proxy to freeze before any sort of mitigation can take place. I have no idea why the fake connections are even displayed in the first place, 124.41.215.157:57050|vHCunsZylGqkaNWZ is not a legitimate mc user trying to join so why does it bother showing me that in console? Am I doing something wrong here?

**Comment by Janmm14** [comment]
> @Janmm14 The issue is that the proxy is being spammed these fake connections thousands of times a second and it's causing the proxy to freeze before any sort of mitigation can take place. I have no idea why the fake connections are even displayed in the first place, 124.41.215.157:57050|vHCunsZylGqkaNWZ is not a legitimate mc user trying to join so why does it bother showing me that in console? Am I doing something wrong here?

Its a legit name, it has 16 chars, not more. Are you using online mode or offline mode?

Remove logging will not solve bot attack problems, it will at max require more effort on attacker's side.

Take a few connecting ips and put them into google, optionally with the "proxy" keyword. Often you will find some pages lsiting many free socks proxies, copy all proxy addresses from these and create a script to block them via iptables.

**Comment by SecretlyJealous** [comment]
Sorry I should have been more clear when I said it's not a legit name. It's not a taken name it's just random characters: [https://namemc.com/search?q=vHCunsZylGqkaNWZ](https://namemc.com/search?q=vHCunsZylGqkaNWZ). It's not a cracked server. Removing logging will stop things like this: https://hastebin.com/ixinigoqus.css from basically taking down the proxy. There's too many different proxy ip's being used so it's hard to basically find them all and put them in an iptable which is why I thought it would make more sense to have an option to hide this type of info in the config. It's basically a layer 7 ddos attack.

**Comment by electronicboy** [comment]
I have doubts that it's the actual logger that is holding the performance back there unless your terminal is slow as much as the actual connections themselves. At the end of the day, the fix here is to not remove logging, but to work on blocking such connections to your server.

We will *not* provide the ability to disable error messages, they hinder your and our ability to debug issues from log files. If you want to fork the software and do this yourself, you're more than welcome to, however, my stance on this will likely not change, the logger is there for a reason, we're not here to hinder it

Best suggestion is to take IPs and work on blocking netmasks, or looking into using ASNs to block networks which are being a nuisance

**Comment by SecretlyJealous** [comment]
I've already solved this issue by basically breaking the whole logging stuff which fixed the issue as my host was able to analyse the amount of packets being sent since the bungeecord wasn't crashing anymore and have changed the sensitivity of it. Just thought it would be nice to have this sort of option since I had to go to an extreme length just to disable viewing that "InitialHandler" stuff.
