### ISSUE TITLE
User cannot join server after changing their name

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Waterfall#298]
Started using Waterfall instead of bungeecord since yesterday but have an issue with a player who is not able to join the server after changing their name. Might be because they only changed the capitals in their name?
<img width="767" alt="glitch" src="https://user-images.githubusercontent.com/10485646/47610104-e3d7c480-da44-11e8-918f-c81a0ce317c5.png">

**Comment by electronicboy** [comment]
This kick originates from the backend server, not the proxy
