### ISSUE TITLE
Error on player connection.

### ISSUE THREAD

**Issue by xGioChR** [PaperMC/Waterfall#30]
Hello!
As the title says, the console get spammed with this http://pastebin.com/zgLa8tgD .
Any ideas?

**Comment by Janmm14** [comment]
Seems like you have ping passthrough on with some creepy forced hosts.

**Comment by xGioChR** [comment]
I solved the previous issue, but today I noticed this error showing in the console on player join -> http://pastebin.com/R0wa2tVt

http://pastebin.com/Hfif6Psp

**Comment by Janmm14** [comment]
First pastebin: No real error, its just something bungee waits for netty instead of fixing it themselves.
Second pastebin: Too many open files - you need to increase the server's open file limit, google it

**Comment by xGioChR** [comment]
Okay, I figured out how to increase this limit.
What should I set as the limit?

ps. an other error http://pastebin.com/GjKyy8iR

**Comment by Janmm14** [comment]
@xGioChR That error is caused by an obfuscated plugin which main class is called `wl` (look bungee.yml / plugin.yml with a zip tool inside your plugins jars)
