### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by JH3Y50N** [PaperMC/Waterfall#302]
start bungee server: http://prntscr.com/ldydqc

**Comment by LuminousLoreBloom** [comment]
Post your config.yml

**Comment by electronicboy** [comment]
Your config.yml is invalid, I generally suggest to just delete the configuration file and rework it, ensuring that you stick to the existing format, or ask for assistance on the discord/IRC, paperdiscord.emc.gs https://github.com/PaperMC/Waterfall#join-us
