### ISSUE TITLE
Error whilst handling query packet from null

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#303]
Just thought I'd give Waterfall a try. Being new to Waterfall, I don't know if this is an error due to a miss configuration or a real error. Never had this error with BungeeCord.

So here we go:
https://pastebin.com/bEdNtUHb

**Comment by mikroskeem** [comment]
You can ignore this. Somebody sent an invalid query packet.

**Comment by x1p** [comment]
If this is a "business as usual" empty packet, then I would expect a normal readable message like "Empty packet --> disregarding"

Funny thing is: this is my own (optifine)client sending this. I have a good internet connection, so can't explain whats causing an empty packet.

**Comment by Janmm14** [comment]
minecraft clients usually doesn't send any query packet.

query is udp, not tcp and likely on a different port.

**Comment by Janmm14** [comment]
Also the exception does NOT state "empty packet".

**Comment by x1p** [comment]
Excuse me :-)
"Invalid packet - disregarding"

**Comment by Janmm14** [comment]
"java.lang.IllegalStateException: No session!"

This does not need to come from your modified minecraft client.

The query protocol is a different protocol which allows remote control after authentication of minecraft and bungeecord and uses the udp protocol.

A normal minecraft client only uses the tcp protocol and so cannot cause the exception in the linked pastebin.

Query protocol may be used by some server lists, those often show an option labeled as that.

If you do not need the query protocol, you can disable it in the config.

**Comment by electronicboy** [comment]
Closing, as already noted, somebody is sending invalid traffic to your server, invalid packets are not "normal business", but, any application on the public network is always at risk that somebody is going to send it something it doesn't understand
