### ISSUE TITLE
Suggestion : Add support for server-icon.png

### ISSUE THREAD

**Issue by EOT3000** [PaperMC/Waterfall#304]
Bungee cord has a thing where if you put a file called server-icon.png in the server directory, then the server in the servers list will have that icon. I switched to waterfall from bungee cord, but the icon doesn't show.

**Comment by electronicboy** [comment]
Waterfall already has support for this from upstream, are you sure that you're not using ping passthrough which will rely on the server to reply to the ping, and provide the icon; Other than that, version? logs?

**Comment by EOT3000** [comment]
version: git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237
no logs relevant to topic. What is ping passthrough? Is it in config.yml?

**Comment by electronicboy** [comment]
ping passthrough means that bungee should proxy the request to the server itself, as opposed to replying to the message itself; There are no code changes inside of waterfall to this section of code, so I'm not all too sure why this would work on bungee and not waterfall

**Comment by EOT3000** [comment]
Well I fixed it
