### ISSUE TITLE
disconnected with: Exception Connecting

### ISSUE THREAD

**Issue by Chazotu** [PaperMC/Waterfall#312]
Waterfall Build: 238
Plugin: None

After Updating Waterfall Every time a Player wants to join he gets disconected whit the Error

disconnected with: Exception Connecting: iIllegalArgumentException : Unexpected packet received during server login process!
1bcc017b227472616e736c617465223a22646973636f6e6e6563742e67656e65726963526561736f6e222c2277697468223a5b22496e7465726e616c20457863 @ net.md_5.bungee.ServerConnector:157

Waterfall Log : https://pastebin.com/fb5c4fxG

**Comment by electronicboy** [comment]
The ServerConnector handler is for handling packets from the server itself, the login protocol does not define a kick packet, and when the server closes the connection it sends a packet which ends up hitting some code in waterfall to handle these packets which aren't in the protocol spec for this phase

The message decoded is: Ì{"translate":"disconnect.genericReason","with":["Internal Exc
Being the disconnection reason from the server
