### ISSUE TITLE
All servers show the same player count

### ISSUE THREAD

**Issue by KarlOfDuty** [PaperMC/Waterfall#314]
Is there an option to make them show their individual player count?

![image](https://user-images.githubusercontent.com/18099825/48962160-a2233680-ef7c-11e8-8df9-bcf0ac8a12c0.png)

There is only me online in one of the servers when this picture was taken.

**Comment by Janmm14** [comment]
possible with config currently only with ping passthrough

**Comment by KarlOfDuty** [comment]
Ping passthrough is on on all servers though.

**Comment by Janmm14** [comment]
tested with bungeecord?

**Comment by KarlOfDuty** [comment]
Nope not yet, will do during next server maintenance.

**Comment by KarlOfDuty** [comment]
It seems like it happens in bungeecord as well.

**Comment by electronicboy** [comment]
![image](https://user-images.githubusercontent.com/1228900/48968485-38d90d00-efe8-11e8-87e5-16dd2036db83.png)
Working as intended here, are you sure that you don't have any plugins on the proxy that might be playing with the response?

**Comment by KarlOfDuty** [comment]
Will check during tomorrow's maintenance but I'm pretty sure we ran without plugins for a while.
