### ISSUE TITLE
TabComplete in 1.13 not working

### ISSUE THREAD

**Issue by Cornit** [PaperMC/Waterfall#316]
TabComplete cannot be used in 1.13 because the TabCompleteResponsePacket is only send to Players their version is older than 1.13.

**Comment by ishopify** [comment]
Noticing the same issue

**Comment by electronicboy** [comment]
This is a known bungeecord limitation, but this is a complex issue to solve, this would also ensure that the system would break the moment any mod or plugin tries to hook into the command system to provide their own parsers

The issue stems down to how the tab completion in 1.13 works, relying on commands being sent to the client as opposed to just fishing for results from the server with the tab completion request packet, now the client needs to know about beforehand, which would mean that we'd need to parse the command tree, save a copy of it (per player), add our commands to it, and then send it

The command system really isn't designed for a proxy to be smack bang in the middle, and if we do take this on, we'd need to ensure that the system works as intended and provide relevant API for plugins to be able to interact with this, at bare minimum we'd need to provide a way for people to register parsers

**Comment by electronicboy** [comment]
Resolved upstream, you can enable the "hack" using inject_commands in config.yml
