### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException

### ISSUE THREAD

**Issue by sebastnalmiron** [PaperMC/Waterfall#317]
Hey! I am using latest Waterfall and PaperSpigot 1.12.2 builds from papermc.io/downloads . I am having troubles in that specific server, so, when I do "/ + TAB" or some command and doing TAB, It kicks me with the default message "[Proxy] Lost connection to server"

On the Paper server doesn't display any errors, on the Waterfall appears this: https://hastebin.com/seqarikaro.m

On other servers I don't have problems because I am using Paper 1.11.2.

Need a way how to fix this asap! :(

**Comment by Janmm14** [comment]
Please don't use hastebin, the service has been instable for me at least a year and your paste is not loading for me.

**Comment by electronicboy** [comment]
As above, the paste isn't loading for me either, hastebin also retains information for a short time, hindering should we ever wish to go back and see a report

As for the issue itself, this always boils down to a plugin on the server modifying packets improperly, while the client is a bit more happy to deal with them, the proxy isn't
