### ISSUE TITLE
Centos OpenSSL problem.

### ISSUE THREAD

**Issue by camdenorrb** [PaperMC/Waterfall#32]
`20:46:43 [INFO] Could not load native library: /tmp/bungeecord-native-cipher810503535089700859.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
20:46:43 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.`

`[root@bungeeberry Bungee]# yum install openssl-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
- base: less.cogeco.net
- extras: centos.mirror.rafal.ca
- rpmforge: mirror.team-cymru.org
- updates: less.cogeco.net
  Package 1:openssl-devel-1.0.1e-51.el7_2.5.x86_64 already installed and latest version
  Nothing to do`

**Comment by minecrafter** [comment]
Please switch to a less crappy distribution, in this case Debian or Ubuntu

**Comment by sgdc3** [comment]
Centos is crappy? sure! xD

**Comment by camdenorrb** [comment]
IKR!

**Comment by sgdc3** [comment]
@camdenorrb You can fix this if you compile waterfall on CentOs.

**Comment by camdenorrb** [comment]
I actually tried that but I can't seem to get it to work, I was able to compile bungeecord with no problems.

**Comment by sgdc3** [comment]
Requirements: Oracle JDK 8 or OpenJDK-devel 8

How to install OpenJDK-devel 8

`sudo yum install java-1.8.0-openjdk-headless.x86_64 java-1.8.0-openjdk-devel.x86_64 -y`

How to compile Waterfall:

```
sudo yum install maven git -y
git clone https://github.com/WaterfallMC/Waterfall
cd Waterfall
git submodule update --init
./applyPatches.sh
cd Waterfall-Proxy
cd native
./compile-native.sh
cd ..
mvn clean package -B
```

Edit: thanks to @kamcio96 for some corrections

**Comment by kamcio96** [comment]
`cd Waterfall-Proxy` before mvn

**Comment by camdenorrb** [comment]
I will try that tomorrow :) thanks for your help

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by kamcio96** [comment]
Try also compile native code

**Comment by camdenorrb** [comment]
Erm, how would I go about compiling the native code?

**Comment by kamcio96** [comment]
```
cd Waterfall-Proxy
cd native
./compile-native.sh
```

**Comment by camdenorrb** [comment]
Will do ^-^

**Comment by Techcable** [comment]
Yeah, this is an OpenSSL/CentOS problem.
Basically because of how native code works and how OpenSSL is coded when OpenSSL versions change native code breaks.
CentOS uses and old version of OpenSSL that doesn't work with the native code we distribute.

**Comment by sgdc3** [comment]
@Techcable why is openssl required? I'm just curious ;)

**Comment by kamcio96** [comment]
It's faster native library. Without it proxy will call Java code, which is a little slower

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by camdenorrb** [comment]
Just to note,You have to do
git submodule update --init 
before applying patches

And it works ^-^ Thank you guys so much :3

**Comment by sgdc3** [comment]
Yeah forgot about that ;)
