### ISSUE TITLE
Custom game version

### ISSUE THREAD

**Issue by melinstagibson** [PaperMC/Waterfall#322]
Since waterfall has an option to set a custom game version would it be possible to not put "Waterfall" in front of that even if you set it?

I understand that you would probably not want to do that due to missed exposure but it really defeats the point of the option and, in my case, ild still have to fork it either way which seems like just unnecessary since you added the option already.
Thanks for considering

**Comment by Janmm14** [comment]
Plugins can alter this I think.

**Comment by electronicboy** [comment]
There really isn't a way that we can migrate the settings without adding "yet another config option", especially for something we've been encouraging users to use plugins for instead for a long time, the version setting is there to allow server owners to avoid the blind 1.8-1.13 version

**Comment by melinstagibson** [comment]
ok, i havent found a working plugin in the 2 hours i searched for one so i just forked it and changed the patch which was easy enough.
thanks for the quick reply tho!

**Comment by x1p** [comment]
ProtocolChanger and BungeeDisplay can do this afaik
