### ISSUE TITLE
Pixelmon specific error

### ISSUE THREAD

**Issue by krisjenner** [PaperMC/Waterfall#323]
When connecting to my Pixelmon server via Waterfall proxy - I get stuck at "Waiting..." while battling wild pokemon and the only way to exit out is the /endbattle command via console. There are similar issues on BungeeCord github but idk if it has since been fixed.

**Comment by krisjenner** [comment]
[issue](https://github.com/SpigotMC/BungeeCord/issues/1919)
[issue](https://github.com/SpigotMC/BungeeCord/issues/2069)

**Comment by electronicboy** [comment]
There are people running pixelmon fine behind waterfall, it really seems to boil down to the version of the mod you're using, to my understanding support for bungee is one of those things which has been fixed and broken on their end multiple times

**Comment by krisjenner** [comment]
i forgot to disable online mode in config.yml on the Waterfall server. Set to false and now works fine

**Comment by electronicboy** [comment]
That would suggest a UUID mismatch between the client and the backend server, which would need to be fixed by either offline mode, or by forwarding the users data to the server, I'm not sure of what your options are outside of sponges bungeecord support are for forge
