### ISSUE TITLE
Random disconnections - Waterfall seems to restart/crash?

### ISSUE THREAD

**Issue by krisjenner** [PaperMC/Waterfall#324]
here is my[ log ](https://pastebin.com/TkWPVkdL) - I'm using the following plugins: SpongePls, CommandControl, BungeePlayerCount and RedirectPlus. Online mode true in Waterfall config and false on all servers.

It just seems we get disconnected after a certain time whether it gives a "timeout" error or just "disconnected" this happens to all users on the proxy simultaneously

**Comment by electronicboy** [comment]
Outside of a native crash (check for a hs_err file in the folder you run waterfall from), if a crash was to occur, we'd expect information about the crash to be in the log file, which there isn't

Waterfall can't restart itself, if the proxy does actually restart, I would suggest checking your hosting setup for issues, as this would mean that you've got something that's intentionally restarting the proxy, or the proxy is being restarted by something after a crash, I'd suggest also checking the console output for any unlogged errors (such as those triggered by the JVM)

**Comment by krisjenner** [comment]
was on the hosting providers side. not Waterfall
