### ISSUE TITLE
Red X on server Ping

### ISSUE THREAD

**Issue by DanBTechnology** [PaperMC/Waterfall#328]
When I try to ping the server running Waterfall, I can connect to it, but it shows a red X near the motd and says that the server is outdated... Is there any way to fix this? Thanks

Screenshot: 

https://imgur.com/a/VrnuwVJ

**Comment by DanBTechnology** [comment]
Update: Fixed screenshot link; sorry about that

**Comment by Black-Hole** [comment]
Please try to reproduce without plugins like ViaVersion or ProtocolSupport.

**Comment by mikroskeem** [comment]
![](https://0x0.st/skHP.png)

Assuming you use ServerListPlus, then this feature (showing text on the left side of server entries in Multiplayer list, or "custom player slots format") is known to do this.

**Comment by electronicboy** [comment]
Basically, what @mikroskeem said, the plugin sends the wrong protocol version back so that the client will show the version information, which is how they're showing the text there.
