### ISSUE TITLE
Empty Packet when player tab-completing

### ISSUE THREAD

**Issue by CryLegende** [PaperMC/Waterfall#335]
Hello, I have a problem on my server
Error: https://pastebin.com/raw/pXMpQ5V8
Waterfall: git:Waterfall-Bootstrap:1.13-SNAPSHOT:67734af:240 by md_5
Server: PaperSpigot 1.12.2 (#1594)

Waterfall + PaperSpigot = The error appears when a player Tab-completing a command, the player is kick
Bungeecord + PaperSpigot = The error appears at the connection and the player is kick
PaperSpigot alone = No Error
Waterfall + Spigot = No error

The error probably comes from PaperSpigot but the error occurs on the proxy
(also appears when the allow_empty_packets option is set to "true" in waterfall.yml)

Thanks for your help, I will also post this message on the github of PaperSpigot

**Comment by mikroskeem** [comment]
Can you provide list of plugins on Paper server?

**Comment by Remski01** [comment]
PaperSpigot... its PaperMC

**Comment by CryLegende** [comment]
omg I found where the bug came from: ProtocolSupportPotions
