### ISSUE TITLE
Error Creating 1gb File core.987

### ISSUE THREAD

**Issue by JH3Y50N** [PaperMC/Waterfall#336]
waterfall creating 1gb+ file
I do not know when and how it happens, it's happened before and i deleted the files is happening always

Print: http://prntscr.com/m0fy1n

**Comment by electronicboy** [comment]
based upon the name, I'd guess it's a coredump; Either something intentionally created a dump, or the JVM crashed; In the case of the latter, we'd need to see the console output from the JVM crash

**Comment by JH3Y50N** [comment]
> based upon the name, I'd guess it's a coredump; Either something intentionally created a dump, or the JVM crashed; In the case of the latter, we'd need to see the console output from the JVM crash

there was no crash, the server not crashed

**Comment by Janmm14** [comment]
waterfall does not create such a file on its own. either is a plugin or a dump from the jvm

**Comment by JH3Y50N** [comment]
> waterfall does not create such a file on its own. either is a plugin or a dump from the jvm

it was not any of my plugins that created this file

**Comment by electronicboy** [comment]
If the proxy didn't crash, it means that the file was not by the JVM on existing, waterfall itself cannot produce such files, something running on the machine/somebody with access to your system created it

**Comment by JH3Y50N** [comment]
> If the proxy didn't crash, it means that the file was not by the JVM on existing, waterfall itself cannot produce such files, something running on the machine/somebody with access to your system created it

only i have access to the system and there is nothing else creating the file

**Comment by MarkTwoFive** [comment]
I would recommend deleting the file, tracking when it's recreated and seeing what your server was doing when that file was created.
Especially checking any logs you have access to.

**Comment by mikroskeem** [comment]
> there was no crash, the server not crashed

Press X to doubt. How did you check?

> only i have access to the system and there is nothing else creating the file

Coredump is generally created when process exits with signal 11, in other words gets killed with SIGSEGV signal. Processes getting killed in such way usually end up logged into kernel message buffer (see `dmesg` command) on certain system configurations (on my systems atleast) - I am not sure about others but for example on Ubuntu they end up in `/var/log/kern.log`.

Java exits in such cases with hs_err_pid_<number>.log and generally with a coredump file - which size is about the memory size that java process used. You have coredump file with huge size (which I expect to be smaller than your `-Xmx` flag, but can be tad larger than it in certain cases) but no java crash log, which is quite interesting.

This is definitely the result of java process crashing for some unknown reason. Keep your eye on console and memory(or whatever resource limits).

Can you send that coredump file next time? Don't forget to compress it with 7z (definitely 7z or xz), much of the coredump size can be cut down using archiving programs.

**Comment by JH3Y50N** [comment]
Ok, when he creates i will to send
