### ISSUE TITLE
Error when joining a sub server

### ISSUE THREAD

**Issue by tomkeuper** [PaperMC/Waterfall#337]
When I try to join my skyblock server when I am not in 1.8.8 or 1.8.9 it kickes me and sends me to the lobby again. I have ViaVersion installed (1.6.0) (kick message: The server you previously were on went down) It gives this error in the waterfall console: http://prntscr.com/m0tuxr And this one in the skyblock servers console http://prntscr.com/m0ty62
I dont know what is causing this issue because I have a bedwars server running the same version of spigot that works fine.

Thanks,
Tom Keuper

**Comment by electronicboy** [comment]
Your server sent a packet without any contents, more than likely down to a bad plugin on the server itself.
