### ISSUE TITLE
[Feature Request] Add API which allows adding forced hosts

### ISSUE THREAD

**Issue by Sir-Will** [PaperMC/Waterfall#342]
hey,

currently it is possible to add new servers while bungee is running via a plugin but there doesn't seem to be a way to add new forced hosts.

Any chance this can be added to Waterfall and Travertine?

**Comment by MarkTwoFive** [comment]
Wouldn't this be better placed at BungeeCords repo?  
Not that I don't like the idea, I'm just thinking out loud.

**Comment by aikar** [comment]
If you want to try that, go for it. But upstreams for Paper projects aren't the most friendly to get ideas into, so we recommend filing them to us and we will act on them to our own judgement.

**Comment by mikroskeem** [comment]
>Wouldn't this be better placed at BungeeCords repo?
>Not that I don't like the idea, I'm just thinking out loud.

I mean theoretically.... everything could go into upstream but as you can see this fork does not exist without a reason? :smile:

**Comment by MarkTwoFive** [comment]
Fair enough. ^^  
But I think there's no harm in trying.

**Comment by electronicboy** [comment]
This is stored in a map on ListenerInfo and should be exposed there already

**Comment by Sir-Will** [comment]
How would I access that? I did only find api method which gets it from the config.

**Comment by electronicboy** [comment]
Which is the same place that bungee reads it from for everything else, basically; You'd just need to modify the contents of that

**Comment by Sir-Will** [comment]
This is what I tried without success:
```java
ListenerInfo listenerInfo = ProxyServer.getInstance().getConfigurationAdapter().getListeners().iterator().next();
listenerInfo.getForcedHosts().put("dev.mym.li", "test");
```

**Comment by electronicboy** [comment]
You want to use getConfig on ProxyServer, going through the config adaptor means that you're just going to pull a brand new list of listeners (which aren't going to be used)

**Comment by Sir-Will** [comment]
Oh okay. That works, thanks!
