### ISSUE TITLE
getModList empty on paper server

### ISSUE THREAD

**Issue by Sir-Will** [PaperMC/Waterfall#344]
hey,

I wanted to use the `getModList` method but found out that it is empty when connecting to a paper server. For forge server it seems to work fine.

Is there any way to get this working for paper spigot?

**Comment by electronicboy** [comment]
You would need to simulate a FML handshake to make the forge client disclose that information so that waterfall can actually capture it

https://wiki.vg/Minecraft_Forge_Handshake#Forge_handshake
