### ISSUE TITLE
So i ran this server with waterfall and it keeps kicking players from the server to the hub every 10 - 20 minutes

### ISSUE THREAD

**Issue by D4rkHelix** [PaperMC/Waterfall#347]
this keeps happening every 10 minutes is there a reason why this happens also can it be fixed. like people will be on ozone 3 and then 10-20 minutes later they are kicked to the hub what causes this issue and is there a solution?
[15:12:36] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: BebySenost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer this is the error that keeps coming up. how does one fix this? its essentially resetting the connection every 10-20 minutes is this a known issue and is there a solution?

**Comment by 123Kappa** [comment]
Having the same issue :/

**Comment by Spontini** [comment]
same here

**Comment by Janmm14** [comment]
What do ~~bungee~~ waterfall logs say?

**Comment by 123Kappa** [comment]
It says just what the d4rkHelix dude posted

**Comment by 123Kappa** [comment]
Could it be ping_passthrough config? I have it as false

**Comment by electronicboy** [comment]
All we can know from what you've provided is that the connection was improperly closed by something upstream, bungeecord will be logging at least something when they're disconnected

**Comment by 123Kappa** [comment]
https://pastebin.com/bzGNS82J
Here sorry for some reason I didnt see the giant log

**Comment by electronicboy** [comment]
This is an issue with mods installed on your server: https://github.com/Lunatrius/InGame-Info-XML/issues/72

**Comment by 123Kappa** [comment]
Thank you a lot, such an annoying issue <3

**Comment by D4rkHelix** [comment]
Erm so its still not fixed from removing that https://paste.feed-the-beast.com/view/f3b5c6b2 here is the error full error its to do with waterfall can u please have a second opinion towards it?
