### ISSUE TITLE
Server change bug

### ISSUE THREAD

**Issue by johnbli** [PaperMC/Waterfall#353]
I have only one more problem, if you switch between the servers, you have to press Escape because otherwise landscape is left standing.

In the log I have no mistake.

You can test it with the modpack saemix modded citybuild at twitch where the pack also contains the address to my server.

modpack adress is.: https://minecraft.curseforge.com/projects/saemix-modded-citybuild

**Comment by electronicboy** [comment]
Seems like there is no real interest in this issue, pressing escape has 0 bearing on the proxy itself and suggests that some mod really doesn't like server transfers, there are some things in the proxy these days which can help but chasing down edge case issues with 200 in 1 mod packs is not something I can commit to
