### ISSUE TITLE
Server offline

### ISSUE THREAD

**Issue by LoXR** [PaperMC/Waterfall#356]
Basically the server appears offline on voting sites aswell as https://mcapi.us in the latest builds. The only working version it seems is Build: 254

**Comment by electronicboy** [comment]
Did you enable the query protocol? are there any messages in the logs, etc?

**Comment by electronicboy** [comment]
Turns out it doesn't use the query protocol, it uses the status protocol; Working perfectly fine here, however

```
$ curl https://mcapi.us/server/status\?ip\=0.tcp.ngrok.io\&port\=17849
{"status":"success","online":false,"motd":"","error":"","players":{"max":0,"now":0},"server":{"name":"","protocol":0},"last_online":"","last_updated":"1551806635","duration":245585213}%
```

**Comment by LoXR** [comment]
So although the older Waterfall builds will show online, I just have to stay on build 254? While even the newest dev build that came out didnt fix it.

**Comment by electronicboy** [comment]
I misread the response from their API, for some "sane" reason it seems that success is probably just always true with their system... I can replicate this on bungee and waterfall, for some reason the protocol ID we're getting seems incorrect

**Comment by Aurelien30000** [comment]
I can confirm this problem with Query connexion. If you need more details, ask me ^^.
