### ISSUE TITLE
allow_empty_packets not used

### ISSUE THREAD

**Issue by antbig** [PaperMC/Waterfall#357]
Hello,
the waterfall option to allow empty packets is not correctly implemented:
![image](https://user-images.githubusercontent.com/1473896/53876855-020f8b80-4008-11e9-9eba-572277f1a0c8.png)
This is located in the patch 0045-Add-Configuration-to-allow-empty-packets.patch in the class WaterfallConfiguration

**Comment by electronicboy** [comment]
In my defense, https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0045-Add-Configuration-to-allow-empty-packets.patch#L9
