### ISSUE TITLE
Inject_commands

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#358]
Latest BungeeCord/WF misses the inject_commands option. This was removed in upstream.

Could it be added by WF as an option to turn off the auto tab completion completely?
Or better yet: is it possible to selectively disable some tab completions? There are spigot plugins which can do this, but there is no plugin yet which can do this on bungee.

**Comment by Artuto** [comment]
I think this is now default behavior https://github.com/SpigotMC/BungeeCord/commit/0d6f3ee3745a9d551c90ca654e0092b6f173ce0c

**Comment by Janmm14** [comment]
There are plugins that can block tab complete on bungee level. Look for bungeecord command blockers.
Suggesting to try out https://www.spigotmc.org/resources/command-blocker-ultimate.296/ its from someone I know and open source

**Comment by x1p** [comment]
Good suggestion. Tried it right away. Sadly, it doesn't worked for me.

**Comment by ArtNRG** [comment]
Tried this bungee plugin: https://www.spigotmc.org/resources/abps-%C2%BB-antibungeepluginsteal-first-bungeecord-plugin-blocking-tab-in-commands-3-000-downloads.31951/
It can't block those suggestions too.

**Comment by MrIvanPlays** [comment]
@x1p md_5 removed it because it got "out of the furnace". This was a beta feature in BungeeCord and now it made up "out the furnace". Disabling can only be established via permissions in the plugins. Why they should get it back?

**Comment by electronicboy** [comment]
I decided to go for an event, being that it provided control for developers and server owners, especially when the server provides an event for this, why not bungee too?

This event is really not the ideal solution, the proper fix should be that developers implement their commands and provide a permission/override hasPermission to implement the relevant checks

Plugin created while playing with this is available here: https://papermc.io/forums/t/completions-control/617

**Comment by x1p** [comment]
@MrIvanPlays Let me explain why: I'm already busy for 2 months (!) now to have Litebans respect permissions and fix this.
