### ISSUE TITLE
Unknown meta type 14

### ISSUE THREAD

**Issue by FStjerne** [PaperMC/Waterfall#361]
Getting an issue with PO3 running on latest Waterfall build

I saw it posted previously on https://github.com/PaperMC/Waterfall/issues/136

I tried both true and false for disable_entity_metadata_rewrite in waterfall.yml

Pastebin of error https://pastebin.com/sNgqmif0

**Comment by electronicboy** [comment]
disable_entity_metadata_rewrite is false there or something else is messing around with the proxy, when entity metadata rewrite is disabled, we use a dummy rewriter to save on patch changes and compatibility, worth noting that you *cannot* greload this setting due to the changes it makes

**Comment by FStjerne** [comment]
We don't really use the reload commands at all. Restarting every time. What could mess with the proxy? Running almost default setup aside from fallback server having some restrictions lifted to allow modded clients.

**Comment by electronicboy** [comment]
My best guess is that you didn't save the configuration file or something, The only way a plugin could break that would be if something was installed on the proxy that was messing with user connections

**Comment by FStjerne** [comment]
Such as ViaVersion or VersionConnector?

disable_entity_metadata_rewrite is set to true

**Comment by electronicboy** [comment]
If they're overriding the UserConnection object, yes

Had a quick word with the ViaVersion guys and apparently, they don't do anything that would break that, mind seeing if you can work out if it is a plugin, and if so which one?

I was originally going to implement this in a way that would survive plugins messing with internals, but didn't like the way that needed to be done, I guess I look into that

**Comment by FStjerne** [comment]
VersionConnector isn't open source so might be difficult to work out, but I'll disable that to see if it fixes anything.

**Comment by FStjerne** [comment]
Still occurs. I can't see any other plugins that would have any say in connections.

**Comment by creeper123123321** [comment]
Are you using 1.13?

**Comment by FStjerne** [comment]
The fallback server is.

**Comment by electronicboy** [comment]
Looks like BungeeCord isn't handling metadata types for 1.13+ properly, ViaVersion seems to be potentially acting as a trigger for it (However, as a note, ViaVersion is technically doing nothing wrong here)

**Comment by FStjerne** [comment]
Okay, thank you for the quick response. What's the solution?

**Comment by julianubico** [comment]
> Okay, thank you for the quick response. What's the solution?

Try setting these 2 options to false in `astralsorcery.cfg` for your Project Ozone 3 server.
```
    shooting_stars {
        # Set to true to make shooting stars do a little explosion where they land [default: true]
        B:doExplosion=false  <- set this to false

        # Set to false to disable shooting stars from spawning [default: true]
        B:enabled=false <- set this to false
    }
```

**Comment by electronicboy** [comment]
Was working on other stuff and this ticket fell onto a backburner, looking at it, I was wrong about the 1.13+ stuff, Bungee handles it properly, however there was still the concerns that the metadata setting wasn't working as expected due to plugins installed on the proxy, which I should push up a change to improve sometime soon

**Comment by FStjerne** [comment]
> > Okay, thank you for the quick response. What's the solution?
> 
> Try setting these 2 options to false in `astralsorcery.cfg` for your Project Ozone 3 server.
> 
> ```
>     shooting_stars {
>         # Set to true to make shooting stars do a little explosion where they land [default: true]
>         B:doExplosion=false  <- set this to false
> 
>         # Set to false to disable shooting stars from spawning [default: true]
>         B:enabled=false <- set this to false
>     }
> ```

That did it. Thank you

**Comment by Phoenix616** [comment]
> VersionConnector isn't open source

This one https://github.com/Phoenix616/VersionConnector? :thinking:
