### ISSUE TITLE
Allow overriding Waterfall-specific configuration via custom ConfigurationAdapter/improving proxy specific ConfigurationAdapter API

### ISSUE THREAD

**Issue by mikroskeem** [PaperMC/Waterfall#364]
BungeeCord provides this option by in API, yet Waterfall simply hardcodes this to `waterfall.yml` and that's it.

How about improving the situation and providing a way to set the configuration adapter for Waterfall specific configuration via API?

I'm currently thinking about 3 possible solutions, with pros and cons brought out:
1) Actually not exposing a separate way to set configuration adapters and prefix Waterfall-specific stuff with `waterfall_` or something
	* Pros:
        - No need to change the API
    * Cons:
        - Annoying to use
        - Does not scale well (Waterfall forks?)
2) Add separate getter/setter for Waterfall config
    * Pros:
        - Convenient to use
    * Cons:
        - Does not scale well (see above)
3) Improve ConfigurationAdapter getter/setter by deprecating current methods and add ones which take an enum value parameter - [I have made some progress here](https://github.com/mikroskeem/Waterfall/commit/3318e15d8028d10cfb80e12cbff528ff72834b4c)
    * Pros:
        - Different proxy implementation specific configurations can be accessed via enum value parameter
        - Convenient to use
        - Scales well (e.g forks can add their configuration adapters into API with a single line of change)
    * Cons:
        - Deprecates current API

Ideas? Questions? Feedback?

I prefer either second or third option personally, if that matters.

**Comment by MrIvanPlays** [comment]
Gud.

**Comment by LogGits** [comment]
I think this would be really convenient to have. I want to change the restricted status of the server. But currently requires removing server and adding it with the new status. Something like this would allow me to simply do `server.setRestricted(true)`. 👍

**Comment by electronicboy** [comment]
There was some discussions on this on discord, the major concerns was the fact that the bungee and waterfall configurations would need to be seperated, this would likely require a delgation object to deal with both the waterfall and the bungee config without breaking other plugins

Another concern was the usage of an enum, adding API to make stuff more sane for forks and then using stuff like enums which are designed feels counterproductive to the intent here, I'd personally rather stick to seperate methods use strings as an identifier, I'm not really sure of the best "clean" route here, all options feel somewhat gross

> Something like this would allow me to simply do server.setRestricted(true). 👍

I don't see how this would change anything, beyond allowing you to return your own custom ServerInfo implementation much easier, but still offers some risks for working with other plugins given that BungeeServerInfo is immutable

**Comment by mikroskeem** [comment]
>I think this would be really convenient to have. I want to change the restricted status of the server. But currently requires removing server and adding it with the new status

That does not fall under this idea anyway. This here targets fork-specific configuration, your idea wants basically a modification of BungeeCord's API which belongs into separate issue.
