### ISSUE TITLE
Unexpected packet at player disconnecting

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#365]
Experimenting with OpenJ9 gives this when a player disconnects.
```
[22:28:53] [Netty Worker IO Thread #1/WARN]: No client connected for pending server!
[22:28:53] [Netty Worker IO Thread #1/ERROR]: [Playername|/123.123.123.123:64751] <-> ServerConnector [Test] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
0d01
```
Maybe anyone can prevent this from happening or can can give a hint what to change.

**Comment by electronicboy** [comment]
That looks like the typical "the server managed to send a bad packet" and not related to open j9?

**Comment by x1p** [comment]
Could be, but when I change to BC, it does not appear so I did not expect it to come from the paper.

**Comment by x1p** [comment]
It seems to come from somewhere from the paper server. I'll eliminate further to find out.

**Comment by minecraft7net** [comment]
> 
> 
> That looks like the typical "the server managed to send a bad packet" and not related to open j9?

i have the same errors only from lobby servers and it seems that players cannot connect to lobbies about 5-7% connections. 

i have tried upgrade my hubs from 1.8.8 paper to 1.12.2 paper - no change the same errors
also removing 90% plugins from hubs no help.

https://pastebin.com/88uXijRu

https://pastebin.com/WUpf4BPP

https://pastebin.com/gjbLfhiH

few errors when debug is enabled

**Comment by electronicboy** [comment]
Something closed the connection improperly, the flood of exceptions is likely from a plugin on your server messing around with netty and breaking the connection from being closed properly
