### ISSUE TITLE
Invalid channel names sent in minecraft:register

### ISSUE THREAD

**Issue by creeper123123321** [PaperMC/Waterfall#366]
Waterfall seems to send invalid plugin channels for 1.13+ clients when 'forge-support' is enabled, potentially causing issues with Fabric API
Reproduction:
Install ViaVersion-DEV on a Waterfall server with 'forge-support', try to enter with a client with Fabric API, get kicked https://user-images.githubusercontent.com/7974274/55688938-fbe93380-5954-11e9-8504-7290583a60a0.png

**Comment by electronicboy** [comment]
We need to look into supporting the 1.13 forge changes, however I'm not sure what the status on forges changes are and if they're finalized; I'm considering disabling forge support for 1.13+ protocols, given that it won't work here anyways as the system has changed drastically

**Comment by electronicboy** [comment]
Looking back at this, we never send this stuff unless we actually get it ourself? Guessing that this is purely a proto-hack thing and not something I'm going to invest time into unless people can reproduce without such hacks
