### ISSUE TITLE
Waterfall not connecting with external server properly

### ISSUE THREAD

**Issue by Kitsune-Ultima** [PaperMC/Waterfall#368]
Every time a player tries to connect with the waterfall proxy they connect briefly then immediately disconnect. directly connecting to the server (localhost:25565) it connects just fine, this happens even with older servers that have worked with waterfall before. 
log screenshot [http://prntscr.com/naao9x](http://prntscr.com/naao9x)

**Comment by Janmm14** [comment]
You use waterfall and mc server on the same machine?
If yes, you need to give your mc server a different port when you use waterfall, if you did not do that already.

**Comment by Kitsune-Ultima** [comment]
waterfall and the mc server are on separate machines the waterfall proxy runs under kubuntu linux, and the mc server runs under windows 10 pro (my computer) this is mostly so I can access the server files directly, as opposed to 'scp'ing (secure copy) files over to the server over ssh.

**Comment by electronicboy** [comment]
ReadTimeoutException means that a packet hasn't been sent in so long, this is configured using the timeout in config.yml, increasing that shouldn't be needed, but if it does, often suggests issues with the server or networking that cause players to take too long to join fully, see https://github.com/PaperMC/Paper/issues/895#issuecomment-372175216 for more info

**Comment by Kitsune-Ultima** [comment]
through further testing increasing the timeout to 120000 milliseconds (120 seconds/2 minutes) results in a timed out event firing on the client side as opposed to a ReadTimeoutException : null on the proxy side and a disconnected event on the client side with a timeout of 30000 milliseconds (default), right now it seems that waterfall is outright refusing to connect to the server as the two computers are on the same network, the client and server are on the same computer, connecting to the server via localhost allows login, connecting via the waterfall to the server, denies access

**Comment by electronicboy** [comment]
If waterfall was refusing the connection you'd see a different message than that, by increasing that timer so high you've allowed the client to reach its own timeout before the proxy boots it, you need to address what is taking so long for the client to join, this is generally down to plugins on the server or a slow/bad connection somewhere, I'd suggest reading the linked comment, if you require more assistance, please seen support on discord/IRC

**Comment by Kitsune-Ultima** [comment]
I assume that there is a different reason that the ServerConnector connect and disconnect have the exact same timestamp in this [screenshot](http://prntscr.com/naao9x) of the waterfall terminal then?
