### ISSUE TITLE
Some Players getting kicked back to hub randomly

### ISSUE THREAD

**Issue by 123Kappa** [PaperMC/Waterfall#369]
This is what's on console when it happens: https://pastebin.com/ZST9qg2G
I think this is a better pastebin  https://pastebin.com/4pq0drY9

I think this is the most clear one from the logs https://pastebin.com/XV62S94j

**Comment by 123Kappa** [comment]
#361 Seems to be the solution

**Comment by electronicboy** [comment]
Duplicate of #136 try using the setting in waterfall.yml to disable entity metadata rewriting
