### ISSUE TITLE
Problem with forwarding packets from Immersive Railroading mod

### ISSUE THREAD

**Issue by xNccPlay** [PaperMC/Waterfall#374]
Hey guys,

We have a server running with your waterfall fork for supporting our sponge modded server. Since we use waterfall, we can't move inside trains from the Immersive Railroading mod. I've already contacted the mod author and he said, that this is a problem on your site.
Here you have a link to the original issue form: [https://github.com/cam72cam/ImmersiveRailroading/issues/579](https://github.com/cam72cam/ImmersiveRailroading/issues/579)

If you need anymore informations about the problem just ask.

Greetings, xNccPlay

**Comment by electronicboy** [comment]
Try disabling the entity metadata rewriting in waterfall.yml

**Comment by xNccPlay** [comment]
Thanks for your quick reply, I've changed the entry but have to wait a little to restart the server. I'll give you feedback later :)

**Comment by xNccPlay** [comment]
Thank you, the fix works fine! :)
