### ISSUE TITLE
1.14

### ISSUE THREAD

**Issue by JE201506** [PaperMC/Waterfall#375]
Please add 1.14 support, the latest version "ghost" supports 1.14, you can not connect but the version list includes 1.14.

Please add this ASAP!

Thanks

**Comment by electronicboy** [comment]
I'm honestly too busy and have little interest in releasing a patch which will be removed in a few hours when bungee updates, if somebody is bored enough and wants to submit a PR, noting that it will be removed in a few hours, I'll consider it

**Comment by JE201506** [comment]
Does the latest bungeecord not support 1.14 ether then?

**Comment by JE201506** [comment]
As it looks like '#1​40​5' bungee version has support?
