### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#376]
There are messages missing in messages.properties. For example /find and /send :( Please add all messages.
https://gyazo.com/1cdf6584b9c1db8e2abb6edf18746f1c

**Comment by mikroskeem** [comment]
Honestly try bumping upstream with this

**Comment by ghost** [comment]
This would be a nice feature because there isnt really another reason to use Waterfall over Bungecord in my opinion

**Comment by MrIvanPlays** [comment]
> This would be a nice feature because there isnt really another reason to use Waterfall over Bungecord in my opinion

Waterfall does a bunch of performance improvements. Thats why you should be using it

**Comment by MrIvanPlays** [comment]
https://github.com/SpigotMC/BungeeCord/pull/2684

**Comment by MrIvanPlays** [comment]
https://github.com/SpigotMC/BungeeCord/commit/9e76966e0fc46e4bdc61cfe97f14cd8b98290d8c
@electronicboy you can close this now and merge upstream
