### ISSUE TITLE
1.14 SUPPORT NOT A WORK #279

### ISSUE THREAD

**Issue by successed** [PaperMC/Waterfall#377]
i have #279 version waterfall and this not a support 1.14 clients.

http://prntscr.com/ngsqpi

**Comment by Aurelien30000** [comment]
What is the version of your game and the version of your server where we are moved when you connect to your server ? Because Waterfall supports normally 1.14 ^^

**Comment by successed** [comment]
This not support waterfall, Check this out this bungeecord: http://prntscr.com/ngz85t

**Comment by NachtRaben** [comment]
Sep 4, 2018 is the build date of that revision. It won't support 1.14.

**Comment by electronicboy** [comment]
Cannot replicate, among with the many others using this build for 1.14

![image](https://user-images.githubusercontent.com/1228900/56779095-47169980-67d1-11e9-85e0-b6d0e941e3fd.png)


![image](https://user-images.githubusercontent.com/1228900/56779054-35cd8d00-67d1-11e9-93ee-58a37fabffb6.png)
