### ISSUE TITLE
Bug - sending all users apart from one.

### ISSUE THREAD

**Issue by Jackis18** [PaperMC/Waterfall#381]
https://pastebin.com/XatK5f3Z

Please advise :/

**Comment by electronicboy** [comment]
Looks like you're missing part of that error

**Comment by Jackis18** [comment]
Sent a complete log file in case I did miss some off, 

https://pastebin.com/4aXAA84F

**Comment by Jackis18** [comment]
07.05 14:45:31 [Server] INFO Total players online: 2
07.05 14:45:31 [Server] INFO io.netty.handler.codec.DecoderException: Error decoding packet class Team with contents:
07.05 14:45:31 [Server] INFO +-------------------------------------------------+
07.05 14:45:31 [Server] INFO |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
07.05 14:45:31 [Server] INFO +--------+-------------------------------------------------+----------------+
07.05 14:45:31 [Server] INFO |00000000| 3e 07 57 6f 6c 66 66 32 61 00 07 57 6f 6c 66 66 |>.Wolff2a..Wolff|
07.05 14:45:31 [Server] INFO |00000010| 32 61 12 c2 a7 64 4e 49 43 4b 45 44 20 c2 a7 37 |2a...dNICKED ..7|
07.05 14:45:31 [Server] INFO |00000020| 7c 20 c2 a7 64 03 c2 a7 72 00 06 41 4c 57 41 59 || ..d...r..ALWAY|
07.05 14:45:31 [Server] INFO |00000030| 53 ff                                           |S.              |
07.05 14:45:31 [Server] INFO +--------+-------------------------------------------------+----------------+
07.05 14:45:31 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:82) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]
07.05 14:45:31 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:4d24258:278]

**Comment by Jackis18** [comment]
Any updates?

**Comment by electronicboy** [comment]
Your server sent an incomplete Team packet, I would suggest trying to remove plugins on the server itself, especially those involved with scoreboards or packet-based stuff
