### ISSUE TITLE
Server can't handle more that one player

### ISSUE THREAD

**Issue by NaruseII** [PaperMC/Waterfall#383]
Hey, when two players are connected to a server, they are instantly kicked by the server with the following details:
`[/-----------|Skundeste] <-> DownstreamBridge <-> [lobby] - bad packet ID, are mods in use!? Empty minecraft packet!`
I tried resetting the configurations, connecting in vanilla, removing the plugins, even with a BungeeCord proxy: always the same problem. I had, on the other hand, more description with the bungee: 
`DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1019478, widx: 1082326, cap: 2097152)) @ io.netty.handler.codec.MessageToMessageDecoder:98`

Any idea for a solution ? :]

**Comment by mikroskeem** [comment]
Try configuring Waterfall to allow empty packets in `waterfall.yml`. iirc vanilla itself ignores empty packets, so that should be fine.

**Comment by NaruseII** [comment]
Oh yeah, it's fixed now. Thank you. :)
