### ISSUE TITLE
game_version:

### ISSUE THREAD

**Issue by madtomic** [PaperMC/Waterfall#384]
waterfall.yml

what to use to set the game version?

```java
use_netty_dns_resolver: true
disable_entity_metadata_rewrite: false
disable_modern_tab_limiter: true
log_initial_handler_connections: true
throttling:
  tab_complete: 1000
game_version: ''
allow_empty_packets: false
```

**Comment by electronicboy** [comment]
`game_version` controls the text that should be displayed from the proxy if the protocol version of the server doesn't match the clients (Allows you to say, use 1.14.1 when the proxy would just say 1.8-1.14.2)

**Comment by madtomic** [comment]
@electronicboy 
Thanks for explaining this.
