### ISSUE TITLE
Not connecting to fallback on Exception while joining

### ISSUE THREAD

**Issue by thedejavunl** [PaperMC/Waterfall#385]
Since upstream is not responding on my issue. Maybe someone can help me here.

We are using stunnel to provide secure connections between our Bungeecord and Spigot server.

When on first join the main server is down the player gets kicked with the following message:
`Connection Exception: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1`

The server is not trying to connect to the fallback server when the main server is down.
Without stunnel the server will reconnect to the fallback, but then the connections between BungeeCord and Spigot won't be encrypted and that is not what we want.

Can the code be adapted so that the server will try to connect to the fallback when this error occurs?

**Comment by electronicboy** [comment]
I've honestly never used stunnle, "Connection reset by peer" indicates that something closed the connection improperly, is there anything in the client logs or something maybe?

**Comment by thedejavunl** [comment]
It is because the connection after the stunnel is not available. (happens when the server is offline of restarting) But the connection exception is not putting the connection to the fallback.
