### ISSUE TITLE
disable_entity_metadata_rewrite not working?

### ISSUE THREAD

**Issue by NLBlacky** [PaperMC/Waterfall#387]
A few months ago we had issues with players disconnecting during the evening. This was caused by entity metadata rewriting. We've since then enabled disable_entity_metadata_rewrite in the Waterfall.yml.

Today we've started working on setting up a Direwolf20 server (version 2.5.0). During the evening everyone got disconnected due the entity metadata rewriting. We were using version 282 so I updated to 284 but the issue still kept happening. Below are the logs:

Version 282: https://pastebin.com/jDhN5CHa
Version 284: https://pastebin.com/uSwV0rN7

Our Waterfall.yml config:

> use_netty_dns_resolver: true
> disable_entity_metadata_rewrite: true
> disable_modern_tab_limiter: true
> log_initial_handler_connections: true
> throttling:
>   tab_complete: 1000
> game_version: '1.14 and below'
> allow_empty_packets: false

I'm not sure why disable_entity_metadata_rewrite stopped working or if something else is going on. This is why I made this post.

**Comment by electronicboy** [comment]
Looks like this one missed my eyes, basically, the setting works, but it seems to be pretty easy to break with some plugins, shamefully there is very little that I can do about this (without implementing 20 dozen ways for it to detect and avoid rewriting...), bungees design just really makes handling more invasive configurations a challenge around other plugins

**Comment by NLBlacky** [comment]
This work in progress server was connected to a test Waterfall instance on port 25566 while our main instance was on port 25565. It seems like multiple things including the meta rewriting didn't work as intended on servers connected to the second Waterfall instance. Option works fine on the main Waterfall server and I decided to move any test servers to the main Waterfall as well now.
