### ISSUE TITLE
deluxemenus server selector support?

### ISSUE THREAD

**Issue by compieter-gh** [PaperMC/Waterfall#389]
i have on my server deluxe menus (spigot) but it wont work with waterfall or tavertine
but it works on bungeecord

**Comment by electronicboy** [comment]
We would need more information, never touched the plugin, nor do we do anything that should impact the plugin messaging channel

**Comment by compieter-gh** [comment]
well it send a connect signal to bungeecord then connects me to the server but idk if its the plugin or the proxy

also it works on hexagon (edit)

this is in my config - '[connect] server'
[servergui.zip](https://github.com/PaperMC/Waterfall/files/3263204/servergui.zip)

**Comment by compieter-gh** [comment]
probbaly because of subservers 2 it works in a normal setup
