### ISSUE TITLE
Team Glow Colors dont work

### ISSUE THREAD

**Issue by Bennyboy1695** [PaperMC/Waterfall#390]
With the glow effect you can set it to be a certain color by being in a scoreboard team and setting that teams color to be what color you want. When this is applied to the player it should make them glow that color., but for every color it just shows white. This works on normal bungee versions but not waterfall

**Comment by mikroskeem** [comment]
Can not reproduce.

![image](https://user-images.githubusercontent.com/3490861/59245092-dcee7280-8c1f-11e9-83fb-ef80482fd4a3.png)

What plugins are you running on Waterfall?

**Comment by Bennyboy1695** [comment]
http://bit.ly/31rni6Y ServerSync just tracks some events (like chat) and send them over redis

**Comment by electronicboy** [comment]
0 further reports on this and this is all generally controlled by the client, if this is an issue one would need to provide more detailed info or reproduction info
