### ISSUE TITLE
Waterfall to Bungeecord 

### ISSUE THREAD

**Issue by lostonyx** [PaperMC/Waterfall#391]
Is it possible to IP forward the waterfall to a bungeecord?  In order to create load balancers (for example)

**Comment by mikroskeem** [comment]
Use HAProxy for load balancing, never proxy BungeeCords as you'll probably end up killing someone's kitten or burning house down with that in production.

**Comment by Janmm14** [comment]
If you don't require perfect balance, you can also use dns round-robin (set up multiple dns a records of the same subdomain, a random one will be chosen every dns request, requires short ttl)
