### ISSUE TITLE
Waterfall change my config.yml

### ISSUE THREAD

**Issue by Charismara** [PaperMC/Waterfall#392]
Hey,
i got a problem with my config.yml.
every time i start the waterfall proxy the config.yml change from [this ](https://pastebin.com/V1Qbrafr)to [this](https://pastebin.com/pCLD8Rzp).

how can i fix this?

**Comment by Black-Hole** [comment]
Why does the order of the entries matter?

**Comment by Charismara** [comment]
after the change the proxy don't start anymore. [Log](https://pastebin.com/cygT3Uh9)

**Comment by MarkTwoFive** [comment]
@Black-Hole I would assume it's not the order of the entries that keeps breaking things. I would guess that's due to the query port changing from ``25577`` to ``25566`` :thinking: .  
But in any way, an actual log file would help more than just the changes of the configuration file.

**Comment by Charismara** [comment]
Log with working config.yml: https://pastebin.com/7i2GqwwY
Log with broken config.yml: https://pastebin.com/8LYkzM5W

**Comment by electronicboy** [comment]
Changing actual configuration values is not something bungee does on its own, your configuration is also formatted improperly, incorrect tabbing etc, hence why you're getting that exception

**Comment by Charismara** [comment]
@electronicboy The problem is the valid config ([this one](https://pastebin.com/V1Qbrafr)) change itself to [this one](https://pastebin.com/pCLD8Rzp) which crashes my waterfall proxy. Is there any way to prevent that file from changing?

**Comment by electronicboy** [comment]
Waterfall itself cannot change the file like that, nor does it make any configuration changes itself, are you using some startup scripts that might be modifying the configs or something?

**Comment by Charismara** [comment]
`java -server -Xmx2048M -jar waterfall.jar nogui`
this is my full startup code

**Comment by Janmm14** [comment]
I don't know what's going on with your bungeecord. Both configs you sent are invalid.
In your original config one space at start of the line is missing in lines 4, 20, 32 and 35.
Yaml is space-sensitive.

Additionally you can safely remove the "nogui" option from your startup line, because bungeecord / waterfall does not have a gui. bukkit and spigot do not display a gui by default, the nogui option is only relevant for vanilla mc server normally.
