### ISSUE TITLE
Error dispatching event PlayerDisconnectEvent

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Waterfall#393]
I keep getting this everytime I "end" the waterfall instance.
Water - 284
LuckPerms - 4.4.26

Just recently started, no idea why it continues to happen.
https://pastebin.com/raw/YAVkALRz

**Comment by mikroskeem** [comment]
Thread pool has shut down and it won't accept any more tasks - LuckPerms seems to schedule something too late

**Comment by andrewkm** [comment]
Doesn't happen anymore.
