### ISSUE TITLE
LowMemorySet lag

### ISSUE THREAD

**Issue by MedicOP** [PaperMC/Waterfall#394]
LowMemorySet sorting causes huge lag if the set is big.

The LowMemorySet should be changed back to HashSet IMO.

![Screenshot_1](https://user-images.githubusercontent.com/18251099/59726129-b5576580-9230-11e9-954b-3d69f9eb98e9.png)

**Comment by MedicOP** [comment]
Any updates on this? 

Even if you have a million entries, assuming the overhead is as high as 64 bytes per entry (way more than it actually is), that's only 64MB of RAM.

I don't see why this change is necessary, and sorting the set each time an entry is added is horrible for performance.

**Comment by electronicboy** [comment]
This class has been primed for removal, just; Dreadful mistake of installing Catalina meant that I couldn't make the relevant changes, I'll try and get to this later *goes back to huggling mojave*

**Comment by Brokkonaut** [comment]
Doesn't the remaining part of the patch (the String.intern()) create a memory leak, because all names that have ever been added to the Team will never be removed from the memory again?

**Comment by Janmm14** [comment]
I'm sure the intern list/map is using weak references.
