### ISSUE TITLE
Crashing Bungee while join

### ISSUE THREAD

**Issue by TebosBrime** [PaperMC/Waterfall#396]
Yesterday we updated to the latest Waterfall (260 -> 284) After the connect of a player the bungee died. Maybe the following helps to find the error:

io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit
Caused by: java.lang.RuntimeException: VarInt too big

[Netty Worker IO Thread #0/ERROR]: [/*.*.*.*:46102] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 08323266bf1f2fa2abdabc4d85de54b2

**Comment by TebosBrime** [comment]
full logs for you guys: 
https://pastebin.com/raw/xJLK5vKQ
https://pastebin.com/raw/9hAHw1HW

**Comment by mikroskeem** [comment]
This error shouldn't happen under normal circumstances... does player have mods installed?

**Comment by TebosBrime** [comment]
They were spambots. I think so.
found this in log: https://pastebin.com/i3KGYeKR

and: https://pastebin.com/raw/Se8N9ze5
(the error occurs in the old versions as well)

**Comment by xxDark** [comment]
How you want this issue to be resolved? You have to do something to not allow spambotting on your proxy.

**Comment by TebosBrime** [comment]
No. You don't understand me. 
Not even the PreLoginEvent is fired. This aren´t real players. 

That must be related with some handshakes or protocol communication? How to handle this?

**Comment by mikroskeem** [comment]
That event can't be fired even if players fail to send proper packets at first place - best you can do is filter logs or simply disable exception logging in InitialHandler/where ever spam is happening.

**Comment by TebosBrime** [comment]
But the Bungee crashed. I think ignoring does not help.

**Comment by Janmm14** [comment]
> 
> 
> But the Bungee crashed. I think ignoring does not help.

Your logs do not show anything crashing.

> 
> 
> full logs for you guys:
> https://pastebin.com/raw/xJLK5vKQ
> https://pastebin.com/raw/9hAHw1HW

You write "full logs", but what you present are just single, handled exceptions or a bunch of handled errors where bungee only puts one line into the logs.

**Additionally all of your logs are _NOT_ created by bungeecord, you are using waterfall.**

**Comment by TebosBrime** [comment]
i know, i´m runnig waterfall. That's why I'm writing here.

the log simply ends: https://pastebin.com/raw/hXay6UHS 
and then the next latest.log started. (restart in the script) [[16:57:16] -> [16:57:42]]

**Comment by electronicboy** [comment]
Your log files indicate that
1) Somebody is sending invalid traffic to the server - We can't really do much about that, waterfalls one job is to accept connections and deal with them, there are plugins which will help blacklist known IPs for vpns, etc

2) Your log files are incomplete, all we can really see is that there are invalid connections and that either a plugin is taking too long to process events or the server is overloaded in general, if the box isn't overloaded and a plugin is actually taking that long to process the event, that's something that'll need to be addressed on your end
