### ISSUE TITLE
Waterfall Crashes.

### ISSUE THREAD

**Issue by xGioChR** [PaperMC/Waterfall#4]
Hello!
Today I noticed that Waterfall gives theese errors in my console:
- http://pastebin.com/50tY67Rc
- http://pastebin.com/aP5r3erx

Can someone help me?

**Comment by minecrafter** [comment]
- WaterfallMC/Waterfall-Old#74
- This error can happen to anyone who exposes a BungeeCord server publicly

**Comment by Janmm14** [comment]
@minecrafter What about the first error?
