### ISSUE TITLE
People randomly kicked - WARN]: [/IPHERE:PORT] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by TomLewis** [PaperMC/Waterfall#403]
This is getting ridiculous now, my last ticket got closed without even looking into this.
This is happening to a LOT of my users.
I have had my server for 6 years and this has just started happening out of the blue, I am the server owner and its happened to me after playing for about 60 mins in a stable internet connection, I know I haven't had this issue before, its Bungee/Waterfall issue.

Searching for the word "WARN" in my latest bungee log brings back **1152** results...  This isn't isolated, that is just from the last less than 24 hours log, A lot of them are "read timed out" for no reason at all, just bungee kicking them, how can I stop this? this is new, this didnt used to happen before.

```
[22:17:27] [Netty Worker IO Thread #4/WARN]: [/ip:port|GodsDead] -> UpstreamBridge - NativeIoException: syscall:read(..) failed: Connection reset by peer
[22:17:27] [Netty Worker IO Thread #4/INFO]: [GodsDead] disconnected with: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
[22:17:27] [Netty Worker IO Thread #4/INFO]: [/ip:port|GodsDead] -> UpstreamBridge has disconnected
[22:17:27] [Netty Worker IO Thread #4/INFO]: [/ip:port|GodsDead] <-> DownstreamBridge <-> [survival] has disconnected
```

**Comment by Black-Hole** [comment]
You have to sort this out with your hosting provider.
As with any networking program getting a "Connection reset by peer" is not something you could mitigate at the application layer.

**Comment by TomLewis** [comment]
@Black-Hole it's a Dedi box on kimsufi, how do I diagnose the issue? It's basically no support unless you tell them exactly what's wrong. I have no idea how to diagnose this. Ovh the parent company is massive, but it's not Minecraft specific.

**Comment by Black-Hole** [comment]
I don't know, but as said before Waterfall gets a message from the TCP stack of the operating system that the connection was closed remotly. And there is nothing to do about that in Waterfall.
