### ISSUE TITLE
"game_version:" not working in 289?

### ISSUE THREAD

**Issue by Cyvros** [PaperMC/Waterfall#411]
After updating to 289 waterfall seems to ignore what is set in "game_version:" and accepts all connections again.

**Comment by electronicboy** [comment]
game_version only controls what's sent to the client for the server list ping, it's part of what displays on a protocol version mismatch

**Comment by Cyvros** [comment]
beeing only to display a version at mismatch: **cloing does not solve it.**

It still not shows the entry 1.14.2 when i load the serverlist with 1.8.9 ... 
It does not show any mismatch at all in new version. it just shows as beeing able to join
so it still does not work and is an issue since last version? It worked before updating.

**Comment by electronicboy** [comment]
Configuration? screenshots?
From what I can see your issue is a misunderstanding of what that configuration does

**Comment by Cyvros** [comment]
i do not missunderstand …. it worked before …
it should show a red "1.14.2" instead of the players on the 1.8.9 client shouldn't it ?

![waterfall 1](https://user-images.githubusercontent.com/6624742/61993674-6ee6f900-b06f-11e9-9964-f6602b7c35e3.PNG)

**Comment by electronicboy** [comment]
Bungee itself doesn't know the version of the backend server, for 1.14.3 on the earlier build it would show that info, but as the newest version of waterfall supports 1.8-1.14.4, it's happy as is; Enabling ping-forwarding in config.yml will make it forward the ping to the server which will return the correct version info (But that will show ping info from the server itself)
