### ISSUE TITLE
Waterfall disconnects users from the server

### ISSUE THREAD

**Issue by TechieBlort** [PaperMC/Waterfall#412]
Provided is the error when a user is trying to join 02.08 13:13:53 [Server] WARN [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@4238b77f
02.08 13:13:53 [Server] INFO java.lang.IllegalStateException: Default server not defined
02.08 13:13:53 [Server] INFO at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at net.md_5.bungee.api.AbstractReconnectHandler.getServer(AbstractReconnectHandler.java:23) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:530) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall-290.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
02.08 13:13:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by TechieBlort** [comment]
I closed this thinking I solved it but it still is showing the error sorry about that.

**Comment by electronicboy** [comment]
Your configuration file is incorrect and likely doesn't define any priorities in the listener (outside of a plugin), I'd suggest joining discord/using the forums for support
