### ISSUE TITLE
lost connection when chat only fullwidth space

### ISSUE THREAD

**Issue by tomo1560** [PaperMC/Waterfall#413]
lost connection when chat only full-width space ("　") 
use version：waterfall#290
console log：https://pastebin.com/JZ94cpj1
image：
![2019-08-04_02-20-55](https://user-images.githubusercontent.com/12862158/62415030-971dbb80-b65e-11e9-8b45-ca477c02fbf1.gif)

**Comment by Black-Hole** [comment]
This seems to be designed this way:
https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0024-Validate-that-chat-messages-are-non-blank.patch

**Comment by electronicboy** [comment]
This is intentional, not 100% on why it was done, but there is a good chance that it was treated differently in older client versions than it is now and thus made sense to prevent other issues

**Comment by Janmm14** [comment]
Should be changed probably to only check is empty in higher client versions.
