### ISSUE TITLE
Half of Player Were Kicked

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Waterfall#415]
Half of player were kicked after the error.

Waterfall-290
PaperSpigot 1.14.4

Error log:
06.08 22:18:30 [Server] WARN No client connected for pending server!
06.08 22:18:30 [Server] INFO 0d0100
06.08 22:18:31 [Server] WARN No client connected for pending server!
06.08 22:18:31 [Server] INFO 0d0100
06.08 22:18:31 [Server] WARN No client connected for pending server!
06.08 22:18:31 [Server] INFO 0d0100

**Comment by mikroskeem** [comment]
Not enough information, please paste your logs/latest.log into gist.github.com
