### ISSUE TITLE
Skins are not showing in offline mode.

### ISSUE THREAD

**Issue by DotRacel** [PaperMC/Waterfall#416]
This is Widely known "bug" in bungeecord. The main reason is the wrong uuid of players. But I still hope you guys fix it soon, Velocity Proxy have fixed it already, so I belive there's a way to fix it.

**Comment by electronicboy** [comment]
We need more information, as this 100% works fine in a properly configured/supported environment

**Comment by DotRacel** [comment]
I'm using travetine now.
Proxy config:
```
ip_forward: true
online_mode: false
```
Spigot: 1.8.8 paperspigot.

Spigot server.properties

`online_mode: false`

Spigot spigot.yml

`bungeecord: true`

**Comment by electronicboy** [comment]
`online_mode: false` You need to have the proxy in online mode for skins, the correct UUID is handled by the proxy and sent to backend servers

**Comment by DotRacel** [comment]
I have said "Skins are not showing in offline mode." in the title and I need you guys to make skin works on offline mode. Velocity proxy have fixed this issue already.

**Comment by electronicboy** [comment]
Sorry, I didn't read the title properly, there are plugins to achieve this, but you set the proxy into offline mode and told it not to contact mojangs API, I'm not really sure why you're expecting a different behavior

**Comment by Janmm14** [comment]
SkinsRestorer for example
