### ISSUE TITLE
290th update of waterfall broke a plugin

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#417]
the 290th update of waterfall made ServerListMotdBungee plugin to stop changing motd, I thought I should report this, works perfectly on 289th

**Comment by mikroskeem** [comment]
Please provide more information, like proxy log if you can see any errors.

**Comment by electronicboy** [comment]
Waterfall made no changes that would impact motds, only internal code; if this impacted a plugin, they need to update to accommodate the changes
