### ISSUE TITLE
Random CPU Spikes and Timeout Kicks

### ISSUE THREAD

**Issue by ygtdmn** [PaperMC/Waterfall#420]
Last couple weeks has been really rough for my server because players are randomly getting kicked. First I checked every Spigot instances but there was no issue. BungeeCord is getting unresponsive for ~10 seconds and then half of the players in the server getting kicked. 

It happens almost every 5 to 15 minutes. So it's making the gameplay so painful and players stops playing the server.

I tried to profile it with YourKit. Here is a YourKit snapshot:
https://www.dropbox.com/s/sazf3tcuvu3sgin/BungeeCord-2019-08-18-2%282%29.snapshot?dl=0

It has been taken automatically before server gone unresponsive and kick players for timeout. I'm not really good at reading thread dumps, so I couldn't understand what causes the problem. I didn't change any plugin it just started to happen randomly.

**Waterfall version:**
Build #291 (git:Waterfall-Bootstrap:1.14-SNAPSHOT:a46e94c:291)

**Noteworthy Plugins:**
- AdvancedBungeeAnnouncer
- ChangeSkin
- BungeeRcon
- LiteBans
- PartyAndFriends (https://www.spigotmc.org/resources/party-and-friends-for-bungeecord.9531/)
- PlayerBalancer (https://www.spigotmc.org/resources/playerbalancer.55011/)
- ServerListPlus

I didn't change any plugin for like a year. So I don't suspect it is a plugin issue but who knows 🤷

I can provide more data if necessary. I would appreciate any help. Thanks.

**Comment by ygtdmn** [comment]
One more snapshot:
https://www.dropbox.com/s/tot2etbmdwdoh2t/BungeeCord-2019-08-18%289%29.snapshot?dl=0

Check 1h48m.

**Comment by ygtdmn** [comment]
Tried these:
- Remove ChangeSkin
- Remove PartyAndFriends
- Update ViaVersion to 2.1.3 in spigot servers.
- Downgrade Waterfall to build 276
- Moved Waterfall to another machine. 

None of these worked unfortunately.

**Comment by ygtdmn** [comment]
These might be related: #403

**Comment by Drc-DEV** [comment]
Was this solved? If so, how did you fix the problem?

If the problem is still present, can you tell us if you have the same problem with BungeeCord or just with Waterfall?

**Comment by ygtdmn** [comment]
Problem solved after I switched CentOS from Ubuntu. Problem was also exist in BungeeCord. Even with Velocity. So I don't think it's related with proxy servers now. Forgot to close the issue. Thanks for reminder.
