### ISSUE TITLE
Was running fine, then i wasnt on PC for 2 days and now the server doesnt connect

### ISSUE THREAD

**Issue by Joshbts** [PaperMC/Waterfall#421]
i get this message upon running Waterfall "main WARN Advanced terminal features are not available in this environment". The cmd window boots up fine and goes through all procedures and still says listening on x.x.x.x:25565, however i cannot connect to it no matter what i try to do. I was having issues with GTA V the other day so i contacted Rockstar Support and the guy made me change my MSCONFIG and disable a load of things, not sure if that might be the issue but i dont know how to fix this. Please help, Thankyou

**Comment by MrIvanPlays** [comment]
I cannot reproduce this. Its your issue

**Comment by Joshbts** [comment]
i even completely started a new server with a fresh download of waterfall, it has the same issue every time

**Comment by electronicboy** [comment]
We need more information beyond "doesn't work", what exactly are you seeing when you try to connect?
if you have been tweaking internal OS stuff and broke something, there really ain't much we can do there, but some level of hopeful doubt that that is relevant

**Comment by Joshbts** [comment]
Ill leave some screenshots, so the waterfall server boots up (first screenshot) and gives the message "2019-08-21 18:02:13,625 main WARN Advanced terminal features are not available in this environment". However after that, the server keeps with the startup procedure and says listening on 192.168.0.4:25565, meaning i could usually join the server.
![CMD prompt](https://user-images.githubusercontent.com/54358097/63452438-30f6ae00-c43e-11e9-9d2b-f140eacb46ce.png). When i go to join the server on MC, it gives this message (screenshot 2)
![failed to connect](https://user-images.githubusercontent.com/54358097/63452511-61d6e300-c43e-11e9-8d1b-d9726e427457.png). I am sure everything on the port forwarding and router side is fine because it was working literally two days ago, then i come back and something has gone wrong. any help is gratefully accepted.

**Comment by electronicboy** [comment]
"Connection timed out" is a generic network error and means that there was no response to the connection whatsoever

Configure the proxy to bind on 0.0.0.0 and connect on localhost, double check all IP addresses too, e.g. did your ISP change your IP
