### ISSUE TITLE
Tab completion changes + additions

### ISSUE THREAD

**Issue by Harvle** [PaperMC/Waterfall#423]
Hi, I have a couple of changes and additions that I think would benefit server owners regarding tab-completion with waterfall.

- A similar setting to default Spigot's `send-namespaced`. This would disable any of the `<plugin name>:<command>` commands listed in tab completion, and only show the `<command>` part. This could be helpful if you want to hide the plugins you're using.
- A way to hide every player's name by typing nothing and pressing tab. Currently if you run plugins such as BungeeTabListPlus, all of the "empty slots" that are taken up on the tablist by text currently show as `~BTLP Slot <number>`. An option called something like `prevent-players-in-tab` would help remedy this.
- An option similar to Paper's `suggest-player-names-when-null-tab-completions` for waterfall. It'll do exactly the same thing as it does on Paper, but just for bungee.

If any or all of these changes are possible, I feel they would be quite helpful to server owners to keep things a little more hidden and clean when it comes to tab completion.

Thanks!

**Comment by electronicboy** [comment]
These suggestions aren't applicable to the proxy;

1) Waterfall/bungee do not send namespaced commands, nor do I believe it's the proxies place to interfere with commands sent by the server itself

2) This is client sided, the completion itself is derived from the player info which is displayed in tab, only way for it to not be displayed would be for it to not have been sent to the client/removed from tab

3) This configuration option changes the response of the bukkit API to suggest player names when a plugin returns null, the proxy does not use this behavior
