### ISSUE TITLE
Waterfall screws up console.

### ISSUE THREAD

**Issue by andrewkm** [PaperMC/Waterfall#424]
Please, before I lose my mind.
Tests were done on windows machine.

Bungee is correct:

Type in "testing123":
https://i.imgur.com/EISLX56.png
And begin pinging server:
https://i.imgur.com/1uOFBCM.png (Correctly moves down)

Meanwhile on waterfall:

Type in "testing123":
https://i.imgur.com/Atjn3Uv.png
And begin pinging server:
https://i.imgur.com/VdpFKta.png

**Comment by electronicboy** [comment]
We use the same setup as paper, are you having any issues there?

**Comment by andrewkm** [comment]
What?

**Comment by andrewkm** [comment]
Paper consoles work correctly.

**Comment by drunderscore** [comment]
Believe this is simply a Windows issue. I've seen it many times when using a Window's console. Why it's different between Bungee and Waterfall, I have no idea.

**Comment by andrewkm** [comment]
Bungee, Spigot, and Paper all work fine.
It’s the recent Waterfall commit that broke it.

**Comment by MrIvanPlays** [comment]
log4j 2.12.0 or terminalconsoleappender or jline is broken on Windows 10.

**Comment by Justsnoopy30** [comment]
Can confirm, I'm on windows 10 and this started happening after updating to the latest waterfall build.

**Comment by Justsnoopy30** [comment]
Although my problem is mostly there being no colors and it says this on startup: 

> 2019-09-12 07:40:53,311 main WARN Advanced terminal features are not available in this environment

**Comment by Drc-DEV** [comment]
I'm on windows 10 and I do not experience this problem. I use cygwin and I suppose you should use that too.

**Comment by Janmm14** [comment]
cygwin is nothing anyone should have to use to run a java program

**Comment by Drc-DEV** [comment]
> 
> 
> cygwin is nothing anyone should have to use to run a java program

I thought he was using win10 to remotely connect to a linux server, nevermind

**Comment by andrewkm** [comment]
Fixed.
https://github.com/PaperMC/Waterfall/commit/cbb038fcc24320d6c25635e0e5348ccbc1b9ccf8
