### ISSUE TITLE
Mass player kicks. 

### ISSUE THREAD

**Issue by 123Kappa** [PaperMC/Waterfall#427]
Hello, i have a network tha averages 200-260 players sometimes waterfall kicks around half the players off the network. (kicks like 20% from each server). This has started happening since we added more servers to the network and we got more players. 

At first I thought it was due to the CPU's load. So i bought a new dedi and i moved my bungeecord there. Issue wasnt fixed, then i thought it was ram, from 4gb i changed it to 2gbs because i thought that it may have been too much. Then i changed it back to 4gb and then to 6gb. 

I've known other server owners that had this issue and they told me that I should use multiple waterfall setup but i have no idea how to use that. 

The are no errors in the console outside from this: 
[Player] -> UpstreamBridge - NativeIoException: syscall:read(..) failed: Connection reset by peer
 [Netty Worker IO Thread #0/INFO]: [Player] disconnected with: NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

Some players have this error and some just get "disconnected"

**Comment by electronicboy** [comment]
`Connection reset by peer` - Something external to the proxy closed the connection, this is not something we can do anything with; General advice is to check the client/server logs, something likely caused the connection to close improperly

**Comment by 123Kappa** [comment]
Across all servers at the same time?

**Comment by 123Kappa** [comment]
And i said some of them had the error 90% of them just have "disconnected". I want to send you the logs but they include IPs.

**Comment by electronicboy** [comment]
`connection reset by peer` specifically means that the remote (or something upstream from us) reset the connection, proxy logs are irrelevant here as they'll just be saying that something on the network closed the connection

**Comment by 123Kappa** [comment]
Can I message on your discord, I want you to see the logs, I need assistance from someone who really understands bungee. 

I can pay you for your time.

**Comment by 123Kappa** [comment]
Ok i guess not, i have another question though, if it's a ram or cpu issue would i get an error?

**Comment by 123Kappa** [comment]
How do i locate what's causing this issue?
