### ISSUE TITLE
 Repeatedly dropped or  TAB cannot be used

### ISSUE THREAD

**Issue by huangsijun17** [PaperMC/Waterfall#428]
if _disable_entity_metadata_rewrite_ in _waterfall.yml_ set **true** , then my Tab plugins doesn't work.
if _disable_entity_metadata_rewrite_ in _waterfall.yml_ set **fales** , then Some of my servers will be unconnected from time to time.
`encountered exception
java.lang.IllegalArgumentException: Unknown meta type 14: Using mods? refer to disable_entity_metadata_rewrite in waterfall.yml`

Both SkyFactory4 with Mohist and EnigTech with Catserver.

**Comment by Janmm14** [comment]
What do you mean with "Tap" plugins?
Tab?

That sounds weird to me.

**Comment by huangsijun17** [comment]
> What do you mean with "Tap" plugins?
> Tab?
> 
> That sounds weird to me.

BungeeTabListPlus

tab...

**Comment by huangsijun17** [comment]
![TAB](https://github.com/huangsijun17/Picture-links/raw/master/2019-10-4-001.PNG)

The players should be inside Server EnigTech but now in the upper left corner.

**Comment by KillerJWB86** [comment]
I have the same problem on my server.It only happens once you change servers.It starts off looking fine in the lobby.
https://cdn.discordapp.com/attachments/641968803508518913/644205135756656701/unknown.png

**Comment by huangsijun17** [comment]
> 我的服务器上也有同样的问题，只有在更换服务器后才会发生，开始时在大厅看起来还不错。
> https://cdn.discordapp.com/attachments/641968803508518913/644205135756656701/unknown.png


 I am the same.

**Comment by electronicboy** [comment]
You *must* disable entity metadata rewriting (There is no way to work around this without modifying the proxy to be able to work directly with your mods entity metadata somehow), tab plugins breaking is a side-effect that needs to be looked into when I'm not ill
