### ISSUE TITLE
Plugins that use MySQL take a while to load and some fail loading out right

### ISSUE THREAD

**Issue by johncsuti** [PaperMC/Waterfall#435]
Title says it all i have a link to the full startup log so you can see luck perms complain about it as well as lite bans both of them use MySQL for database storage.

https://pastebin.com/GuLLYwd6

**Comment by johncsuti** [comment]
since they are the only two plugins i use MySQL with it could be just them or it could be others i don't know and according to luck perms they think its an issue with waterfall since its both plugins and i agree with them.

**Comment by electronicboy** [comment]
Nothing to do with waterfall, waterfall only provides the mysql driver

A quick `mysql -h<host>` shows that the mysql server isn't accepting connections and is just timing them out, this is likely a misconfiguration with your network setup
