### ISSUE TITLE
Cracked Fix by online

### ISSUE THREAD

**Issue by TheMagBum** [PaperMC/Waterfall#437]
If the Server is in onlinemode, and a player joined who is cracked. Then not trigger the ProLoginEvent. Pls patch it. Not Trigger!

**Comment by electronicboy** [comment]
Wut

**Comment by mikroskeem** [comment]
There is no such event as ProLoginEvent, but there is PreLoginEvent.

Either way, [PreLoginEvent should fire regardless of the online mode option](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L339-L398).

![stole this image from Velocity Discord](https://media.discordapp.net/attachments/472485684473626625/655869139189104650/unknown.png)

So perhaps you forgot to register the listener?

**Comment by TheMagBum** [comment]
how can I make sure that my code is not executed with cracked players? But I can't use any other event either. Because then it would be too late for ban

**Comment by Janmm14** [comment]
> 
> 
> how can I make sure that my code is not executed with cracked players? But I can't use any other event either. Because then it would be too late for ban

Use LoginEvent - its called when the server recieved and validated EncryptionResponse

Maybe you also want to tell us what you *actually* want to achieve.

**Comment by electronicboy** [comment]
Not an issue, The event is a *Pre* login event, fired before the server attempts to handle authentication against mojang.
