### ISSUE TITLE
Error authenticating users with minecraft.net

### ISSUE THREAD

**Issue by lokka30** [PaperMC/Waterfall#440]
Hi! I've came across an issue with my Waterfall setup.
My users aren't able to connect, as they get kicked:

> Error occurred while contacting login servers, are they down?

(Nope, the login servers aren't down)

On the Lobby server, bungee-cord is true and offline-mode is false.
The lobby server runs paper-33 (latest for 1.15.1) and the Waterfall is at the latest version too.

I tried a lower version of paper, no results.
I tried reinstalling the modules, no results.

Thanks :)

**Comment by lokka30** [comment]
I removed all the modules and let Waterfall reinstall them. So far, the issue seems to be fixed. I'll keep it open in case I come across it again.

**Comment by mikroskeem** [comment]
Errors point to DNS error, check your server's DNS configuration.

**Comment by lokka30** [comment]
Haven't touched my DNS configuration. Used to host bungee instances on the machine without error. Hosted locally on windows.
I apologize for my lack of knowledge on server hosting by the way. :-)

**Comment by lokka30** [comment]
'sessionserver.mojang.com.Home' isn't a valid site, I don't think .Home is meant to be there.

**Comment by lokka30** [comment]
solved by electronicboy: 'disable the async dns feature in waterfall.yml'.
