### ISSUE TITLE
Hackers crash my server - send too many wrong packets

### ISSUE THREAD

**Issue by andris155** [PaperMC/Waterfall#441]
https://pastebin.com/XhHGux9w (Full log - 20k lines) 
10 wrong packets/sec

**Comment by electronicboy** [comment]
Issue has already been reported, please use the search function...
Also, update; Some level of mitigation was added last night.

**Comment by andris155** [comment]
@electronicboy thanks, this fixed the crash. But this create 100 MB log/minute. Please add option to set less character warn messages for wrong packets.

**Comment by electronicboy** [comment]
Reducing the amount of logging ain't going to fix that much, it's basically on your side to mitigate these connection attempts, e.g. configuring fail2ban or using a plugin which will do similar
