### ISSUE TITLE
Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by IndexOutOfMJ** [PaperMC/Waterfall#444]
Hey, 

I have following problem:
If I join my server everything is okay, but if I try to join another server that is in another version (1.15.1)
following exception occurres:

Waterdfall (latest version):

encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
1b8f017b227472616e736c617465223a

Server I will join (also latest version):
<IP> lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.NullPointerException

Thanks for your help!

**Comment by electronicboy** [comment]
The proxy didn't expect a kick packet to be sent in the login phase, fix your server

**Comment by IndexOutOfMJ** [comment]
Oh thanks. I did not expected, that it was a plugin error.
