### ISSUE TITLE
bad packet ID

### ISSUE THREAD

**Issue by Coloryr** [PaperMC/Waterfall#446]
When join server,Client will show:

> disconnected with: The server you were previously on went down, you have been connected to a fallback server

And I watch Console,it show:

> bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 79 Protocol GAME Direction TO_CLIENT 

What happen it?

**Comment by electronicboy** [comment]
Duplicate of #418

**Comment by Coloryr** [comment]
thanks
