### ISSUE TITLE
Error Decoding Packet id 26

### ISSUE THREAD

**Issue by thehollowedone** [PaperMC/Waterfall#447]
![image](https://user-images.githubusercontent.com/36892342/72895130-bed70d80-3cea-11ea-836b-afccbb8b83ee.png)
`         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 26 00 00 00 68 01 00 00 00 00 08 d8 c7 c1 1b 2e |&...h...........|
|00000010| 54 34 f4 04 66 6c 61 74 06 00 01                |T4..flat...     |
+--------+-------------------------------------------------+----------------+ @ net.md_5.bungee.protocol.MinecraftDecoder:74`

Only started after I updated waterfall.

**Comment by electronicboy** [comment]
That's not the full exception, more than likely your server also sent a bad packet, i.e. replicate without plugins
