### ISSUE TITLE
Forge Unexpected packet received error

### ISSUE THREAD

**Issue by Siriuo** [PaperMC/Waterfall#449]
Whenever trying to setup Waterfall with a forge 1.15.2 server (also tried with 1.14.4 and 1.15.1) I seem to get the below message displaying in the console and within Minecraft.

[Siriuo|/127.0.0.1:63010] <-> ServerConnector [lobby] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
1bc7017b227472616e736c617465223a

No plugins/mods on either side just fresh installations of both.

**Comment by electronicboy** [comment]
Server initiated a kick, likely as bungee doesn't support modern forge support

**Comment by tiarnia** [comment]
well why not it says it does and you can turn in forge in the config but you cant use it?

**Comment by electronicboy** [comment]
Because nobody has added support for it, and upstream (Bungee) has actually dropped maintenance for forge support
#450 PRs welcome
