### ISSUE TITLE
Allways"Timed out"

### ISSUE THREAD

**Issue by Coloryr** [PaperMC/Waterfall#452]
When join server,player can play some time,but they will kick out server,it show at log:

> [23:15:14 INFO]: [Color_yr] disconnected with: Timed out 

I try join Server many times,but it allways show this.
It some bugs?

**Comment by electronicboy** [comment]
> Timed out

That means that a packet wasn't received in so long, generally more networking/plugin issues.

**Comment by Coloryr** [comment]
but if i use vanilla client,is also show this.
no any BC plugin install

**Comment by electronicboy** [comment]
Never said anything about your client. This issue tracker is for reporting issues with waterfall, if you require support, please use the forums/irc/discord, however, we can't do much to debug these types of issues for you
