### ISSUE TITLE
View Bug with BungeeTableListPlus

### ISSUE THREAD

**Issue by williambacteria** [PaperMC/Waterfall#453]
I used the latest Waterfall,and the latest BungeeTablistPlus.
The bug is When player change server and player's name will move to top left or bottom right.
This bug only occur on Waterfall, BungeeCord runs well.
![tablelistbug](https://user-images.githubusercontent.com/25552054/73203903-f1fd1f00-4178-11ea-92e9-84b88097f2c2.png)

**Comment by electronicboy** [comment]
re-enable metadata rewriting in waterfall.yml.

**Comment by williambacteria** [comment]
I love u
