### ISSUE TITLE
GReload not removing servers from config

### ISSUE THREAD

**Issue by LoXR** [PaperMC/Waterfall#454]
Something for the issue tracker to be worked on down the track, where you could add servers in the config and /greload no worries. Trying to remove a server would have the server remain in /server.

Using latest Waterfall #318 
Tested with and without plugins on Proxy.

**Comment by Janmm14** [comment]
This is intended by upstream (bungeecord) because what to do when people are still connected or currently connecting to the server in question of removal?

**Comment by Chew** [comment]
/greload is also not supported. I believe you can simply restrict the server and reload then send everyone on there back to lobby, or shut down the server.
