### ISSUE TITLE
Increased average player latency

### ISSUE THREAD

**Issue by lucaazalim** [PaperMC/Waterfall#457]
I have updated Waterfall to the lastest commit yesterday, and today my average player latency graph shows constant ping increase and a lot of random spikes.

![image](https://user-images.githubusercontent.com/10585881/74886949-45b5ef00-5358-11ea-97b7-40be31c3b61b.png)

My plugin calculates the ping average based on `ProxiedPlayer::getPing` to generate this graph. It is affecting my three Waterfall instances. I have about 600 players on each one of them.

Is there anyone being affected by the same or similar problem? I was not able to identify any commits that could have caused this.

**Comment by mikroskeem** [comment]
From what commit did you update? There haven't been any significant commits related to networking recently either, so perhaps something still on your end?

**Comment by lucaazalim** [comment]
This is the commit we have updated to: https://github.com/PaperMC/Waterfall/commit/e9ad343d5e878e8eba5610c970180cf155e4e14b

I'm going to deploy an instance with the old Waterfall version to make some tests today. I'll send the results here.

**Comment by mikroskeem** [comment]
Let me reword my question... what commit did you use before?

**Comment by lucaazalim** [comment]
This is the ccommit we updated from: https://github.com/PaperMC/Waterfall/commit/6456426ebdf5c4ad3b32a8954607892e70139e63

**Comment by mikroskeem** [comment]
Maybe https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7 could be the culprit?

**Comment by lucaazalim** [comment]
> Maybe SpigotMC/BungeeCord@eeb3747 could be the culprit?

Maybe. Probably yes.

**Testing results:**

- proxy-1 and proxy-2 are running https://github.com/PaperMC/Waterfall/commit/e9ad343d5e878e8eba5610c970180cf155e4e14b
- proxy-3 is running https://github.com/PaperMC/Waterfall/commit/6456426ebdf5c4ad3b32a8954607892e70139e63

![image](https://user-images.githubusercontent.com/10585881/74946288-d1229500-53d7-11ea-916d-6ff817184552.png)
![image](https://user-images.githubusercontent.com/10585881/74946218-bbad6b00-53d7-11ea-9cd5-6946c59a2e64.png)
![image](https://user-images.githubusercontent.com/10585881/74946261-c8ca5a00-53d7-11ea-980f-018019b95f2b.png)

**Comment by mikroskeem** [comment]
Maybe you could try to revert that change to confirm that it's the issue?

**Comment by Janmm14** [comment]
Previous bungee versions would stop keepalives wrongly if they arrive after the next keepalive was already sent (by default ping 1000+). I think the added spikes could in theory be that it just got accurate now and your server sending keepalives more frequent or sth. along those lines.

**Comment by lucaazalim** [comment]
> Maybe you could try to revert that change to confirm that it's the issue?

I'm gonna do that. I'll post the results in the next hours.



> Previous bungee versions would stop keepalives wrongly if they arrive after the next keepalive was already sent (by default ping 1000+). I think the added spikes could in theory be that it just got accurate now and your server sending keepalives more frequent or sth. along those lines.

Something I noticied is that there are no players reporting lag on the proxies that are running the latest commit, even with higher latency. It doesn't seem to have affected the connection performance.

**Comment by lucaazalim** [comment]
**New testing results, as requested by @mikroskeem:**

- proxy-1 and proxy-2 are running on the latest commit (https://github.com/PaperMC/Waterfall/commit/e9ad343d5e878e8eba5610c970180cf155e4e14b).
- proxy-3 is running with the latest commit (https://github.com/PaperMC/Waterfall/commit/e9ad343d5e878e8eba5610c970180cf155e4e14b) with https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7 reverted.

(The proxy-3 spikes before 15:20 should be ignored since there were almost no players online due to a restart.)

![image](https://user-images.githubusercontent.com/10585881/74970759-b236f980-53fd-11ea-9d9a-b3c5771f8c5b.png)
![image](https://user-images.githubusercontent.com/10585881/74970774-ba8f3480-53fd-11ea-8d53-a12452b73c49.png)
![image](https://user-images.githubusercontent.com/10585881/74970787-c4189c80-53fd-11ea-859f-ec2afc0fa370.png)

**Comment by Janmm14** [comment]
Do you run any plugin on spigot/bungee sending Ping (aka Keepalive) packets? Do you run ViaVersion on Bungee or similar "heavy" stuff?

Are you able to gather data of a certain timeframe on a per-player basis and analyse that data snapshot more precisely:
To see stuff in more detail like did the average increase because all players have higher latency or because 1/6 (or so) of your players is having lagspikes (network or fps drop because of world switch or other stuff) which are longer than 1 second and therefore just not measured by bungee / not included in the measurement without that bungee fix/change regarding keepalives?

**Comment by lucaazalim** [comment]
- I don't have anything sending keepalive packets afaik.
- I do run ViaVersion on all my spigot servers.
- I noticied that sometimes the average ping is above 1.4 seconds during the spikes.

I'm gonna try to figure out a way to bring more detailed informations here. Unfortunally the tests are being done on a production environment and I can't restart it as frequently as needed. I'll try.

**Comment by Janmm14** [comment]
Sure, take your time.
As I was the first one creating the bungee issue about it not letting all the keepalives through, I am just really interested why the average decreased that much.

**Comment by Janmm14** [comment]
This could be a possible problem: https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7#r37698703

**Comment by Janmm14** [comment]
@lucaazalim possible problem identified
https://github.com/SpigotMC/BungeeCord/issues/2783

**Comment by MrIvanPlays** [comment]
https://github.com/SpigotMC/BungeeCord/pull/2786#issuecomment-598031817

Perhaps the problem comes from that you run ViaVersion in your spigot servers or your server's network is terrible. 

EDIT: Or the calculations you perform in order to get average ping are wrong.

**Comment by lucaazalim** [comment]
@MrIvanPlays calculations are right (it's a simple average) and our network is fine. I can't test it without ViaVersion. I don't think that testing it with one online player is enough to assume that the problem is with ViaVersion, my network or calculations.

**Comment by MrIvanPlays** [comment]
Can you just dump https://github.com/SpigotMC/BungeeCord/pull/2786 's jar in your server and then give data? The problem's obv not waterfall, it's coming from bungee so you test it on bungee level.

**Comment by MrIvanPlays** [comment]
We may have some progress on this. https://github.com/SpigotMC/BungeeCord/commit/2f54c943720aea0c2c83049a37644fd67f6718bb

Can you test with latest bungee?

**Comment by lucaazalim** [comment]
@MrIvanPlays no improvements. Look what happened after updating:

![image](https://user-images.githubusercontent.com/10585881/83301254-b24e4e80-a1cf-11ea-805d-4119f86ddc9b.png)

This is how ping average is calculated:

``` java
private static int getPingAverage() {
	Collection<ProxiedPlayer> onlinePlayers = ProxyServer.getInstance().getPlayers();
	return onlinePlayers.stream().map(ProxiedPlayer::getPing).mapToInt(i -> i).sum() / (onlinePlayers.size() > 0 ? onlinePlayers.size() : 1);
}
```

**Comment by MrIvanPlays** [comment]
ok your code is wrong. for average you need .avg (or .average I forgot how was the method) without any dividing your current statistic shows the result of the sum.

**Comment by lucaazalim** [comment]
@MrIvanPlays I can't undestand what is wrong with my code. You are right that I should use the .avg() method of the Stream, but it doesn't change anything. I'm summing all the latencies and dividing by the number of online players.

**Comment by lucaazalim** [comment]
@MrIvanPlays I don't think my code is wrong, it's just a bit of a mess. It sums all the latencies and divides by the number of online players.

Just changed it to:

``` java
private static int getPingAverage() {
	return (int) ProxyServer.getInstance().getPlayers()
			.stream()
			.mapToInt(ProxiedPlayer::getPing)
			.average()
			.orElse(0D);
}
```

But it obviously doesn't fix the problem.

**Comment by astei** [comment]
You're measuring the wrong (and meaningless) statistic, in my opinion.

Averages are well-known for not being a resistant statistic. The presence of extremes in a list will cause its average to increase. You're averaging the ping of all players, which can be extremely skewed. For instance, if I connect on a cable connection to a server close to my location, I will have good latency (let's say 20ms), but if I'm connecting from a satellite internet connection, my latency will be quite awful ([Wikipedia](https://en.wikipedia.org/wiki/Satellite_Internet_access) quotes 638ms).

**Comment by lucaazalim** [comment]
@astei this is not meaningless. All my players live in the same country (Brazil) and the ping average directly shows instabilities and network problems. It helps us a lot to identify issues. I know that there are more effective statistics to diagnose network problems, but it doesn't explain why my graph shows that kind of latency spikes on the latest BungeeCord/Waterfall builds.

My average player online count per proxy is 1200. The latency average is not that much affected by a random player joining from China or from a satellite.

**Comment by Hyronymos-Old** [comment]
We noticed high traffic income with newest waterfall, it spikes nearly up to 950mbit/s with 300 players, thats the reason, why we have ping spikes as hell, we already reached 5TB traffic in 2 days.

Proof: https://image.prntscr.com/image/gnERN8pJT_qO58TtSbkUbw.png

You should check your traffic income with nload.

**Comment by lucaazalim** [comment]
@Hyronymos1337 I don't see this behaviour here. No changes on the income traffic.

**Comment by MrIvanPlays** [comment]
I'm pretty sure thats not bungee/waterfall/whatever fork of those problem. But with the latest changes we made on this topic the data got even acurater, although I think we will need one more change; to clean up some of the old keep alives in order to free up some memory. But this won't affect the data in any way.

I'm pretty sure these spikes are either server or clients' network problem. And I agree with @astei that this statistic is meaningless.

**Comment by Janmm14** [comment]
@MrIvanPlays it should get clenaed up pretty well actually, as its saved in serverconnection, its garbage collected once the server is switched.

**Comment by MrIvanPlays** [comment]
> @MrIvanPlays it should get clenaed up pretty well actually, as its saved in serverconnection, its garbage collected once the server is switched.

I was thinking that it would still stay in memory but as you say.

**Comment by lucaazalim** [comment]
Not a problem anymore. I'm not sure how it was fixed.
