### ISSUE TITLE
When pressed *tab* and there is a '\'

### ISSUE THREAD

**Issue by Tanju42** [PaperMC/Waterfall#459]
I have a String: te\\_st
When I press *tab* the preview is: te\\_st

And when I confirm that I want the string it places it as this: te\\\\_st

Here a Photo:
![Error-tab](https://user-images.githubusercontent.com/16364184/75627287-2d9f6480-5bcf-11ea-8ab6-e5b067eeb90b.png)

**Comment by Chew** [comment]
Can't reproduce, and this is likely a SSH client or operating system error.
