### ISSUE TITLE
Logs rate limit

### ISSUE THREAD

**Issue by haeiven** [PaperMC/Waterfall#460]
Hello,

Since few years now, bots attacks are rly common on Minecraft.

We've nice antibots to prevent that happening, but there's something who antibots don't handle, it's the logs. Some plugins are having errors when there's too many connections & cancelled connections. And then they're flooding the logs and it start to lag Waterfall.

My idea is to add an option to rate-limit the logs to prevent these lags.

**Comment by JH3Y50N** [comment]
JH_AntiBot v3 have log filter... handle and remove..

**Comment by electronicboy** [comment]
This is already built into log4j
