### ISSUE TITLE
disable_entity_metadata_rewrite causes other players to become invisible

### ISSUE THREAD

**Issue by jbdman** [PaperMC/Waterfall#461]
Similarly to #350 

I have an issue using the 4.1.0 Release Version of SkyFactory 4 (Forge 2838), and Waterfall build 323.

When disable_entity_metadata_rewrite is true, players are not able to see each other at all. When disable_entity_metadata_rewrite is false, players are able to see each other, but are periodically kicked due to the Unknown Meta Type.

I am also able to reproduce this issue using Forge 2838, no Mods, and pure Vanilla 1.12.2.

My config files follow:

config.yml:
```server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: '&1jbdman''s Bungee Connector'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    <domain redacted>: pubSF4
  ping_passthrough: false
  priorities:
  - test
  - privSF4
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  <username redacted>:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: <dont know if this is private, but redacted>
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  pubSF4:
    motd: jbdman's Public SF4 Server
    address: <ip redacted>:25567
    restricted: false
  privSF4:
    motd: jbdman's Private SF4 Server
    address: <ip redacted>:25565
    restricted: false
  test:
    motd: jbdman's test server
    address: <ip redacted>:25590
    restricted: false
```

waterfall.yml:

```use_netty_dns_resolver: true
disable_modern_tab_limiter: true
log_initial_handler_connections: true
throttling:
  tab_complete: 1000
game_version: ''
disable_entity_metadata_rewrite: true
```

If you need any logs, or verbose options enabled, just ask, happy to oblige.

Thanks for your time,
Josh (jbdman)

Edit: can confirm, issue is still present on build 325

**Comment by jbdman** [comment]
Will be testing this issue again, when I get home from work in approximately 5 hours.

**Comment by MrIvanPlays** [comment]
Are you running viaversion? Or have a combination with protocolsupport & skinsrestorer?

**Comment by jbdman** [comment]
No sir. Forge server on the back end, or vanilla, same issue occurs. No extra bungee plugins.

**Comment by jbdman** [comment]
Just tested this issue again today. Latest Waterfall, default settings (except rewrite metadata), with Stoneblock 2 {Forge 14.23.5.2846}. I can confirm the issue is still present.

**Comment by Ve6om** [comment]
We're getting the same issue.

**Comment by electronicboy** [comment]
Cannot reproduce against a spigot 1.12.2 server (jar I had lying around...)

**Comment by Ve6om** [comment]
well, obviously multiple others have reproduced it

**Comment by electronicboy** [comment]
There was some comments that this was an issue with configuration, e.g. IP forwarding enabled with servers stuck in offline mode; if that's the case, you can disable the tab list rewriting in waterfall.yml, otherwise, we need better replication info, I can't debug something I can't reproduce
