### ISSUE TITLE
Extra heart and protection icons no remove after switch server

### ISSUE THREAD

**Issue by andris155** [PaperMC/Waterfall#464]
Extra heart and protection icons no remove after switch server
https://www.youtube.com/watch?v=JNunZMOwPOQ

<img width="291" alt="Capture" src="https://user-images.githubusercontent.com/8324198/76661712-6b5f9e00-657c-11ea-84c7-bd7a6e66a81f.PNG">

<img width="564" alt="Capture" src="https://user-images.githubusercontent.com/8324198/76661671-53881a00-657c-11ea-9ddb-40e6c5cdca8b.PNG">

**Comment by MrIvanPlays** [comment]
Do you have entity metadata rewrite disabled? Are you running viaversion/protocolsupport?

**Comment by andris155** [comment]
Yes, disabled.
I don't use viaversion/protocolsupport plugins.
