### ISSUE TITLE
A way to create new servers through AWS and have Waterfall recognize them

### ISSUE THREAD

**Issue by s5bug** [PaperMC/Waterfall#466]
Is there a way I can hook into Waterfall to
1. Query how many players are on a certain server (or a certain subset of servers)?
2. Tell AWS to create the appropriate new server for a specific gamemode and map?
3. Tell Waterfall that that new server exists?

The usecase is as follows:

Say my server has various different gamemodes, such as `hg`, `uhc`, `bedwars`, etc. Some of those gamemodes may have templates for specific maps (`hg-jungle`, `bedwars-city`) while some may not (just `uhc`).

For any gamemode with `n` number of maps (`uhc` has only one map), and `m` number of in-progress/full games, `m`/`n` is the number of "full cycles". Any time I do not have a complete empty cycle (empty cycle meaning at least one empty server available for each map) I want to spin up a new server for the full maps so that I get back to the state of having an empty cycle.

With normal Bungee, `/greload` is slow, and I have to do some funky stuff to manage the configuration at runtime. Is there a better way to dynamically manage servers with Waterfall?

**Comment by electronicboy** [comment]
> Is there a better way to dynamically manage servers with Waterfall
Yes, the servers list in waterfall is mutable, allowing you to add/remove servers as your heard desires

1) "yes", bungee provides API for pinging servers, not to mention the players list that the proxy itself maintains (however, proxies list is local to the proxy)
2) I would imagine that there are java APIs available for that

**Comment by s5bug** [comment]
Is there a code example somewhere of changing servers at runtime?

**Comment by Janmm14** [comment]
BungeeCord API allows adding servers by constructing a server info with `ProxyServer.getInstance().constructServerInfo(...)` and then calling `ProxyServer.getInstance().getServers().add(...)`

Removal should be possible too, but make sure nobody is on the servers you remove.
