### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown meta type 14

### ISSUE THREAD

**Issue by xANoyU** [PaperMC/Waterfall#468]
https://paste.ubuntu.com/p/ybyNQhYn6P/
Kick from server to login server

I know to set "disable_entity_metadata_rewrite" as true Can solve this problem

But it makes my tablist sort incorrectly.
image:
![QQ图片20200318163921.png](https://i.loli.net/2020/03/18/1bjOYZQmNnBacr8.png)

Tips after being kicked out
![QQ截图20200318164543.png](https://i.loli.net/2020/03/18/vG2emfFNHqLExKA.png)

I use the BungeeTablistPlus plugin, But I don't know how to turn to them for help
this is BungeeTablistPlus plugin url↓
https://www.spigotmc.org/resources/bungeetablistplus.313/

Please help me!
I'm from China, I can't speak English. I can only use machine translation, I'm very sorry

**Comment by electronicboy** [comment]
tab list order is a known bug, pretty sure that there is already an issue report open for it
