### ISSUE TITLE
Add features to alert commands

### ISSUE THREAD

**Issue by leoncp9** [PaperMC/Waterfall#472]
Hi can you add the options for remove the prefix in the /alert command by waterfall proxy?
\u00a7h
In game i can use &h before all text for remove the prefix, but in the messages.properties file of Waterfall.jar i can't set the code \u00a7h
so is possible set the code &h for remove the prefix in /alert ?
Thank

**Comment by Janmm14** [comment]
In message.properties you should be able to just leave the alert message empty (or use `\u00a7f` as alert value if it complains about the value being empty).

**Comment by leoncp9** [comment]
yes work, thank little panda, have good day! :D
