### ISSUE TITLE
Force default server

### ISSUE THREAD

**Issue by cristiancmrg** [PaperMC/Waterfall#475]
### 
graciously
letalboy

**Comment by letlaboy** [comment]
When the force default server option is marked as true, waterfall only shows the players connected to the lobby, when a player leaves the lobby for another specific server the ping and the value of their connection is not displayed, thus, if there are 100 players on the rankup server and 1 in the lobby on the server motd still in the multiplayer tab of the user's laucher will mark the total of 1 player connected to the server, while there are 101 players in total. when deactivating the force default server the error ends and the server returns to display in its status 101 connected players.

    For now I will be waiting, I can say that my opinion is a great server connector and the only one that solved my problem with the connection between forge moded servers and default servers. thank you waiting for a reply.

graciously
letalboy

**Comment by electronicboy** [comment]
that is not force default, that's ping passthrough
