### ISSUE TITLE
[Enhancement] Native libs Windows

### ISSUE THREAD

**Issue by metrotyranno** [PaperMC/Waterfall#476]
Hi, Running without native libs on windows causes quite poor performance. Would it be possible to get native compression and cipher libs in windows?

**Comment by xxDark** [comment]
Update your JRE to the version at least 11 and ask Waterfall developers to use new Inflater/Deflater methods that accept `java.nio.ByteBuffer` if they are available.

**Comment by electronicboy** [comment]
We had some issues getting waterfall to compile against 11, might take another stab at it at some point but getting the java 11 stuff working is a goal, I don't however use windows, so generally maintaining libs for platforms I don't use is generally an issue, and given that linux in general is the most popular platform for running the proxy, non-linux platforms are shamefully not a high priority here (I do use macOS, but, not really a platform I specifically aim to put too much effort for optimizations on)

**Comment by electronicboy** [comment]
Given waterfalls deprecation and the fact that windows is such a niche platform here, I'm not feeling inclined to deal with the issues preventing this or spend time specifically on an environment I have little experience with
