### ISSUE TITLE
Some functions of MOD will be invalid

### ISSUE THREAD

**Issue by Nothingness-Void** [PaperMC/Waterfall#482]
AcademyCraft‘s item Data Terminal will not work properly 

When I use BungeCord to connect to the mod server
AcademyCraft Unable to detect data terminal 
But when I connect directly to the mod server data terminal proper functioning
This problem also appeared in ShinColle

**Comment by electronicboy** [comment]
There is an option in waterfall.yml to disable entity metadata rewriting, I would suggest trying that

**Comment by Nothingness-Void** [comment]
THX I will try it
