### ISSUE TITLE
Player could not connect to the server

### ISSUE THREAD

**Issue by luanmenglei** [PaperMC/Waterfall#483]
The error is simply io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

It happens in when I use ProxiedPlayer.connect to send the player to another server,

It usually takes about 10-30 tries before they actually get in.

I'm using
java:
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
os:
CentOS Linux release 7.7.1908 (Core)
Linux localhost.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by electronicboy** [comment]
`io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use`
That is not a waterfall issue, something somewhere tried to use an address that is already in use.

**Comment by luanmenglei** [comment]
So what should I check from
