### ISSUE TITLE
Java 11 Breaks The Server

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#485]
Hello,
Recently I was experimenting with Java 11 and I found out that with this version waterfall will turn on, however, no one will be able to join. 
It results this error when a user joins:
java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

Thanks.

**Comment by electronicboy** [comment]
This is not an issue with waterfall, your certificate store is busted and missing certificates, I'd suggest reinstalling java
