### ISSUE TITLE
Commands don't work when building from sources

### ISSUE THREAD

**Issue by RimaitosLab** [PaperMC/Waterfall#487]
I tried to create a Docker image for a waterfall server. I wrote the following Dockerfile which clones the repository and executes waterfall b. Then I copy the waterfall.jar and delete all other files.

The server start fine and also connects to the default server. But I can not execute any commands related to waterfall/bungeecord (e.g. /server, /servers, /glist, /alert). The logs also show nothing interesting, only a plain command now found when executed from the console.

Dockerfile:
```
FROM ubuntu:bionic

EXPOSE 25577/TCP

RUN apt update && apt upgrade -y

#Install dependencies
RUN apt install -y bash curl git openjdk-11-jdk maven

RUN git config --global user.email "waterfall-container@local.host"
RUN git config --global user.name "waterfall-container"

#Download newest waterfall version
RUN git clone https://github.com/PaperMC/Waterfall.git /source

#Build from source
WORKDIR /source

RUN ./waterfall b

#move built file and clean up
WORKDIR /

RUN mkdir build
RUN cp /source/Waterfall-Proxy/bootstrap/target/Waterfall.jar /build/waterfall.jar

RUN rm -R source

WORKDIR /server

ENV JAVA_ARGS="-Xms256m -Xmx1G"
ENTRYPOINT java -jar /build/waterfall.jar
```

Is there something I missed when building from sources or why doesn't it work?

**Comment by electronicboy** [comment]
The commands are implemented in the modules, not inside the proxy itself; You'll need to copy them over

**Comment by RimaitosLab** [comment]
Wow that was a fast Answer, Thank you!
