### ISSUE TITLE
Waterfall refuses to connect to my spongeforge server

### ISSUE THREAD

**Issue by Roboticluke51** [PaperMC/Waterfall#491]
So i have a WaterFall server hosted on 1.15.2 that has a hub and then a flans server. On the flans server i have setup spongeforge and its corresponding settings in order for it to work with waterfall. But for some reason my WaterFall server refuses to connect me to my flans server.

here is what my WaterFall server says:
https://hastebin.com/vawakiqefa.md
and here is what my flans server sees:
![unknown](https://user-images.githubusercontent.com/26510945/80270840-674d9280-8689-11ea-9bf0-74a3b7243071.png)

The problem seems to be inside of WaterFall/SpongeForge because when i enable online mode and undo all of the settings on my flans server to make the server work with WaterFall i am able to connect with the direct ip without any issues.

It could very possibly be the fact that my waterfall server is 1.15.2 and my spongeforge is from 1.12.2. But from what i have been informed it seems that those versions should somewhat pair together (Do not quote me on that, lmao).

**Comment by Xernium** [comment]
@Roboticluke51 May I chime in here; Bungeecord does something called data rewriting in which data that the server sends to the client or vice-versa is read and verified so the the partner don’t have to suffer if one sends it maliciously modified or invalid data. Your mod setup seems to break or interfere how the vanilla game talks to the server and thus you will get kicked. There are two options to resolve this; Either have the mod authors fix how the mod that causes this behaves; or modify Waterfall so it skips rewriting entity data for 1.15.2. I can give you a build of waterfall with the second option applied so you can test for anything else broken

**Comment by Roboticluke51** [comment]
> @Roboticluke51 May I chime in here; Bungeecord does something called data rewriting in which data that the server sends to the client or vice-versa is read and verified so the the partner don’t have to suffer if one sends it maliciously modified or invalid data. Your mod setup seems to break or interfere how the vanilla game talks to the server and thus you will get kicked. There are two options to resolve this; Either have the mod authors fix how the mod that causes this behaves; or modify Waterfall so it skips rewriting entity data for 1.15.2. I can give you a build of waterfall with the second option applied so you can test for anything else broken

Thank you so much for your response, but literally 2 minutes before your comment i found a fix by using HexagonMC's version of Bungee.

**Comment by electronicboy** [comment]
Waterfall already has a patch to disable the mechanism behind this in waterfall.yml

The fact that you're saying it's a 1.12 server but the 1.15 entity remapping logic is in play is sketchy as all heck, some oddball protocol hack in play? o.O
