### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Joelxblackx** [PaperMC/Waterfall#495]
i have problem with waterfall can somebody help me!
>.... [11:49:04 ERROR]: [/149.202.74.183:49608] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 6e6f9828dc248ca11153eb922a60c5ef

**Comment by Janmm14** [comment]
someone sent invalid data, usually this can be ignored completely
also the connecting ip address of this error is not a consumer ip, but an ip of [OVH](https://ovh.com), a big server hoster, making it unlikely that this was a legit minecraft client connecting.
