### ISSUE TITLE
IllegalStateException: Adding 1 elements would exceed capacity of 128

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Waterfall#498]
Today I got kicked by my Waterfall and got the following exception in the log:
https://pastebin.com/raw/Dgd1dx5Y
It happended during switching worlds on a server (but not switching servers)

I did have a look in the waterfall logs and during the last days several players got kicked with this exception. Any ideas why that happens and what I can do to prevent this?

**Comment by Janmm14** [comment]
This is the limit on plugin messaging channels which can be registered by clients.

**Comment by Brokkonaut** [comment]
Is it possible to list those registered channels to see what might cause it?

**Comment by Artuto** [comment]
ProxyServer#getChannels

https://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/ProxyServer.html#getChannels--
