### ISSUE TITLE
<-> ServerConnector [ServerName] - read timed out

### ISSUE THREAD

**Issue by rudipratm** [PaperMC/Waterfall#500]
Hi, I'm having this problem to a few players on my server. This problem occurs while transfered the player to the main server after they logged in on Auth Server. Some people not having this problems, but some others experience this problems. As a fix, I do /send them manually using Waterfall Console.

Here's the log links: [pastebin](https://pastebin.com/MHNPmNTK)

Ps. Please read the comment on the logs...

**Comment by electronicboy** [comment]
`read timed out` means that no packets were sent in so long, more than likely a server issue

**Comment by rudipratm** [comment]
Hmm ok thanks for your response :)
