### ISSUE TITLE
Jenkins build config

### ISSUE THREAD

**Issue by Aeris1One** [PaperMC/Waterfall#505]
Hi,
I'm the SysAdmin of a little Minecraft server which plans to modify Waterfall to suit our needs. I cannot configure Jenkins to build Waterfall correctly, simply by running `./waterfall b`, I get some errors.
Can you tell me how is configured your Jenkins ?

**Comment by clrxbl** [comment]
How about providing the errors you get?

**Comment by Aeris1One** [comment]
https://ci.nexoviaserv.fr/job/Waterfall/1/console
That one: I have a Maven autoinstaller set up but seems it works only when invoking Maven using Maven Job type.

**Comment by clrxbl** [comment]
scripts/build.sh: line 6: mvn: command not found

You don't have Maven installed, just install it through your package manager

**Comment by Aeris1One** [comment]
I have autoinstallers set up in Jenkins and it works well when building other projects. I don't understand why it doesn't install here :/

**Comment by Aeris1One** [comment]
Solved, but what is the difference between `./waterfall b` and commands used by your Jenkins ? The output is not the same at all :/

**Comment by electronicboy** [comment]
we have extra steps involved for deployment, we /basically/ just ./waterfall p, mvn clean install
