### ISSUE TITLE
Patch can be removed - included in upstream

### ISSUE THREAD

**Issue by LuminousLoreBloom** [PaperMC/Waterfall#509]
https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0040-Add-console-command-completion.patch

https://github.com/SpigotMC/BungeeCord/commit/3508bf6c85e4b81b2228dbb8ad3b5bfde057e194#diff-a0f22706046677e92b813746c0882c55

**Comment by mikroskeem** [comment]
Does removing that make sense? Waterfall uses jline 3, while BungeeCord is still on jline 2

**Comment by LuminousLoreBloom** [comment]
I think it's best to remove the patch in Waterfall and just edit https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0036-Use-Log4j2-for-logging-and-TerminalConsoleAppender-f.patch to restore the deleted file ConsoleCommandCompleter and [update the line where the completer is set](https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0036-Use-Log4j2-for-logging-and-TerminalConsoleAppender-f.patch#L303) to use the new Jline system. That way this diff is reduced and that patch is removed.

**Comment by astei** [comment]
I think this is a no-go - Waterfall needs this diff because it uses [log4j](https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0036-Use-Log4j2-for-logging-and-TerminalConsoleAppender-f.patch) and `TerminalConsoleAppender`, unlike BungeeCord which relies on `java.util.Logger`.

**Comment by electronicboy** [comment]
As mikro said, waterfall uses jline 3, bungees impl is for jline 2, that commit uses API which has been moved in 3, our tab-completion stuff also looks more thorough, looks like bungee won't complete command names in the console?

**Comment by LuminousLoreBloom** [comment]
Yeah that's why I said simply change ConsoleReader.completer(ConsoleCommandReader) to LineReader.completer(ConsoleCommandCompleter) which is a two line diff change which is compatible.

It is true though that you can't complete to see all the commands of proxy which is one advantage over waterfalls impl.
