### ISSUE TITLE
Waterfall not pushing players to the correct servers when using direct connect IPs

### ISSUE THREAD

**Issue by FarmerMisShelley** [PaperMC/Waterfall#510]
Hi. We had a dev set things up who is no longer with us and I'm trying to start a new Stoneblock 2 server but what he setup is blocking us in some way. I guess this isn't so much an issue as it is a plea for help. if I can resolve this, it would be great. Below is some info and a link to the config.yml.

The Waterfall and lobby servers show when a player connects to lobby but shows no attempts to connect them to Stoneblock 2
The Stoneblock 2 server console shows no signs of any connection whatsoever.

config.yml:
[https://hastebin.com/pivutesata.makefile](https://hastebin.com/pivutesata.makefile)

If you need me to send anything else, just let me know

**Comment by astei** [comment]
The Github tracker should not be used for support.

Your problem is that you are using the same server name for both servers (sf4) - this is wrong.
