### ISSUE TITLE
Long commands result in kick for overflow in packet

### ISSUE THREAD

**Issue by JasonHorkles** [PaperMC/Waterfall#512]
If you paste a long command into a command block, or type a lot of text into chat then turn it into a command, you get kicked for `DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 256 (got <#> characters) @ io.netty.handler.codec.MessageToMessageDecoder:98`

It appears the issue is caused by [this change](https://github.com/PaperMC/Waterfall/blob/master/BungeeCord-Patches/0055-Cap-tab-complete-packets-to-clients-max.patch)
A comment about it can also be found [here](https://github.com/PaperMC/Waterfall/commit/ffe3d76ee6a89e4c8a7708eafdc3a148b341f51d#r39487212)

**Comment by KleinDevDE** [comment]
We can confirm this error, it also appears at our server
