### ISSUE TITLE
ServerSwitchEvent#getFrom() produces NoSuchMethodError

### ISSUE THREAD

**Issue by Jaimss** [PaperMC/Waterfall#513]
Error: https://hastebin.com/ikikixekin.cs
This is a bungeecord method that looks like it was added [here](https://github.com/SpigotMC/BungeeCord/commit/f1c32f84f46589632d7721d8de87d5589ef8e6a6). I want to use this for my server to be able to see where players are switching from. 

Please consider adding this method to Waterfall.

**Comment by mikroskeem** [comment]
>`waterfall-1.15.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b9a1246:313`

Update.
