### ISSUE TITLE
Issue with debug screen

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#517]
The part of the debug screen where it shows what type of server you're using is overlapping with the "Allocated: 100%" thingy and causes the text to be blurry / undreadable.
![image](https://user-images.githubusercontent.com/60381935/84264096-e48d7380-ab20-11ea-95bc-745d07b0679a.png)

**Comment by mikroskeem** [comment]
Same issue appears very likely on BungeeCord as well, but honestly nothing we can do about it.

I'm interested, what is your game resolution and GUI scale?

**Comment by ghost** [comment]
My game resolution is set to Current (2560x1440@165 (24bit)), and my GUI Scale is set to 5.

Is there no way to change the text to something smaller like this:

- Waterfall:1.15-SNAPSHOT:2615829:346 - Paper [TX]tx [RX]rx

or

- Waterfall - Paper - [TX]tx [RX]rx

**Comment by mikroskeem** [comment]
Use brand changing plugins if you really must. I'd personally change GUI scale smaller, as sooner or later you'll see that other texts in game (depending on your server's content) won't fit either.

**Comment by zachbr** [comment]
I'd think it'd make more sense to drop the version from the brand anyway. I'm not sure why Bungee thinks it's a good idea to shove the entire version string up there but ultimately it's up to @electronicboy

**Comment by ghost** [comment]
Ok

**Comment by manvankaliber** [comment]
Is there any way to just change this in a config or something? Do we really need to install plugins to fix this? Installing a plugin should never be the right answer...

**Comment by astei** [comment]
I would be in support of dropping the version anyway
