### ISSUE TITLE
Line breaks bug

### ISSUE THREAD

**Issue by Rubenicos** [PaperMC/Waterfall#521]
Minecraft Version: 1.16
**Screenshot:**
![Captura de pantalla (244)](https://user-images.githubusercontent.com/44579213/85447588-07714c00-b553-11ea-8fce-11e2cd58265b.png)

**Comment by electronicboy** [comment]
Cannot reproduce on the proxy itself, that's handled fine; looks like something is mangling your player list

**Comment by Phoenix616** [comment]
Easily reproducible by installing ServerListPlus and added a multi-line hover message without enabling the `Samples.Multiple` config option.

As far as I can tell the client simply doesn't like player names with new lines in them anymore.

**Comment by electronicboy** [comment]
This is purely out of our control, if the client isn't parsing \n in there anymore, which does look like the case, not much we can do

**Comment by Janmm14** [comment]
instead of \n just add multiple fake player entries then
