### ISSUE TITLE
Online mode bug ?

### ISSUE THREAD

**Issue by Koora7334** [PaperMC/Waterfall#522]
Hello, I have a problem with the last Waterfall version (353), freshly downloaded from the website.
When I tries to connect to the server (with default configs), It kicks me from it with the reason "Internal Error: java.lang.NPE", I am running on a VPS with java 8. It do the same on my computer. I am playing on 1.8

**Comment by electronicboy** [comment]
need the full exception

**Comment by Koora7334** [comment]
I have only this : https://share.koora.eu/Lepp1W266r.png
and (server) : https://share.koora.eu/sBWgNRDqSY.png

**Comment by Koora7334** [comment]
It do it only with online-mode enabled!

**Comment by Koora7334** [comment]
It came from my side, I was not on the minecraft launcher. But the proxy did not inform me that I was in offline mode on my launcher.

**Comment by Janmm14** [comment]
when you are offline mode in client, the NPE is clientside once the server sends encryptionrequest. nothing bungee or any server software can do here
