### ISSUE TITLE
Error and server disconnect when chat command returns error

### ISSUE THREAD

**Issue by MatthewNeri** [PaperMC/Waterfall#527]
When ever I run a chat command with an invalid arg or the command has an error I get kicked with the message "NullPointerException : null @ net.md_5.util.ChatComponentTransformer:44"
I have encountered this on both build 359 and 258

**Comment by Janmm14** [comment]
Its a bug in BungeeCord which got fixed very recently. Wait for a waterfall update.

**Comment by MatthewNeri** [comment]
> Its a bug in BungeeCord which got fixed very recently. Wait for a waterfall update.

thanks for the info!
