### ISSUE TITLE
All players have the same ip

### ISSUE THREAD

**Issue by ToxicPeople** [PaperMC/Waterfall#529]
Hello, for no apparent reason all the players suddenly have the same IP, this only happened on 1 server in the entire network, and we do not know why, since we have not touched any that has to do with it, only optimization. The problem is that now we cannot ban anyone from ip every time we ban someone, they come back with another account (Yes, it is a non-premium minecraft server). What option do I have so that this does not happen and the error is corrected? :c

**Comment by electronicboy** [comment]
You likely didn’t configure bungee mode on the backend server
