### ISSUE TITLE
Problem with Waterfal/Travertine | Message space with \ n

### ISSUE THREAD

**Issue by zArtemis03** [PaperMC/Waterfall#530]
So, I'll explain the problem in detail, I wanted to be able to edit the messages of BungeeCord, in particular the messages that are shown when the player is kicked, for example because the player is already online on the server or because he is using a non-malicious version etc. So in order not to use a fork of Waterfall / Travertine that are never updated I decided to extract the message.properties file and edit the messages from there, I did not have some type of problem to edit the messages, there is only one problem , the space between various messages. I know 2 ways, below are 2 examples.

already_connected_proxy=|-
   §4Line 1
   §4Line 2
etc..

and

already_connected_proxy=§4Line 1\n§4Line 2

Many plugins offer the ability to create multiple rows in this way, or even better than those who do it this way

no_permission: 
- ""
- ""

Anyway, for Waterfall / Travertine I tried the two methods but the first one did not work instead the second one works perfectly and therefore I created my whole message with multiple lines like this:

already_connected_proxy=§8§m------*-------+-------*------\n§3§lArkeus§f§lCraft\n§f\n§bSei stato kickato!\n§f\n§8• §7Autore: §bConsole\n§8• §7Motivo: §bSei già dentro al server\n§f\n§7Pensi che sia un errore?\n§7Contattaci su telegram §b@ArkeusCraft_Bot\n§f\n§8• §7Store: §bstore.ArkeusCraft.it\n§8• §7Sito: §bwww.ArkeusCraft.it\n§8§m------*-------+-------*------

But the result is this, I send you the photo, from what I have noticed it is possible to create a maximum of 2/3 lines if I go to use \ n but after the 2/3 times that I use it the other lines go beyond the message "Back to title screen", is the first time I see this problem, in plugins instead the "Back to title screen" always went down if I added other lines

https://user-images.githubusercontent.com/67873205/86539429-8fb10300-befc-11ea-8a9a-308449d7a685.png

Forgive me for my bad English, I am Italian and I do not have a high level with English, I hope you understand the problem and therefore I hope you can solve it

**Comment by MrIvanPlays** [comment]
Try replacing § with \u00a7
.properties files can't handle utf8 too well

**Comment by zArtemis03** [comment]
Don't work

**Comment by Janmm14** [comment]
Did you test this with different client versions?
Or does the problem not occurr with other kicks?

**Comment by Xernium** [comment]
Can literally not be fixed on the proxy, this is a client issue. Iirc this is already known and filed as bug on the mojira
