### ISSUE TITLE
Sending json messages runs into JSONEsxception

### ISSUE THREAD

**Issue by Bloodrayne1995** [PaperMC/Waterfall#538]
Hi,

I saw today a weird bug, that only happens with the latest build 361: [https://pastebin.com/dNEQWZG5](https://pastebin.com/dNEQWZG5)
Background-Information:
I develop a plugin which gets posts from a grav website to announce it in game. I use json to proper format this message and replace some variables with the given data.

This function looks like this: [https://pastebin.com/phYk7jga](https://pastebin.com/phYk7jga)

EoCore is another bungee plugin, which offers us to reuse database connections, manage players or in this example for a simple use of chat functions.
The function "broadcastJSON()" looks like this: [https://pastebin.com/tWJnkp5m](https://pastebin.com/tWJnkp5m)

With build 361 I got this error. If I use the previous version it worked.

Here is the base json. In this I replace the variables with the given data:
[https://pastebin.com/AJx8e1F3](https://pastebin.com/AJx8e1F3)

According to [https://jsonformatter.curiousconcept.com/](https://jsonformatter.curiousconcept.com/) the json is valid.

I saw that something with mojangjson happened in the latest build. Maybe this is the point which cause my problem.

**EDIT:** I replaced the code snippets with pastebin links. This looks better than before :)

Greetings
Bloodrayne1995

**Comment by Mystiflow** [comment]
I couldn't reproduce with both the JSON's in this post:
Here's the code I used to test (it doesn't throw any exception):
```
    public static void main(String[] args) {
        String json = "[{\"text\":\"Klicke hier um die letzte News \",\"color\":\"white\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://eona-minecraft.de/de/news/creative-und-themona-gehen-wieder-online\"}},{\"text\":\"Creative und Themona gehen wieder online!\",\"bold\":true,\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://eona-minecraft.de/de/news/creative-und-themona-gehen-wieder-online\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":[\"\",{\"text\":\"Veröffentlicht am: \"},{\"text\":\"03.07.2020\",\"bold\":true,\"color\":\"blue\"},{\"text\":\"\\n\"},{\"text\":\"Hallo liebe Community, endlich gibt es wieder neue News von Eona. Morgen am 01.03.2020 um 17:00 Uhr...\",\"italic\":true},{\"text\":\"\\n\"}]}},{\"text\":\" zu lesen!\",\"color\":\"white\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"https://eona-minecraft.de/de/news/creative-und-themona-gehen-wieder-online\"}}]";
        ComponentSerializer.parse(json);

        json = "[\"\",{\"text\":\"Klicke hier um die letzte News \",\"color\":\"white\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"%POST_URL%\"}},{\"text\":\"%POST_TITLE%\",\"bold\":true,\"color\":\"gold\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"%POST_URL%\"},\"hoverEvent\":{\"action\":\"show_text\",\"value\":[\"\",{\"text\":\"Veröffentlicht am: \"},{\"text\":\"%PUBLISH_DATE%\",\"bold\":true,\"color\":\"blue\"},{\"text\":\"\\n\"},{\"text\":\"%SUMMARY%\",\"italic\":true},{\"text\":\"\\n\"}]}},{\"text\":\" zu lesen!\",\"color\":\"white\",\"clickEvent\":{\"action\":\"open_url\",\"value\":\"%POST_URL%\"}}]";
        ComponentSerializer.parse(json);
    }
```

**Comment by Bloodrayne1995** [comment]
Weird. I develop this since 2 days. And my testserver downloads everytime a new waterfall jar.
It just stopped working over night :). 

I try this tomorrow again and comment here what I got.
Maybe i'm blind and dont see the failure on my code xD

**Comment by LuminousLoreBloom** [comment]
My bad. There was uncommited work in my workspace that was effecting the results. I'm getting an exception now. Will push a fix to BungeeCord soon and then when Waterfall pulls from upstream this should be fixed.

**Comment by Bloodrayne1995** [comment]
Oh ok. Thank you for your help :)

**Comment by Bloodrayne1995** [comment]
I tested it now with build 362 which includes your commit. Now its working fine again :D

Thank you for fixing this.

Greetings Bloodrayne
