### ISSUE TITLE
Server connector & Downstream bridge messages

### ISSUE THREAD

**Issue by bobhenl** [PaperMC/Waterfall#543]
Hi, couldn't you add one option to disable these messages? It's annoying when players are switching servers and it instantly spam proxy console.... Something like you did in waterfall.yml with initial_handler? So something like way to disable logging of these messages?

```
>.... [01:38:33 INFO]: [playername|/playerIP:port] <-> ServerConnector [server] has connected
>.... [01:38:33 INFO]: [/playerip:port|playername] <-> DownstreamBridge <-> [server] has disconnected
```

**Comment by bobhenl** [comment]
Noone want to solve this?

**Comment by electronicboy** [comment]
Use a log4j filter or one of the console spam fixers, etc, there is very little interest from me in terms of disabling this type of information, especially when it's already achievable with the logger framework;
The expectation to provide a way to disable every single message and still likely expect support in these configurations is just meh.
