### ISSUE TITLE
Fishing Rod bobber not showing for players

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#547]
Using Waterfall to connect to a 1.16 paper server.

Right clicking a fishing rod plays the sound, but doesn't show a bobber being casted. This works when direct connected, not via waterfall.

**Comment by Xernium** [comment]
Disable meta rewriting in the waterfall config and see if it still happens. If no I already know what’s wrong and I’ll PR a fix to bungeecord.

**Comment by partydev** [comment]
We had this issue and solved it by updating to the latest Waterfall.
