### ISSUE TITLE
Paper's Player#setPlayerProfile not working when connect with Waterfall in offline mode

### ISSUE THREAD

**Issue by djytw** [PaperMC/Waterfall#548]
I use paper's `Player#setPlayerProfile()` to change skin of a player, using code below
```java
        PlayerProfile profile = player.getPlayerProfile();
        profile.setProperty(new ProfileProperty("textures", skin_value, skin_sign));
        player.setPlayerProfile(profile);
```
This WORKS without problem when connect to paper directly (offline or online mode), and also works when connect to Waterfall in online mode. But not working in offline mode.

**Steps to reproduce:**

 - write a paper plugin that run the above code on command.
 - set both paper server and waterfall to offline mode
 - connect directly to paper, skin changed(works)
 - connect to waterfall:
      the reload animation shows(same to above), but skin unchanged.

**anything else:**

not sure if it helps: if use FastLogin plugin and force the player using the real UUID (not the offline one), skin can be changed. But offline players(or cracked players) cannot change.

**Comment by djytw** [comment]
Caused by the property rewrite at
[net.md_5.bungee.tab.TabList#Rewrite](https://github.com/SpigotMC/BungeeCord/blob/15b514130eb861cb44ddc787aa152f73e259dbb1/proxy/src/main/java/net/md_5/bungee/tab/TabList.java#L54)
Is it possible to add a configuration that skip the rewrite of items.property field, or just keep the properties when it's offline player?

**Comment by xxDark** [comment]
#386
