### ISSUE TITLE
[Issue] IllegalArgumentException : Chat message

### ISSUE THREAD

**Issue by haeiven** [PaperMC/Waterfall#551]
Hello,

Players are randomly disconnected from the bungee with this error:

https://paste.soleria.eu/nisikobagi.cs

The player was playing with version 1.8.9

**Comment by Janmm14** [comment]
Not vanilla client. Vanilla 1.8.9 clients cannot send empty chat messages.

**Comment by haeiven** [comment]
Probably, but most of people on Minecraft don't use the vanilla client...
This wasn't happening with an old version of Waterfall who was supporting 1.8-1.15.2
