### ISSUE TITLE
Long commands result in kick for overflow in packet

### ISSUE THREAD

**Issue by CampbellSoup077** [PaperMC/Waterfall#558]
So on our server we have quite a few custom villagers that sell custom items. Their summon command are quite large to fit in all their data. We just recently made our servers into a network with Waterfall. Now when we try to paste our commands into command blocks to summon our villagers, we get kicked and this message pops up.

DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 2048 (got 8668 characters) @io.netty.handler.codec.MessageToMessageDecoder:98

Command blocks actually have a character limit of 32,500. Limiting it to 2048 its quite the hindrance.

**Comment by electronicboy** [comment]
Fixed in https://github.com/PaperMC/Waterfall/commit/c0f946a534fc4f945ffbed4188501c72f4e67d40
