### ISSUE TITLE
[Improvement] Add Possibility to Ignore Connection Hostname for Reconnect

### ISSUE THREAD

**Issue by coco0325** [PaperMC/Waterfall#562]
This function is important for servers have multiple domains.
Content: https://github.com/SpigotMC/BungeeCord/pull/1956

**Comment by coco0325** [comment]
Could anyone help me to make a pull request?

**Comment by electronicboy** [comment]
PR already exists on bungee but appears to have 0 interest, there is very little interest for such a weird system for such a niche use-case when it can be trivially implemented by a plugin
