### ISSUE TITLE
No longer forge support?

### ISSUE THREAD

**Issue by notFunnys** [PaperMC/Waterfall#563]
I wanted to pack a modpack into my small server network again, I also have "`forge_support: true`", but I get a readtimeout error if I want to go to the Forge server (I don't have any mods in it at the moment)

`io.netty.handler.timeout.ReadTimeoutException: null`

edit: it worked ~ 4 months ago with a very large modpack..

**Comment by electronicboy** [comment]
read timeout suggests that something missed something, 
worth noting that #450, disabling metadata rewriting in waterfall.yml may help
