### ISSUE TITLE
Players not rendering

### ISSUE THREAD

**Issue by meowucme** [PaperMC/Waterfall#564]
Players can not see or interact with each other, even though they show up in the tab list.
[2020-08-27 02-54-11.zip](https://github.com/PaperMC/Waterfall/files/5134575/2020-08-27.02-54-11.zip)

**Comment by Chew** [comment]
Here's the video:

https://github.com/PaperMC/Waterfall/assets/8278263/39bd6334-4d76-474b-99d1-d556eb38d822

This doesn't seem like a Waterfall issue, too many variables for this.

What is the server running? Paper, etc? What versions of both?

**Comment by meowucme** [comment]
its "waterfall-370" and i downloaded the top 1.16.2 paper server yesterday.

**Comment by meowucme** [comment]
fricc i changed bungeecord and forward_ip to true

**Comment by electronicboy** [comment]
99% of the time, this is caused by plugins installed on the actual server mangling data, I've yet to hear of any reports of this specifically for waterfall where information has actually been provided, generally it boils down to server plugins such as outdated Tab, etc

**Comment by Chew** [comment]
After reports, this appears to be a Waterfall issue, it is able to be reproduced without plugins on either server. Testing on Bungee to see if this is an upstream issue.

**Comment by Chew** [comment]
This is an upstream issue, see SpigotMC/BungeeCord#2942

**Comment by Chew** [comment]
This appears to be caused by being in "online mode but IP forwarding not enabled." if you are experiencing this issue, try this solution.

**Comment by meowucme** [comment]
> This appears to be caused by being in "online mode but IP forwarding not enabled." if you are experiencing this issue, try this solution.

That's why I closed it...?
