### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by Redemption2033** [PaperMC/Waterfall#571]
I'm having trouble connecting my forge server to my vanilla hub. I'm not using Sponge/SpongeForge, just Forge. I have seen previous issues about this but I believe they are outdated and they were not helpful to me. 

I have multiple other vanilla servers connected to my network fine, however with my forge server online and appearing in the waterfall/bungee server list, and attempting to connect, I get the error "Could not connect to a default or fallback server, please try again later". I have forge-support enabled and I'm not sure what else I can do to solve this issue. I appreciate any help.

**Comment by astei** [comment]
You can't use a Forge on a proxy with IP forwarding without also using SpongeForge.

Also you failed to include any logs and server versions that might help us investigate the issue.
