### ISSUE TITLE
Windows being windows (yet again)

### ISSUE THREAD

**Issue by MrIvanPlays** [PaperMC/Waterfall#575]
Build 380: console is ew
`2020-10-28 14:38:02,478 main WARN Advanced terminal features are not available in this environment`

Build 379: this doesn't show to me and console is completely fine

**Comment by moom0o** [comment]
Step 1: Don't use windows server
Step 2: Profit

**Comment by MrIvanPlays** [comment]
> Step 1: Don't use windows server

I don't. I just test on my local pc which is windows.

**Comment by electronicboy** [comment]
No additional reports of this, I don't have a windows machine and chasing down endless problems with an OS I don't have the means to test on and where reproduction of these issues is generally spotty as all heck, I have 0 interest in wasting my time on.

if somebody can spot the issue, feel free to open a PR, but I will not be investing personal time into terminal support issues on windows
