### ISSUE TITLE
Restrict plugin messaging packets only to a list of IPs

### ISSUE THREAD

**Issue by zPirroZ3007** [PaperMC/Waterfall#583]
Hi. 

It's a well known issue that plugin messages can be easily spoofed and I think that allowing every IP to send plugin messages packets it's not the best way to handle this kind of stuff.

I propose to add a list of IPs in the `config.yml`, only the packets from those IPs will be handled by the plugin messaging module.

Let me know if this is a doable proposal and if the packet IP can be spoofed making this proposal not useful at all.

Thanks in advance.
Kindest Regards.

**Comment by Janmm14** [comment]
Bungee plugins just have to verify the source of the plugin messages.

**Comment by Phoenix616** [comment]
Plugin messages are a base part of the game. They are used for some game mechanics as well as mods to communicate with the server. Blocking them in general is not easily possible, plugin authors have to ensure that their plugin messages can only be sent from proper sources (e.g. by blocking the channel on the bungee or by using key/password authentication)

Of course a plugin could also be made to simply block all incoming plugin messages so this doesn't need to be in the proxy to begin with.

**Comment by electronicboy** [comment]
What phoenix said, plugin messages are a core part of the game, not as much these days but we gotta support back to 1.8 (and .7...), so, disabling plugin messages as a whole is not even remotely viable; The proxy also itself only accepts plugin messages for its messing channel from the server, beyond that, plugins need to ensure that they validate their source, practically 1 one of security
