### ISSUE TITLE
ChatColor not convert Color correctly

### ISSUE THREAD

**Issue by TheMagBum** [PaperMC/Waterfall#584]
TestingCode:
                Color color = new Color(red ,green ,blue );
                ProxyServer.getInstance().getLogger().info(ChatColor.of(color) + "COLOR RGB: " + red  + " " + green + " " + blue + " - " + rgb);

the Color is Dark Gray, but ingame it display another Color

**Comment by Janmm14** [comment]
You tested with 1.16 client?

**Comment by TheMagBum** [comment]
yes, the problem is that the ChatColor.of(Color) methode is broken.

**Comment by electronicboy** [comment]
If by "ingame", you mean the actual console output, see:
https://github.com/PaperMC/Paper/issues/4668
