### ISSUE TITLE
java.lang.runtimeexception: varint too big

### ISSUE THREAD

**Issue by hkkongou** [PaperMC/Waterfall#586]
when all the players are send to lobby server, some player will face this problem
java.lang.runtimeexception: varint too big
![image](https://user-images.githubusercontent.com/61608872/100491409-358c3500-315e-11eb-8291-1ac2d98ebd45.png)

waterfall show this:
[10:30:54] [Netty Worker IO Thread #14/INFO]: [PecomcAdmin] disconnected with: IOException : 遠端主機已強制關閉一個現存的連線。 @ sun.nio.ch.SocketDispatcher:-2

![image](https://user-images.githubusercontent.com/61608872/100491484-e0045800-315e-11eb-97f6-903e02abbecf.png)

waterfall version 1.16 #384

**Comment by electronicboy** [comment]
Something, likely on the server, mangled a packet from the server, that looks like a light packet which the proxy doesn't even touch
