### ISSUE TITLE
A crash will occur if the number of discards exceeds 64 at a time

### ISSUE THREAD

**Issue by misako227** [PaperMC/Waterfall#589]
I used the **StackUp mod** to make the size of items more than 64, crash occurs when more than 64 items are discarded at once, Direct connection to the server does not have this problem.
If you have time, please help me look at this,Thanks.

When discarding：
[https://paste.ubuntu.com/p/Gnmj952XG3/](https://paste.ubuntu.com/p/Gnmj952XG3/)

**Comment by Xernium** [comment]
Disable entity meta rewriting. The mod is not compatible with it

**Comment by misako227** [comment]
> Disable entity meta rewriting. The mod is not compatible with it

Thank you for your reply.
