### ISSUE TITLE
Crashing issues

### ISSUE THREAD

**Issue by Curtis3321** [PaperMC/Waterfall#59]
Hey,

Currently attempting to use Waterfall. Once a 1.7 client gets around users (a decent amount of them 30+) it'll kick them. 

I have my config waterfall.yml to simply allow 1.7, 1.8 & 1.9.

No plugins are causing this as once I put the good ol' Bungee, it doesn't kick it. Once I switch WF on, it kicks me.

Thanks :)

**Comment by jamierocks** [comment]
Waterfall doesn't support 1.7 - so either you're running an old build (unsupported) or you're using Travertine (repost this issue in the correct repo).
