### ISSUE TITLE
When translating messages into Portuguese, special character bug.

### ISSUE THREAD

**Issue by Brasil150** [PaperMC/Waterfall#590]
When translating the "messages.properties" file(which is inside waterfall.jar), special characters from my language (Portuguese) end up breaking the translation.

Characters such as:
ê, á, ã, í, ç, à, õ, among others.

![2020-12-12_14 20 16](https://user-images.githubusercontent.com/55663598/101991948-6607bf00-3c86-11eb-9b12-589d4124f9b8.png)
![2020-12-12_14 21 18](https://user-images.githubusercontent.com/55663598/101991950-67d18280-3c86-11eb-957d-25e3d941bfd7.png)

I hope the bug can be fixed. I don't believe it is a bug in the waterfall itself, but in the original bungeecord

**Comment by Janmm14** [comment]
You saved the file not in the default encoding of the server you run Waterfall on.

**Comment by electronicboy** [comment]
This is an encoding issue as already hinted, property files do not support unicode until java 9+
Either update to a newer version of java and make sure that the file is saved in the proper encoding, or, use native2ascii to convert the unicode text to a format that's supported by java.

**Comment by Brasil150** [comment]
> Atualize para uma versão mais recente de java e certifique-se de que o arquivo seja salvo na codificação adequada ou use native2ascii para converter o texto Unicode para um formato compatível com java.
How to do this?

**Comment by Brasil150** [comment]
> This is an encoding issue as already hinted, property files do not support unicode until java 9+
> Either update to a newer version of java and make sure that the file is saved in the proper encoding, or, use native2ascii to convert the unicode text to a format that's supported by java.

How to do this?
