### ISSUE TITLE
Error on join

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#593]
[20:38:49 INFO]: [/IP|Michu_toja_] -> UpstreamBridge has disconnected
[20:38:49 INFO]: [IP|Michu_toja_] <-> DownstreamBridge <-> [lobby] has disconnected

I have well-configured ip addresses, because I can connect to them normally. But when I turn on the waterfall and enter through it, it pops up, and writes that it is impossible to connect to the server (added in the waterfall), I will enter the lobby, but from the lobby to other I can not and in other directions, as I am on survival, then not to others can I go in

**Comment by electronicboy** [comment]
all we can see from that is that the client disconnected, there is nothing useful in there, check your client logs, etc
