### ISSUE TITLE
mysterious packets made bungee crash

### ISSUE THREAD

**Issue by Cris9807** [PaperMC/Waterfall#594]
Hey developers,

recently a mysterious package from an brazilian IP occured on my server which made it crash. Is there any way to prevent this from happening, so that those packets are automatically rejected?
[bungee-package.pdf](https://github.com/PaperMC/Waterfall/files/5825284/bungee-package.pdf)

i had to put it into a pdf because it's almost 20 din a 4 pages long ...

Thanks in advance,
Cris

**Comment by Chew** [comment]
Please use a paste site instead

**Comment by Cris9807** [comment]
https://pastebin.pl/view/ba60cf32

**Comment by Black-Hole** [comment]
Looking at PacketLoginInStart in Spigot shows that vanilla Minecraft is limiting the username to 16 bytes, while LoginRequest does not and so up to 32767 bytes could be used.

Anyway, this would only spam the logs. But for web interfaces showing those logs this could potentially insert script code.

**Comment by BuildingDave** [comment]
Same Problem.

3-5 crash / day

https://pastebin.com/9psGCPXb

**Comment by electronicboy** [comment]
a PR that should resolve this has been pulled
