### ISSUE TITLE
player's won't get removed from proxy network

### ISSUE THREAD

**Issue by DEADLYDEVIL-IR** [PaperMC/Waterfall#599]
hi i have problem with waterfall sometimes when my members disconnect from a server they will not get removed from the waterfall server
![image](https://user-images.githubusercontent.com/64157024/105633373-668e9a80-5e6d-11eb-924e-bf930fe7825c.png)

![image](https://user-images.githubusercontent.com/64157024/105633366-5971ab80-5e6d-11eb-9c32-d445402353ae.png)

there’s noOne in survival named unknown but in waterfall it says he’s in survival
also i tried kicking them but it didn't workout

**Comment by electronicboy** [comment]
no further reports of this and every instance of this in the past has been traced back to plugins
