### ISSUE TITLE
Encountered exception during login process

### ISSUE THREAD

**Issue by DJDanTheMan** [PaperMC/Waterfall#605]
Hi, I'm using the latest waterfall jar and for some unknown reason when I added one plugin to my skyblock server I got this error.

ServerConnector [skyblock] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!

**Comment by Xernium** [comment]
Please at least provide information about the plugin in question. Everything else considered this issue is most likely invalid. If you provide info about the plugin we might still take a look regardless.

**Comment by DJDanTheMan** [comment]
The plugin was GenCubes, and the error it gave me on skyblock is the reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 6 bytes extra whilst reading packet 0

**Comment by electronicboy** [comment]
Something installed on the proxy is mangling the packet registry
