### ISSUE TITLE
Adventure support

### ISSUE THREAD

**Issue by kashike** [PaperMC/Waterfall#613]
The same as https://github.com/PaperMC/Paper/pull/4842.

@Xernium expressed interest in working on this a while back, I believe.

**Comment by BomBardyGamer** [comment]
This seems like a great idea, especially to add to the list of platforms with native support, which further allows for the scale of cross compatibility that I think Adventure is designed around. I don’t want to seem like I’m trying to take over or anything, but I’d love to give this one a go, modelling after Paper’s implementation of this. I’ll see what I can come up with and make a PR.

**Comment by Xernium** [comment]
Feel free to @BomBardyGamer 
I just lack the time currently. And that’s probably not changing soon
