### ISSUE TITLE
Customisable waterfall locale

### ISSUE THREAD

**Issue by Notarin** [PaperMC/Waterfall#617]
It would be really poggers if we could change some of the chat logging to have custom locale, especially the errors.
The current setup is really technical for an end users experience, ex.
![image](https://user-images.githubusercontent.com/25104390/110690991-9215dc00-81b2-11eb-95aa-57b743aa4452.png)
It would be much preferable if we could just edit a config file to whatever we wanted it to be
or at the very minimum, disable the chat logging.

**Comment by electronicboy** [comment]
You can extract the messages.properties file from the proxy jar and place it in the folder where the proxy runs and then modify any of the locale you want in there
