### ISSUE TITLE
 Connection reset by peer

### ISSUE THREAD

**Issue by honzajan123** [PaperMC/Waterfall#619]
Hello can someone help me please?  Some players are getting kicked with this message: NativeIoException : readAddress(..) failed: Connection reset by peer

![5793D810-8259-40B4-BC0A-AF8FA0143DB3](https://user-images.githubusercontent.com/80659718/111096982-f3d29f00-8540-11eb-8197-da059982cd7d.jpeg)

**Comment by electronicboy** [comment]
the connection was closed in an unexpected manner
