### ISSUE TITLE
cant join my 1.7.10 server (forge)

### ISSUE THREAD

**Issue by wolflord212312** [PaperMC/Waterfall#620]
Exception Connecting:decoderException:net.md_5.bungee.protocl.badpacketException:unsupportedprotocol version 5 @ io.netty.handler.codec.MessageToMessageDecoder:98

Hub/waterfall running viaversion/backwards so u can join threw 1.16.5-1.7.10
The forge server is 1.7.10 (ftb infinity)
The hub is 1.12.2
can join the hub tho

**Comment by electronicboy** [comment]
Waterfall doesn't support 1.7.10, you need Travertine

**Comment by wolflord212312** [comment]
oh ok thx
