### ISSUE TITLE
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(8) exceeds writerIndex(5): PooledUnsafeDirectByteBuf(ridx: 2, widx: 5, cap: 5)

### ISSUE THREAD

**Issue by hkkongou** [PaperMC/Waterfall#623]
There is a error message pop up when player downstream from my live server.

log:
https://pastebin.com/g3Dih3zy

currently, does have any clue on how to reproduce this problem and don't know what will it affect

**Comment by Xernium** [comment]
Disable entity meta rewriting in the waterfall.yml
This might be a plugin or mod not completely adhering to the strict requirements of this feature.
