### ISSUE TITLE
TabComplete not being updated correctly on server switch

### ISSUE THREAD

**Issue by compieter-gh** [PaperMC/Waterfall#626]
Tab completion isn't updated correctly on a server switch like from hub to survival it also keeps the hubs tab completions and if tab complete is disabled on survival it will override that. 
What should happen is that the tab should be cleared on a switch and be asked from the server which the player joins not keep the old one. (sorry for my horrible english it's pretty late lol)

**Comment by electronicboy** [comment]
not a waterfall issue, the server sends the tab completion post join which updates the client and replaces its existing tab completion, issues like this are generally down to plugins breaking the tab completion stuff or misconfiguration of the server itself, e.g. disabling tab completion in spigot.yml

**Comment by compieter-gh** [comment]
Tested this without any plugins and still presists on waterfall i only have on the hub world edit as a test and second server the tab complete disabled in spigot which does cause waterfall too override the tabcomplete while it should be disabled.

**Comment by electronicboy** [comment]
Waterfall doesn't send a command definition structure to reset this, it relies on the fact that the server sends it on server switching, I have no interest in changing this behavior

**Comment by compieter-gh** [comment]
So basicly saying that spigot/paper should send a reset on join? instead of literately doing nothing i assume?

**Comment by compieter-gh** [comment]
Made an issue by paper itself thank you for helping.
