### ISSUE TITLE
reduce native buffer utilisation by default

### ISSUE THREAD

**Issue by electronicboy** [PaperMC/Waterfall#628]
Java does not cooperate that well with Docker. We have experienced a lot of OOM issues on our network and we managed to fix our issues with our proxy by allocating twice the proxy heap uses in overhead.

The primary reason is because aside from JVM overhead you need to also have room for direct buffers, which can get big.

One startup option I would recommend is . By default Netty pools up to 16MiB buffers and Minecraft only sends packets 2MiB in size, maximum. This option will bring it down to 4MiB and should provide some breathing room if you don't want to increase your memory allocations.

_Originally posted by @astei in https://github.com/PaperMC/Waterfall/issues/327#issuecomment-473565251_

**Comment by electronicboy** [comment]
We need to look into applying this automatically,

ref: #627 
Bungee creates an event pool with 0 limitations, which means that it's pretty easy to drain a system of resources if you're able to take advantage of this

**Comment by Janmm14** [comment]
Maybe it'd be good to manually define -XX:MaxDirectMemorySize=size (I think the default is identical to Xmx) as well.

**Comment by electronicboy** [comment]
that's a JVM flag, we can't control that programmatically afaik?
increasing that also generally doesn't solve the issue as draining resources is pretty trivial still, biggest thing I think would be to try to reduce the default buffer size and maybe look at making the event look bounded with a config option and maybe some auto guesstimation maths for default

**Comment by Janmm14** [comment]
I know thats a jvm flag, so with manually i meant to check if we should ask users to use a lower max heap and allow for more direct mem than max heap as kind of workaround in case this happens in scenarios without abuse/attack.

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Waterfall/commit/e782e77edf184ddea7ce5e7c33bcac567fc8b0d5
