### ISSUE TITLE
Sign official papermc builds

### ISSUE THREAD

**Issue by Janmm14** [PaperMC/Waterfall#629]
With the recent threat of sophicisticated backdoor malware plugins over on spigotmc, it should be considered that PaperMC uses some sort of certificate to sign their official builds of Waterfall. Could also be self-signed for 999 years or so. This allows for better checking of jar file modifications and some jar file modifications might even be stopped from running.

**Comment by JRoy** [comment]
literally takes 5 seconds for malware to just delete or just change signature data. Just don't download sketchy stuff.

**Comment by Janmm14** [comment]
Would still hinder existing malware.

This is not for me, but for people with less experience. New tutorials and instructions for example with a signature check in the start script might improve the situation.

People might also want to use the signature check in a cronjob etc.

One could also add checks inside the code that the CodeSource certificate hash is correct. I've done this for example in my plugin [JsonMessageMaker](https://github.com/Janmm14/JsonMessageMaker/commits/master).

For forks of the software its just changing the parameters for signing and the hash, while the effort for malware is even higher.

**Comment by electronicboy** [comment]
people with less experience are not going to spend their time verifying that their jar is valid each time, nor is signing nightly builds a good security practice at all, if there is a system that would be compromised on our side, it's all giving them access to the entire distro chain
