### ISSUE TITLE
Nothing happening when connecting to forge server

### ISSUE THREAD

**Issue by ptmrankzy** [PaperMC/Waterfall#630]
I try to connect to my forge server from another spigot server and nothing happends.
This is what shows up in the console: 
```
[00:53:05] [Netty Worker IO Thread #1/INFO]: [Rankzy|/127.0.0.1:64231] <-> ServerConnector [Sammycraft] has connected
[00:53:05] [Netty Worker IO Thread #1/INFO]: [Rankzy|/127.0.0.1:64231] <-> ServerConnector [Sammycraft] has disconnected
```
The only fix i found is to set "online_mode: false" but this removes player skins and causes other issues.

**Comment by electronicboy** [comment]
The server disconnected you, this is generally as forge doesn't support IP forwarding so has no clue what to do, you need sponge for this to work, basically, or find a mod which supports IP forwarding; Depending on the mods installed, you may need to mess around with the settings in waterfall.yml, specifically aspects like tab rewriting and entity metadata rewriting
