### ISSUE TITLE
Allowance of empty packets from server

### ISSUE THREAD

**Issue by Etrayed** [PaperMC/Waterfall#631]
Hey so recently commit (c19c4771deb96ad88e01781674d7d716dd10d3c0) was dropped which blocks empty packets from players, but allows them from the server-side. I don't understand why this change has been made because now players are always getting kicked for these empty packets and I would like to know how these empty packets are created and how we could prevent them. We did upgrade Waterfall to the latest version to fix a crasher but now our players are being kicked for the reason said above.

**Comment by electronicboy** [comment]
Flag seems to represent the wrong thing, so, this is fixed
Your server is sending empty packets, i.e. packets which are empty (yet still framed)
This is generally caused by janky plugins messing with server internals
