### ISSUE TITLE
Developer friendly

### ISSUE THREAD

**Issue by N1CK145** [PaperMC/Waterfall#632]
May add getting started and/or link the bungeecord getting startet.

**Comment by aurorasmiles** [comment]
Can you please be a bit more descriptive what exactly you want?

**Comment by N1CK145** [comment]
Sorry,
It would be great if you could add a bit better documentation. If you want to start a new project, you just got the information how to get the API. I just started and don't know how can I start with the plugin.

It would be nice if there was an "Getting started" section where the basics are shown. Enrtry point to the plugin (onEnable())

Like this:

## Getting Started
### Hello World
```java
@Override
public void onEnable() {
    getLogger().info("Hello World");
}
```

I hope this was a litte bit descriptive. I'm sorry

**Comment by Chew** [comment]
I believe the MCDev plugin for IntelliJ starts you off fairly well. Regardless, this is better suited for https://github.com/PaperMC/PaperDocs repo instead, and for all platforms.

**Comment by Janmm14** [comment]
As waterfall is a fork of bungeecord, just use the available documentation of bungeecord at https://www.spigotmc.org/wiki/bungeecord-plugin-development/
