### ISSUE TITLE
Commands with arguments not working

### ISSUE THREAD

**Issue by semenishchev** [PaperMC/Waterfall#636]
When I try to execute command with args, command not executes at all, but without arguments all works fine

**Comment by electronicboy** [comment]
that really gives is nothing to go off, are you using real spaces and not some misc character? logs? any form of info?

**Comment by semenishchev** [comment]
> that really gives is nothing to go off, are you using real spaces and not some misc character? logs? any form of info?

Umm, this is empy command that sends to player argument count. No errors or any.

**Comment by electronicboy** [comment]
You're not really clarifying what the issue is, is this a command you're making yourself? if so, I'd suggest using the dev channel on the discord, otherwise I have very little clue what you're trying to do and really can't help you with the lack of info here
