### ISSUE TITLE
Geyser Compatability Broken on builds above #420

### ISSUE THREAD

**Issue by ItsSynchro** [PaperMC/Waterfall#654]
Greetings, 

 After updating to the latest waterfall builds, Geyser and Floodgate compatibility seems to be broken. The error displayed is...
<-> InitialHandler - overflow in packet detected! A string was longer than allowed. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true

https://mclo.gs/RGl14af
https://mclo.gs/M88VBKU

The last compatible build appears to be #419 which means I won't have 1.17 support ;-;

**Comment by Proximyst** [comment]
Launch Waterfall with said flag and post the logs.

**Comment by Camotoy** [comment]
Please update your Geyser and Floodgate versions (do note that will bump the Java and Bedrock versions of Geyser to 1.17). We have fixed this issue on our end.

Feel free to close this issue.
