### ISSUE TITLE
Force to a Map from Host

### ISSUE THREAD

**Issue by pthoelken** [PaperMC/Waterfall#659]
Is this possible in the config.yml from waterfall that I configure when players use **/server server1** that the player connected forcly  to world1 (at spawnpoint) from server1? 

On server1 mutliverse is running. When the player goes (with multiverse) into server1 on world2 and logout and login again the player is still on world2. My final is, that the player which is logout in world2 after a relogin is by default and automatically in world1 (on the spawnpoint). 

I've already set the spawnpoint etc. but nothing works for me. 

These plugins are running on server1: 
![image](https://user-images.githubusercontent.com/12643853/122361775-db1ac080-cf57-11eb-9069-d50abe95457b.png)

These plugins are running on waterfall: 
![image](https://user-images.githubusercontent.com/12643853/122361837-eb32a000-cf57-11eb-9aad-2010ec3b6d7a.png)

**Comment by Janmm14** [comment]
Such a thing is not possible with bungeecord's config.yml.
However there are plugins out there like [BungeeTeleportManager](https://www.spigotmc.org/resources/bungeeteleportmanager.80677/) which can do this.

**Comment by Proximyst** [comment]
Use a plugin.
