### ISSUE TITLE
Kick issue if player stays at death screen without respawning

### ISSUE THREAD

**Issue by alaajel** [PaperMC/Waterfall#671]
I made more detailed issue at bungeecord repo but developers didn't bother to check it 
So i instade made issue here, Here is the issue https://github.com/SpigotMC/BungeeCord/issues/3146

**Comment by electronicboy** [comment]
can you reproduce this without a proxy? That error message implies that the proxy hasn't recieved any packets in so long

**Comment by alaajel** [comment]
> can you reproduce this without a proxy? That error message implies that the proxy hasn't recieved any packets in so long

No in spigot there is no kick i think as in testing but will retest today

**Comment by ham1255** [comment]
Update: there is no kick

**Comment by alaajel** [comment]
![image](https://user-images.githubusercontent.com/34905970/125282563-956bd080-e328-11eb-89cc-fa2a2e2de970.png)
no kick on spigot or paper server.

**Comment by Janmm14** [comment]
https://github.com/SpigotMC/BungeeCord/issues/3146#issuecomment-878224119

**Comment by Janmm14** [comment]
@ham1255 feel free to close here as well
