### ISSUE TITLE
Seemingly Random Timeouts

### ISSUE THREAD

**Issue by awtyashy** [PaperMC/Waterfall#672]
Hi,
So I've been having a few issues lately where players have been timing out when specific things happen.
I've only been able to identify the cause of one of the issues, and that's when a particle is sent with a speed of 0. If I set the particle speed to something small like 0.000001, it works fine. I've tried using this with basic bungeecord & waterfall without any plugins but nothing has changed. I don't think it's something to do with the server though because I tried doing it without a proxy and no timeouts occurred.

I have also tried it on 3 different machines with 3 different hosts, and still the same thing.

**Comment by xph11** [comment]
Having the same issue on my network as well

**Comment by Janmm14** [comment]
Minecraft Version? Client / Server
Viaversion?
Timeout value in bungee config.yml?
For the ease of testing can you provide a simple test plugin with a command for sending the particle?

**Comment by awtyashy** [comment]
Happens on every minecraft version, servers are from 1.12 - 1.16.5. Latest waterfall version.
Viaversion is on the individual servers and not the proxy.
The timeout value is 30000.
A test plugin can be found here: https://github.com/rewardedcarton/ParticleTest/releases/tag/1.0
The command is /particletask, might take around 30 seconds for it to time you out.

**Comment by fredagsguf** [comment]
I'm experiencing this aswell, seemingly random timeouts with random players..
we also have players whos alts get disconnected but not the primary account.

Waterfall version: 448
Java version: 11
timeout: 30000

**Comment by Baterka** [comment]
Yes, same problem on me but hapenning very randomly.. Players starts to have 10seconds ping and chunks not loading + chat not responding. Spigot server's tps are 20TPS (server is not lagging).

Hapenning on 16+ players on single server...

**Comment by Rockin21** [comment]
also having this issue
