### ISSUE TITLE
Waterfall to Waterfall kick

### ISSUE THREAD

**Issue by cardanawandra** [PaperMC/Waterfall#673]
overflow in packet detected! A string had more data than allowed. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true

**Comment by Janmm14** [comment]
What do you mean with "Waterfall to Waterfall kick"?

Chaining waterfall/bungeecord/velocity proxies is not supported.

**Comment by electronicboy** [comment]
nested proxies is not a supported setup as the entire system relies upon modifying the protocol in a way that ain't vanilla compat for stuff like IP forwarding, and IP forwarding won't work in these setups anyways

**Comment by cardanawandra** [comment]
but in previous waterfall 1.16 it's just works

**Comment by cardanawandra** [comment]
i don't want to downgrade my server tho

**Comment by electronicboy** [comment]
This is not a use-case we intend to support, you are more than welcome to increase whatever limit you're hitting on a fork but we are not going to accommodate for these types of setup
