### ISSUE TITLE
Random mass kick - UpstreamBridge has disconnected

### ISSUE THREAD

**Issue by antibitcoin** [PaperMC/Waterfall#676]
Getting random disconnects, sometimes 5 players would disconnect at the same time with the following error:
UpstreamBridge has disconnected

sometimes 
UpstreamBridge - NativeIoException: readAddress(..) failed: Connection reset by peer
[Proxy] Lost connection to server.

I can't point out where the issue is
My current version I am using:
waterfall-1.17-445

plugins
ViaBackwards-4.0.1.jar
ViaVersion-4.0.1.jar

config:
https://mcpaste.io/36b26db850397cc7

I did not have this issue on old waterfall
waterfall-1.16-414

My java version is 16
my bungee specs
10gbit line, 3gb ram, 5gb space, rayzen 9 cpu.

**Comment by electronicboy** [comment]
> Connection reset by peer

This means that something external to the proxy closed the connection in an unexpected manner, this is generally out of the proxies control and generally on networking or plugins, etc, you'd need to maybe look for client logs and see if there is anything there
