### ISSUE TITLE
Waterfall conflicting with RedisBungee?

### ISSUE THREAD

**Issue by IlPicasso** [PaperMC/Waterfall#68]
This problem only happens while running RedisBungee

When my users disconnect, they won't get removed from redisbungee. This only happens with Waterfall.

INFORMACIÓN] [eldragon98765432|/181.47.80.23:55937] <-> ServerConnector [DLV1] has connected
19:04:45 [INFORMACIÓN] [/181.47.80.23:55937|eldragon98765432] <-> DownstreamBridge <-> [lobby5] has disconnected
19:04:45 [ADVERTENCIA] Event LoginEvent(cancelled=true, cancelReason=You are already logged on to this server.

It may help to try logging in again in a few minutes.
If this does not resolve your issue, please contact staff., connection=[/191.80.251.137:20074|iLeem] <-> InitialHandler) took 380.186.196ns to process!
19:04:45 [ADVERTENCIA] Event PreLoginEvent(cancelled=false, cancelReason=null, connection=[/191.80.251.137:20074|iLeem] <-> InitialHandler) took 380.204.381ns to process!

**Comment by jamierocks** [comment]
Sounds like a certain event isn't being fired...

**Comment by IlPicasso** [comment]
I don't know if this has something to do

19:20:01 [INFORMACIÓN] [thelink186|/200.112.41.44:27231] <-> ServerConnector [lobby4] has connected
19:20:01 [ADVERTENCIA] Event LoginEvent(cancelled=false, cancelReason=null, connection=[/190.108.81.29:49753|hendrix00] <-> InitialHandler) took 259.692.908ns to process!
19:20:01 [ADVERTENCIA] Event PreLoginEvent(cancelled=false, cancelReason=null, connection=[/190.108.81.29:49753|hendrix00] <-> InitialHandler) took 259.723.935ns to process!

**Comment by ghost** [comment]
@jamierocks It's either that, or it's related to https://github.com/minecrafter/RedisBungee/issues/30

**Comment by jamierocks** [comment]
This looks to be an issue with RedisBungee or upstream (See https://github.com/minecrafter/RedisBungee/issues/30). Closing.
