### ISSUE TITLE
Feature request: show special information in the client if all servers are offline

### ISSUE THREAD

**Issue by martymarty004** [PaperMC/Waterfall#680]
It would be nice to have a simple system that makes Waterfall show to the client that the network is offline.

You could add a section in the config file where you can enable the feature and customize the message shown (MOTD, number of players, ect.) and how frequently Waterfall should check if any server is online.

**Comment by tomcraft** [comment]
Thats not the role of Waterfall imo, you can use a plugin to achieve this kind of behavior.

**Comment by martymarty004** [comment]
I know that, but most of the plugins that do this are made for a maintenance mode, which needs to be manually enabled.

This could be an automatic mode that Waterfall enables when it finds no servers online to forward players to.

**Comment by Janmm14** [comment]
Still a job for a plugin.

**Comment by martymarty004** [comment]
OK, I understand.

I'm closing the request.
