### ISSUE TITLE
Players can't connect to Paper 1.8.8 from waterfall

### ISSUE THREAD

**Issue by Lecer69** [PaperMC/Waterfall#683]
Hi there is a bug we cant connect to paper 1.8.8 from waterfall but we can connect to paper 1.12.2 or 1.13+ this is was fixed before updating. I didn't test it with Bungeecord. and I checked everything ports, Firewall, spigot.yml bungeecord=true. its working fine with paper 1.12.2 but if u change it 1.12.2 from 1.8.8 you cant connect.

**Comment by Janmm14** [comment]
What version did you use before Waterfall update?
Waterfall plugins?
Potentially relevant Paper plugins?
Logs of Waterfall and Paper?

**Comment by Lecer69** [comment]
before updating waterfall wasnt really old just 4 version i think.
Plugins: AdvancedNMotd, BungeeHelpMe, BungeePing, BungeeStaffChat, BungeeWhitelist, Command4Me, DynamicBungeeAuth, LiteBans, LuckPerms-Bungee, NetworkRestarter, PersianFontFixer, protocolize-plugin, ProxyAntiTab, RedirectPlus, SecuredNetwork, SkinsRestorer, SlashServer.

and there is no error in logs waterfall and paper
i tested paper without plugin

**Comment by Janmm14** [comment]
I was not just asking for errors in the log, the proxy log should show that people connected and what kick message they got as they were unable to join 1.8.8 server.

You are using quite a bunch of plugins on your proxy which are not using the bungeecord api, but dig deep into bungeecord internals.
First, try updating all your proxy plugins. If the issue persists, try removing plugins from your proxy until you can join 1.8.8 servers again and then report it to the faulty plugin's author.

There are no recent changes done which would just affect 1.8.8

**Comment by electronicboy** [comment]
Closing, this seems more like a support request than an actual issue report, and I'm not going to flood peoples emails trying to get you to provide basic information like logs
