### ISSUE TITLE
Cannot transpond 1.16.5forge clients' mod list to login server

### ISSUE THREAD

**Issue by Huaxidesu** [PaperMC/Waterfall#685]
bc server - waterfall  -1.17-448
target server - https://github.com/MohistMC - mohist-1.16.5-757

![3](https://user-images.githubusercontent.com/45794248/130362151-374c9c35-007d-49f3-98a9-f5a8b80d6883.png)
![4](https://user-images.githubusercontent.com/45794248/130362154-547e4d7a-f647-4ed4-a75d-e46d087a4bde.png)
![5](https://user-images.githubusercontent.com/45794248/130362155-150952ba-9d3b-48e9-af17-3cc25dfcad8b.png)

**Comment by electronicboy** [comment]
#450

**Comment by Huaxidesu** [comment]
> #450

https://github.com/ArclightPowered/lightfall-client
https://github.com/ArclightPowered/lightfall

these waterfall's fork look like support Modern forge
