### ISSUE TITLE
Auto refresh domain.

### ISSUE THREAD

**Issue by HySand** [PaperMC/Waterfall#688]
For some reason,my sub-servers' ip adresses are not statics,so i need to use ddns,which auto changes the ip addresses.And i set the domain as sub-servers' address in config but i still need to restart waterfall to get the new ip address.

**Comment by Janmm14** [comment]
Try
`waterfall.yml`:
```yml
use_netty_dns_resolver: true
```

**Comment by HySand** [comment]
> Try
> `waterfall.yml`:
> 
> ```yaml
> use_netty_dns_resolver: true
> ```

It's already true.

**Comment by electronicboy** [comment]
To my recollection, this is the default behaviour, it's just too darn easy
for anything which accesses those addresses to break it from what I recall
due to how the data is stored and exposed at runtime
