### ISSUE TITLE
fake players after bot attack.

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Waterfall#70]
video: https://youtu.be/IUmf2xY-hdE
screens:
![928eaea21a5e4c11ae1665747ef2cafe](https://cloud.githubusercontent.com/assets/8667294/17554613/6261fa7c-5f14-11e6-90c6-96e75754acc1.png)
![](https://i.gyazo.com/a53a7868d09af4fbccbaa2dda29059ae.png)
antibot plugin src: 
https://github.com/Dimatert9/AntiBot

**Comment by mgl** [comment]
Same problem here: #69

**Comment by jamierocks** [comment]
As with #69 I'm going to need the list of plugins you have installed, along with the build of Waterfall you're running and (if you've had any) stacktraces.

**Comment by Leymooo** [comment]
only one plugin. AntiBot. Source in main post.
Latest build - https://github.com/Dimatert9/Waterfall-1

**Comment by phase** [comment]
@Dimatert9 Open sourcing a list of your IPs wasn't the best idea.

**Comment by Leymooo** [comment]
This is public anti bot for Russian users.

**Comment by Leymooo** [comment]
Caused by connection throttle. https://youtu.be/u0SCVTCm3gc

**Comment by mgl** [comment]
@Dimatert9 is right, setting connection throttle to 0 resolves the problem.

**Comment by Janmm14** [comment]
As far as I know, Waterfall does not alter the connection-throttle. Does it happen with enabled connection throttle on normal bungeecord?

**Comment by mgl** [comment]
It doesn't happen on normal bungee with exact same settings.

**Comment by Leymooo** [comment]
Waterfall dont close connection and dont throw error if in PlayerDisconnectEvent was error.
Bungeecord log:
http://pastebin.com/ribLQ8Zs
WaterFall log.
18:10:21 [INFO] [/127.0.0.1:56541|Leymooooooooooo] <-> InitialHandler has connected
18:10:22 [INFO] [Leymooooooooooo] disconnected with: §cCould not connect to default or fallback server, please try again later: java.net.ConnectException
18:10:34 [INFO] [/127.0.0.1:56621] <-> InitialHandler has connected

there is no error, and UpstreamBridge has disconnected.

//plugin issue.

**Comment by caoli5288** [comment]
Same as #84
