### ISSUE TITLE
Maybe memory leak

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#72]
![1](https://cloud.githubusercontent.com/assets/3120587/17723612/fa524fae-646d-11e6-8de3-a852d1fc0b7f.png)
![2](https://cloud.githubusercontent.com/assets/3120587/17723613/fa9412fe-646d-11e6-83b9-d6b07f752a7c.png)

**Comment by Techcable** [comment]
I bet it's netty direct buffers -_-

**Comment by caoli5288** [comment]
I think so and I sure it is a memory leak. Look `res` today.
![3](https://cloud.githubusercontent.com/assets/3120587/17742456/ad02e23a-64d2-11e6-851c-42d2ec8a8b95.png)
![4](https://cloud.githubusercontent.com/assets/3120587/17742529/ea3df112-64d2-11e6-8cbf-19269e591fd2.png)

**Comment by caoli5288** [comment]
I had to restart to avoid OOM everyday. It will ate about 12G-15G memory in 24h. // About up to 1500 player in this instance.

**Comment by Techcable** [comment]
Please add `-Dio.netty.leakDetectionLevel=advanced` to your command line options.

**Comment by caoli5288** [comment]
I'll Test. THX

**Comment by caoli5288** [comment]
I'm sorry. I can't see any LEAK warning in log file. How can I do?

**Comment by kamcio96** [comment]
Plugins?

**Comment by caoli5288** [comment]
@kamcio96 MultiLobby, RedisBungee, ServerListPlus, SkinsRestorer. Only those.

**Comment by Techcable** [comment]
What are your full logs anyways?

**Comment by jamierocks** [comment]
Have you tested BungeeCord? Would be interesting to know if the issue comes from upstream.

**Comment by caoli5288** [comment]
@Techcable Not any special warn or error log. @jamierocks I'll test tomorrow:-)

**Comment by caoli5288** [comment]
@jamierocks Yes the same on origin BungeeCord. Only hapend while player count > 1000.
![5](https://cloud.githubusercontent.com/assets/3120587/17886618/3a2d59b6-6955-11e6-85d9-8f3d7bebd53a.png)
![6](https://cloud.githubusercontent.com/assets/3120587/17886617/3a2953de-6955-11e6-9006-4c17f7803b2e.png)
Other smaller instance
![7](https://cloud.githubusercontent.com/assets/3120587/17886678/8932468e-6955-11e6-8ed3-6e8dcd0153f1.png)
![8](https://cloud.githubusercontent.com/assets/3120587/17886679/893aaad6-6955-11e6-9ce4-e50033936854.png)

**Comment by jamierocks** [comment]
Hmm, it may be a good idea to make an issue on bungee's issue tracker them also

**Comment by caoli5288** [comment]
@jamierocks They will ignore this issue simply. Maybe.

**Comment by Techcable** [comment]
@caoli5288 Can I see your full logs with the leak detection turned on?

**Comment by caoli5288** [comment]
@Techcable Can not found any "LEAK" prefixed log :-(

**Comment by Techcable** [comment]
I'd like the full logs anyways.

**Comment by caoli5288** [comment]
@Techcable I'm sorry I cannot offer it.

**Comment by jamierocks** [comment]
Anyone able to confirm if this is still an issue?
