### ISSUE TITLE
java.lang.Throwable

### ISSUE THREAD

**Issue by ningwang747** [PaperMC/Waterfall#74]
06:18:40 [严重] java.lang.Throwable: Using a io.netty.buffer.UnpooledUnsafeHeapByteBuf, not a direct byte buf!
06:18:40 [严重]     at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:54)
06:18:40 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
06:18:40 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
06:18:40 [严重]     at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.setProtocol(InitialPacketDecoder.java:111)
06:18:40 [严重]     at protocolsupport.protocol.listeners.initial.InitialPacketDecoder.channelRead(InitialPacketDecoder.java:90)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
06:18:40 [严重]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
06:18:40 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
06:18:40 [严重]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
06:18:40 [严重]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:967)
06:18:40 [严重]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
06:18:40 [严重]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
06:18:40 [严重]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
06:18:40 [严重]     at java.lang.Thread.run(Thread.java:745)

**Comment by jamierocks** [comment]
This is intended https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0030-Print-stack-trace-when-the-ByteBuf-is-not-direct.patch
