### ISSUE TITLE
[Fork help/No waterfall issue] Need help with resolve conflict with patches.

### ISSUE THREAD

**Issue by Leymooo** [PaperMC/Waterfall#79]
Hello! Может кто-то помочь разрешить конфликт с патчем?
error log: 

```
fatal: 
sha1 information is lacking or useless (proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java).
error: could not build fake ancestor
Patch failed at 0043 russian
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
  Something did not apply cleanly to Waterfall-Proxy.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh
```

my fork: https://github.com/Dimatert9/Waterfall
Thanks.

**Comment by jamierocks** [comment]
You'll need to resolve the merge conflict.

**Comment by Leymooo** [comment]
But how?? I dont know how.

**Comment by jamierocks** [comment]
Looks like https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging should explain

**Comment by Leymooo** [comment]
https://i.gyazo.com/7e48bae8b17abaee4fc899b10cbe5e6e.png
![image](https://cloud.githubusercontent.com/assets/8667294/17923357/80053b2e-69ec-11e6-9e98-27bfe571a45f.png)
I think that the error in line 1 and 8
, but i dont know how fix this.

**Comment by jamierocks** [comment]
If you do some research on merge conflicts you should be able to get this resolved ;)

**Comment by Leymooo** [comment]
My english is bad. I really dont know how fix conflicts in patches.

**Comment by jamierocks** [comment]
I found a Russian tutorial - https://githowto.com/ru/resolving_conflicts

**Comment by Leymooo** [comment]
I dont have source, i have only patch, and i dont can apply this patch because i get error:
sha1 information is lacking or useless (proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java).
error: could not build fake ancestor

**Comment by jamierocks** [comment]
I'm not completely sure as to what you mean but assuming I do: the source is under Waterfall-Proxy this is where you will have to fix the conflicts.

Alternatively if you really can't resolve the merge conflict you could rewrite the commit.

**Comment by Dimatert9** [comment]
in WaterFall-Proxy i dont have "<<<<<<< HEAD"
```Alternatively if you really can't resolve the merge conflict you could rewrite the commit.```
how i can do this?
