### ISSUE TITLE
Issues with dynamic add ServerInfo

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#81]
All players in dynamic added server will flashback to lobby server while  someone type `greload` command. See `net.md_5.bungee.conf.Configuration#load`. We need a new map store dynamic added server.

**Comment by caoli5288** [comment]
Other way I can extend a custom ConfigurationAdapter on my plugin (but will conflict with other plugins) resolve this issue:-/

**Comment by minecrafter** [comment]
Simple. Don't use `greload`. It's not recommended by upstream anyway (and nor does it recommend the "dynamic servers" approach many people, myself included, have taken).

You can edit `config.yml` programmatically if you feel the need to use greload anyway.

**Comment by kamcio96** [comment]
btw greload should reload only permissions and messages

**Comment by sgdc3** [comment]
waterfall greload saved my network twice, please don't remove it

**Comment by jamierocks** [comment]
We don't plan on removing it
