### ISSUE TITLE
Issue with Event4j/RedisBungee

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#82]
See stack trace blow. It spam and server crashed immediately. I don't think this is redisbungee's issue because the server has been running smoothly for more than a day. The `com/google/common/cache/LocalCache$AccessQueue$2` impossible not to exist.

http://paste.ubuntu.com/23089044/

If you need any other information, please tell me.

**Comment by jamierocks** [comment]
Well I've never seen that before :s

**Comment by caoli5288** [comment]
I was also the first to get this error

**Comment by minecrafter** [comment]
It's probably a RedisBungee issues, but I'm not going to investigate because I'm not working on it any more.

@Chunkr: mind shining some light on this?

**Comment by minecrafter** [comment]
It's probably a RedisBungee issue, but I'm not going to investigate because I'm not working on it any more.

@Chnkr: mind shining some light on this?

**Comment by ghost** [comment]
@caoli5288 did you compile redisbungee yourself? Looks like `com/google/common/cache` is missing, I'll try to look into this tomorrow.

**Comment by caoli5288** [comment]
@Chnkr I'm sure `com/google/common/cache` is exists. It's part of guava what shade into bungeecord/waterfall.

**Comment by ghost** [comment]
I'll take a stab at it once I'm back from work :+1:

**Comment by jamierocks** [comment]
Anyone able to confirm if this is still an issue?

**Comment by jamierocks** [comment]
I'm going to assume this has been resolved with the removal of Event4J.
