### ISSUE TITLE
Error on player join.

### ISSUE THREAD

**Issue by 64bitjava** [PaperMC/Waterfall#83]
Stacktrace: https://gist.github.com/64bitjava/402eb4c9c42e45b142454c45f1cc23bb
config.yml: https://gist.github.com/64bitjava/c6fa7f4a73703a70e9320d1f3fbc9e83
waterfall.yml: https://gist.github.com/64bitjava/72ba497c493f7794edadd81b46140cbb
Plugins: AlwaysOnline, nuvotifier-universal-2.3.3, SlashServer, UltimateBungee and ServerSelectorBungee.

**EDIT** 
Version: http://i.imgur.com/EzSSCVy.png

**Comment by jamierocks** [comment]
Interesting... I'll take a look at this when I get back ;)

**Comment by jamierocks** [comment]
Anyone able to confirm if this is still an issue?

**Comment by 64bitjava** [comment]
Yes that is still an issue on player join. Tested it without any plugins on the latest waterfall build. 
It happens on Travertine as well.

**Comment by jamierocks** [comment]
And it doesn't happen on BungeeCord?

**Comment by 64bitjava** [comment]
Never happened, even with plugins installed.

**Comment by 64bitjava** [comment]
Travertine with Paper 1.8.8: http://i.imgur.com/WCPNBiC.png (no plugins, everything default)
Waterfall with Paper 1.8.8: http://i.imgur.com/LRZCh2l.png (no plugins, everything default)
Waterfall latest build with Paper latest: http://i.imgur.com/EmkHoYo.png (no plugins, everything default)
Bungeecord latest with Paper latest: http://i.imgur.com/YQbzR6U.png (no plugins, everything default)

**Comment by Janmm14** [comment]
This issue is no real issue, more a notification:
`java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!`
We are looking only for the second issue of the original stack trace:
`Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick`

**Comment by 64bitjava** [comment]
Haven't seen it in a while.

**Comment by Rushmead** [comment]
I've got it when using waterfall latest

**Comment by Techcable** [comment]
The `Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick` part or the `Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!` part?

**Comment by Rushmead** [comment]
The 

> Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!

**Comment by jamierocks** [comment]
`Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!` is **not** a bug, rather a stacktrace added by us to get more debug information.

**Comment by MarkTwoFive** [comment]
So... you're saying this debug information system administrators need to live with?

**Comment by jamierocks** [comment]
Bungee also had a message, we just provide a stack trace for extra information. Honestly by this point it cause more harm than good - I'll be revisiting this.

EDIT: https://cybre.space/@jamierocks/3711812

**Comment by MarkTwoFive** [comment]
It's one thing to print stack traces but it's another classifying them as SEVERE using those log levels. Also traces intentionally printed to the log should be clearly marked as that. Just as the MC/Forge exception upon every MC start which clearly states
> This is not an error.

**Comment by jamierocks** [comment]
I revisited printing the stack trace a while back and decided against it, reverted back to Bungeecord behavior - the false issues it was causing were far greater than the good it was doing.

https://github.com/WaterfallMC/Waterfall/commit/b5d048b57a7837cbb0a4801764ec5d4d698b8fa3
