### ISSUE TITLE
Issue with banned player

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#84]
Reproduction:
1. Ban a player
2. Player try join after banned
3. Un-ban it.
4. Player try join and got `You a already connected to this proxy`

Then the player can't join anymore. No issue with origin BungeeCord.

**Comment by kamcio96** [comment]
plugins, Waterfall version?

**Comment by jamierocks** [comment]
Probably related to https://github.com/WaterfallMC/Waterfall/issues/69

**Comment by caoli5288** [comment]
@kamcio96 Latest Waterfall. Would happen with no plugin. Minecraft server version spigot-1.8.8

**Comment by jamierocks** [comment]
It's possible its an issue with https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0027-Improve-connection-closing-fixing-the-kick-delay.patch

**Comment by caoli5288** [comment]
@jamierocks I revert UserConnection.java. No effect. :-(

**Comment by jamierocks** [comment]
Hmm, there are a lot of logic changes all over the place time to find where the cock up is :s

**Comment by caoli5288** [comment]
@jamierocks I'll test revert your commit one by one...

**Comment by caoli5288** [comment]
It's Event4j's issue. I hava a plugin that query which target player disconnect from but while it banned `null` returned and an NPE thrown. I add debug info into `BungeeCord.removeConnection` and see it called in BungeeCord but no called in Waterfall.
Seem like Event4J not catch all exception and break logic. @jamierocks @Techcable

**Comment by jamierocks** [comment]
Interesting @Techcable are you able to fix anytime soon?

**Comment by jamierocks** [comment]
I've removed the Event4J patch temporarily - https://github.com/WaterfallMC/Waterfall/commit/80bed7979d707563283635998cc326f6aa0ad5b0

**Comment by jamierocks** [comment]
This issue as it is is resolved, Event4J will be reapplied when that is fixed. Resolved.
