### ISSUE TITLE
Is Waterfall make Linux Centos crash?

### ISSUE THREAD

**Issue by netherstar** [PaperMC/Waterfall#90]
i have a minecraft network with ~500 players, i run waterfall for ~5 months with no issues. Waterfall run in Dedicated server, E3 1230 v3, 16 GB, Centos 7 64bit, 200Mbps bandwith, this is flag start.sh:

```
#!/bin/bash
while true; do
  java -Xmx5G -Xms5G -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100  -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=60 -XX:InitiatingHeapOccupancyPercent=30 -XX:TargetSurvivorRatio=90 -Dusing.aikars.suggestion=http://emc.gs/W -Dfile.encoding=UTF-8 -jar Waterfall.jar
  echo "Server restart in 60 seconds, press ctr+c to cancel"
  sleep 30
  echo "Server restart in 30 seconds, press ctr+c to cancel"
  sleep 30  
done
```

but 1 month ago, my centos dedicated server sometimes crash, this is weird error, as i ask in this topic:
http://unix.stackexchange.com/questions/302743/centos-7-all-command-not-found-except-cd/303275#303275
i thought it is hardware problem, and i switch/change to other dedicated, but error still happen.
Change Ram, change SSD still happen.
So i think it cause by Software, i remove all plugin in Waterfall, error still happen every day
i change waterfall start.sh flag to simplest, error still happen for centos .
OK, last, i switch from waterfall to bungeecord and now, 4 days and errors won't happen again
i always use waterfall latest version, i check ci.aquifermc.org every days.
This is error waterfall appear when linux crash:

![](http://i.imgur.com/FouCFd3.png)

**Comment by RhvsW** [comment]
That's definitely an issue with your java installation and not with Waterfall.

**Comment by netherstar** [comment]
No, it's not cause by java. I tried Openjdk, switch to Orace Java, buy new dedicated and install fresh java, Error still happen. So I think issues can't cause by java.
Sorry my english bad.

**Comment by jamierocks** [comment]
That does look to be an issue with your Java installation. Does this happen with bungeecord?

**Comment by netherstar** [comment]
@jamierocks 
as i said, i switch from waterfall to bungeecord 4 days ago, and error won't happen again.

**Comment by jamierocks** [comment]
Oh interesting

**Comment by jamierocks** [comment]
https://github.com/netty/netty/issues/3539 looks to be a relevant Netty issue.

**Comment by netherstar** [comment]
@jamierocks yeah, i think it cause by Netty, because this problem happen from august month. I saw that waterfall build 42 upgrade netty from 7/31.

**Comment by jamierocks** [comment]
Yeah, but we're now at the same version of Netty as BungeeCord. Perhaps some of our changes (in https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0008-Improve-Netty-update.patch) is breaking it :s

**Comment by netherstar** [comment]
it is 5 days when i switch from waterfall to bungeecord, and this issues not happen again. This issues happen in a month and make me crazy, imagine 500 players (700 in sunday) lost connection suddenly.

**Comment by jamierocks** [comment]
This is certainly a huge issue for big networks, I will have a look to the Netty docs tonight and see if any of our changes are effecting the stability.

**Comment by netherstar** [comment]
@jamierocks this is issues start happen from about 8/3 (days 3 of august month)

**Comment by caoli5288** [comment]
Maybe distro's issue? Never got this issue on my E3 CentOS6 cluster.// EDIT I restart proxy instances manually

**Comment by Techcable** [comment]
Please try running `jar -tf /usr/java/jdk1.8.0_102/jre/lib/rt.jar` to try and verify the integrity of the zip-file.
I find it _highly_ unlikely that this issue is either our fault, or netty's fault, but more likely the JDK or distro's fault.
I think there's an underlying issue here, which bungeecord is simply hiding by not accessing the corrupted parts of the jar-file.
There is almost nothing waterfall/netty can do to corrupt java's stdlib, since we don't have write permission to that directory. It's possible that either the JDK's zip-file reading is broken (unlikely), or your distro has corrupted the jar file. I think it's most likely CentOS's fault, especially since distros really like to touch things they shouldn't be touching.

**Comment by netherstar** [comment]
How to verify? here are result after run command, can you check this?
https://www.dropbox.com/s/1g6r6o6efppnykf/very.txt?raw=1

**Comment by Techcable** [comment]
Please [gist](https://gist.github.com/) it.
Also try to do `>/dev/null` at the end, to see if any error messages come out.

**Comment by netherstar** [comment]
here https://gist.github.com/tuanjr/538f8e5b99203f580665bab1bcede001

**Comment by netherstar** [comment]
@Techcable when try 

```
>/dev/null
```

Nothing show. 
After switch to bungeecord, server never crash again (18 days). So this problem should cause by Waterfall.

**Comment by Techcable** [comment]
What's the full logs of the error in waterfall?

**Comment by jamierocks** [comment]
This seems to be resolved in never Netty releases. Resolved.
