### ISSUE TITLE
1.9.0/1.9.2 clients can no longer connect

### ISSUE THREAD

**Issue by Brokkonaut** [PaperMC/Waterfall#91]
Since the update https://github.com/WaterfallMC/Waterfall/commit/40e2465947525c19bd63863d7e26a9bf6174b943 1.9.0 and 1.9.2 clients can no longer connect to the server, the log is:
http://pastebin.com/V9NmKeQ3

**Comment by jamierocks** [comment]
@Aaron1011

**Comment by Brokkonaut** [comment]
For 1.9/1.9.2 that commit is reading the wrong packet, the ids changed in 1.9.4: http://wiki.vg/Protocol_History#1.9.3-pre2

**Comment by Aaron1011** [comment]
Fixed in https://github.com/WaterfallMC/Waterfall/pull/92.

**Comment by jamierocks** [comment]
https://github.com/WaterfallMC/Waterfall/commit/bd6cfa1dfc190fd38784c1e18bbb65d57dd20e90

**Comment by Brokkonaut** [comment]
Thanks for the fast fix :)
