### ISSUE TITLE
Waterfall auto restarting

### ISSUE THREAD

**Issue by relentless-craft** [PaperMC/Waterfall#93]
Waterfall auto restarting when i add more servers in config.yml with 3 work fine when i add more they auto rebooting proxy

**Comment by kamcio96** [comment]
You can setup script with infinite loop :wink:

**Comment by jamierocks** [comment]
Is this a feature request or is there an issue here?

**Comment by Elgorond** [comment]
His wording suggests it is a bug.

**Comment by Techcable** [comment]
Can you show me your logs?

**Comment by jamierocks** [comment]
I'm pretty sure we don't watch for file changes...

**Comment by Techcable** [comment]
Yeah, we don't. I'm just hoping his logs say something that can help us figure out what he's talking about.

**Comment by Janmm14** [comment]
@relentless-craft Are you still there?

**Comment by ediTv2** [comment]
He ded @Janmm14

**Comment by jamierocks** [comment]
Well that's enough time, we can't resolve issues if we don't know the issue.
