### ISSUE TITLE
1.7.10 support

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#94]
will be possible add support for 1.7.10 like https://github.com/HexagonMC/BungeeCord

It will be great have running modded servers 1.7.10, 1.8.9 and 1.10.2 behind one proxy/hub server.

**Comment by jamierocks** [comment]
See Travertine for our 1.7 support ;)

**Comment by ghost** [comment]
Thanks a lot. Tried compile but get error:

[ERROR] Failed to execute goal on project travertine-event: Could not resolve dependencies for project io.github.waterfallmc:travertine-event:jar:1.10-SNAPSHOT: Failed to collect dependencies at net.techcable:event4j:jar:1.1.0: Failed to read artifact descriptor for net.techcable:event4j:jar:1.1.0: Could not transfer artifact net.techcable:event4j:pom:1.1.0 from/to techcable-repo (https://repo.techcable.net/content/groups/public/): Received fatal alert: handshake_failure -> [Help 1]

**Comment by jamierocks** [comment]
I should have mentioned this earlier, it builds on our ci too ;) https://ci.aquifermc.org/job/Travertine/

**Comment by Eufranio** [comment]
Travertine doesn't work :/

**Comment by jamierocks** [comment]
If you have an issue with Travertine, please report it on the appropriate issue tracker.
